### ISSUE TITLE
MOEA: weird when increases the num. of variables the num. of pareto solutions decreases from hundreds to only one

### ISSUE THREAD

**Issue by Naomilicious** [MOEAFramework/MOEAFramework#1]
Hello, I am a bit stuck on my three-objective linear problem using MOEA right now. My problem is an easy one that it constructs three linear objective functions with one equality constraint. For example, one of the objective function would be maximum the sum of parameter (i) multiplies variable (i). All the parameters are read from excel file. In addition, the constraint is the sum of variable (i) equal to an integer.

However, I don't know if the embedded code in MOEA for optimization algorithm can handle 388 number of variables, which always output only one pareto solution. The results are looked weird, and I am just wondering if it always converge to one searching zone. I tried to decrease the number of variables to 20 and the number of pareto solutions rises to 100.

I want to attach my file but looks like here not allowed.

**Comment by dhadka** [comment]
If an MOEA is unable to find a feasible solution, you will usually get a single solution...the solution with the smallest constraint violation.  I would suggest checking this first (e.g., call `solution.violatesConstraints()`).

If the solution is feasible, then it is dominating all other solutions searched by the MOEA.  You may need to increase the max evaluations to give the MOEA more time to search.  The difference in search space size from 20 to 388 variables is huge, and the MOEA may require substantially more evaluations.

You could also add some print statements to your `evaluate` method to print out the objectives & constraint values.  If you see any feasible solutions that are non-dominated with the single Pareto solution you're getting as output, then there is a bug somewhere.

It's unfortunate that Github doesn't allow attachments.  If you'd like to post example code, you could create a ticket on the old Sourceforge bug tracker and post the attachment there: http://sourceforge.net/p/moeaframework/bugs/.  Alternatively, if you're familiar with Git: fork this repository and add the code to your fork.

**Comment by Naomilicious** [comment]
Hi David,

Thank you for the quick response. I found the list of solutions was displayed partially in the system.out.print view (only showed one solution). However, when I outputted the solutions into excel, the full set of pareto solutions was displayed then. So, my problem was solved. 

I got another question that why increasing the number of iterations, the number of solution increases. For instance, there are only 31 solutions in iteration 70000, but 100 solutions in iteration 120000.

**Comment by Naomilicious** [comment]
Is there any way to further reduce the number of solutions?

**Comment by dhadka** [comment]
Internally the algorithms have a fixed population size, typically 100.  When you retrieve the results from a run, it only contains the non-dominated solutions from the population.  So at 70,000 evaluations, only 31 solutions from the 100 population members were non-dominated.  At 120,000, all 100 were non-dominated.  This is a good indicator that the MOEA has converged.  In other words, the algorithm can't produce any improved (dominating) solutions, but is able to find more non-dominated solutions and fills the population with non-dominated solutions.

There are many ways to reduce the number of solutions.  Two easy-to-implement options are:

1. Specify epsilons (using `Executor.withEpsilon(...)`) to specify the desired resolution of solutions.  See Deb et al. "A Fast Multi-Objective Evolutionary Algorithm for Finding Well-Spread Pareto-Optimal Solutions." KanGAL Report No 2003002. Feb 2003. for more details.

2. Use a preference/weighting approach to identify the most-preferred solution.

**Comment by Naomilicious** [comment]
Okay, I see. I'll try it soon.

**Comment by dhadka** [comment]
@Naomilicious Closing ticket for now.  Please reopen or create a new ticket if you have additional questions.
