### ISSUE TITLE
How to do initialization with customized population?

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#102]
Hi, I am wondering how to initialize the population using specified population, so that the algorithms can run interactively? That's to say, run the algorithms for several generations, then change some parameters and continue to run with initial population gained from the previous generation.

**Comment by dhadka** [comment]
Hi, you can use the `InjectedInitialization` class to initialize a population using a specified population.  More details are provided in my response to issue https://github.com/MOEAFramework/MOEAFramework/issues/51.

**Comment by dhadka** [comment]
Closing issue.  Please reopen or create a new issue if you have any further questions.
