### ISSUE TITLE
Problem of using Varialbe values to generate othe variable values.

### ISSUE THREAD

**Issue by MohGhad** [MOEAFramework/MOEAFramework#104]
Hi David,
I want to ask about how to generate an integer decision variables that range from [ 0 to 5 ], then using the resulted variables to generate other decision variables of type real.

This is my code which produces only 0 for both the xOrder and yOrder.

	@Override
	  public Solution newSolution() 
	  {
             for(int i=0; i< numberOfVariables; i+=4)
                 {
                    solution.setVariable(i, EncodingUtils.newInt(0,5));
                    xOrder= (int) EncodingUtils.getInt(solution.getVariable(i));
                    solution.setVariable(i+1, EncodingUtils.newInt(0,5));
                    yOrder= (int) EncodingUtils.getInt(solution.getVariable(i+1));
                 }
              double bounds[]=Bounds.bounds(xOrder,yOrder);
	      double lcx = bounds[0];
	      double ucx = bounds[1];
	      double lcy = bounds[2];
	      double ucy = bounds[3];

              for(int k=2; k< numberOfVariables; k+=4)
	       {
    	           solution.setVariable(k, new RealVariable(lcx,ucx));
    	            solution.setVariable(k+1, new RealVariable(lcy,ucy));
	       }
              return solution;
          }

Please any help with this matter.

Thanks in advance

**Comment by dhadka** [comment]
Hi, great question!  Within this library, decision variables are independent.  You can't have one variable's value/min/max change based upon another.

However, there are ways to implement the behavior you're expecting.  For example, let your real-valused variables range from 0 to 1.  Then, in the `evaluate` method, scale the real values based on the bounds defined by the integer variables.  For example:

```java

	@Override
	public Solution newSolution() {
		Solution solution = new Solution(numberOfVariables, numberOfObjectives, numberOfConstraints);

		for (int i = 0; i < numberOfVariables; i += 4) {
			solution.setVariable(i, EncodingUtils.newBinaryInt(0, 5));
			solution.setVariable(i + 1, EncodingUtils.newBinaryInt(0, 5));
			solution.setVariable(i + 2, EncodingUtils.newReal(0, 1));
			solution.setVariable(i + 3, EncodingUtils.newReal(0, 1));
		}

		return solution;
	}

	@Override
	public void evaluate(Solution solution) {
		for (int i = 0; i < numberOfVariables; i += 4) {
			int xOrder = EncodingUtils.getInt(solution.getVariable(i));
			int yOrder = EncodingUtils.getInt(solution.getVariable(i + 1));

			double bounds[] = Bounds.bounds(xOrder,yOrder);
			double lcx = bounds[0];
			double ucx = bounds[1];
			double lcy = bounds[2];
			double ucy = bounds[3];
			
			double xValue = EncodingUtils.getReal(solution.getVariable(i + 2)) * (ucx-lcx) + lcx;
			double yValue = EncodingUtils.getReal(solution.getVariable(i + 3)) * (ucy-lcy) + lcy;
			
			// now xValue is scaled between [lcx, ucx] and yValue between [lcy, ucy]
		}
	}
```

**Comment by MohGhad** [comment]
Thank you Mr  David, the way you have suggested is working excellently. Thank you very much for the help.
