### ISSUE TITLE
real-valued variable with fixed increments

### ISSUE THREAD

**Issue by fstonedahl** [MOEAFramework/MOEAFramework#106]
I need to represent a real-valued variable with fixed increment steps.  e.g. choosing from the set {1.0, 1.25, 1.5, 1.75, ..., 10.0}

It looks to me like I have three options:
1. Create a new custom Variable type (following the Color example in the MOEA guide)
2. Use a real-valued variable, and do some math to clamp it to the appropriate nearby value.  IN this example, a real variable from the interval [1.0,10.25), with a transformation of f(x) = Math.floor(x / 0.25) * 0.25
3. Use an integer variable (encoded as either binary or real under the hood), and do some math to transform it into the correct number inside my Problem's evaluate() method.  In this example, an integer between 0 and 36 inclusive, with a decoding function of f(x) = 1.0 + 0.25*x

Option 1 seems problematic for this, since I'd have to re-implement all the built-in variation operators, so I'm between Options 2 and 3.  Which of these approaches do you think would be better?  
And if I use Option 3, then would it be better to use a binary variable or a real variable "under the hood"?

**Comment by dhadka** [comment]
I would recommend using option 2.

Using a binary int (option 3) would also work, but there are some nuances.  You'll have access to fewer MOEAs, as some do not work with binary variables (differential evolution, particle swarm, etc.).  Also, the binary encoding ideally would need the number of steps to be a power of 2.

**Comment by fstonedahl** [comment]
Got it - thanks.
