### ISSUE TITLE
representing a "categorical" variable

### ISSUE THREAD

**Issue by fstonedahl** [MOEAFramework/MOEAFramework#107]
I need to be able to represent variables that can be one of a discrete set of things -- e.g. "spicy", "sweet", "sour", "salty", "minty"

I can picture doing this a few ways:
1. Use an integer variable (e.g. 0...4).  But then some values are closer together in the genotype space, when they shouldn't be.  e.g. if using a real-backed integer encoding, then "spicy" is one step away from "sweet", but 3 steps away from "salty".  (binary-backed representation is worse, since it isn't "fair" unless N is a power of 2)
2. Use a subset variable where k=1.  This logically makes sense, but feels a bit like overkill.  Also, the table at the end of the moea guide doesn't show whether any of the third party libraries support subset. Do they?
3. Create a custom type & operator that mutates uniformly to another value in the set.  This wouldn't be hard, but I'm unclear on which search algorithms support custom types.   Is it all of the same MOEA algorithms that support *ALL* the built-in representations?  Do third-party algorithms support custom types at all?

Advice appreciated!

**Comment by dhadka** [comment]
Do third-party algorithms support custom types?  Those from PISA do, others do not.  The [list of algorithms](http://moeaframework.org/javadoc/overview-summary.html#listOfAlgorithms) on the online documentation shows which are supported.

You're correct about integer vs subset.  Using a subset with k=1 would likely achieve the behavior you're looking for, although as you say it's overkill.  The subset mutation operator (replace) will randomly pick a different value with equal probability.

Another way to achieve a similar effect that may make more sense conceptually is to use a real-backed integer variable but use a uniform mutation operator.  You'll have to use a custom variation operator that applies the uniform mutation to the appropriate variables.  Details on this are discussed in this issue: https://github.com/MOEAFramework/MOEAFramework/issues/98.

**Comment by fstonedahl** [comment]
Hmm, the uniform mutation with a real variable is an interesting idea.  Would that allow it to work with algorithms like ES or GDE3 that only support real-valued variables?  Or would those algorithms not support the custom variation operator either?

(I'm assuming that since algorithms ES and GDE3 don't support binary or subset representations, they also don't support custom types?)

**Comment by dhadka** [comment]
No, ES and GDE3 wouldn't work since they use a specific operator.  Essentially, if you look at the [list of algorithms](http://moeaframework.org/javadoc/overview-summary.html#listOfAlgorithms), those that support all types will also support custom types.

**Comment by fstonedahl** [comment]
Great, thanks!
