### ISSUE TITLE
Is WFG3 for 2 objectives problem definition correct?

### ISSUE THREAD

**Issue by tomekster** [MOEAFramework/MOEAFramework#108]
Hello David,
I am working  with WFG problem set and I have tested MOEAD, NSGA-II, NSGA-III and MSOPS algorithms on WFG3 problem with 2 objectives. During my experiments none of this four algorithm have ever returned single solution with negative value of second objective. It bugs me since in file WFG3.2D.pf I can see many solutions lying on a segment with endpoints (2,0), (3,-2). Are those algorithm incapable of searching for such solution or is there  something wrong with WFG3 problem definition or maybe provided reference PF is incorrect? I would be very grateful for clarification.
Best,
Tomasz

**Comment by dhadka** [comment]
Yea, it looks like something is incorrect with that reference set.  Here's some code that will generate the reference set programmatically with the code and compare that to the reference set file.

```java

		// generate a new reference set
		NondominatedPopulation newSet = new NondominatedPopulation();
		WFG3 wfg3 = new WFG3(1, 10, 2);
		
		for (int i = 0; i < 1000; i++) {
			Solution solution = wfg3.generate();
			wfg3.evaluate(solution);
			newSet.add(solution);
		}
		
		// load the existing reference set
		Population oldSet = PopulationIO.readObjectives(new File("./pf/WFG3.2D.pf"));
		
		// plot the two
		new Plot()
			.add("New", newSet)
			.add("Old", oldSet)
			.show();
```

You can see the points in red, which are from the programmatically generated set, are all positive, whereas the file contains the negative values in blue.

![refplot](https://cloud.githubusercontent.com/assets/2496211/25819304/8f5a4f2c-33fb-11e7-9c31-ee094aa0f0a6.png)

According to the [WFG paper](http://www.wfg.csse.uwa.edu.au/publications/WFG2006c.pdf) on page 24, the points should all be positive, ranging between approx. (0, 4) and (2, 0).

**Comment by dhadka** [comment]
The `pf/WFG3.2D.pf` file is updated.  Thanks for bringing this to my attention.
