### ISSUE TITLE
Does MOEA framework include the cooperative coevolution feature for solving large scale multiobjective optimization problems

### ISSUE THREAD

**Issue by Naomilicious** [MOEAFramework/MOEAFramework#109]
Hello, 

Recently, I read an article entitled "Use of cooperative coevolution (CC) for solving large scale multiobjective optimization problems" by Antonio, L.M, and Coello, C.A.C 2013, which looks very efficient for solving large scale multi-objective optimization problems. This method decomposes the dimension of decision vectors into several sub-dimension vectors with equal size, and uses MOEAs (GDE3 in the article) to solve it.

I was wondering whether the MOEA framework incorporate this CC algorithm? That would be very helpful for my research.

Thanks,
Naomi

**Comment by dhadka** [comment]
Hi Naomi,

No, it currently doesn't have any CC implementations.  However, it should be possible to develop your own implementation.

Kind Regards

**Comment by Naomilicious** [comment]
Okay, thanks.
