### ISSUE TITLE
Building trees does not take the maximum size of a node into consideration

### ISSUE THREAD

**Issue by ccreeten** [MOEAFramework/MOEAFramework#110]
Hey all, I have a question about the tree building implementations of the *Rules* class. 

As far as I can tell, the implementations don't take into consideration the maximum possible size a further generated node could get. In the case of full tree growing, if this is smaller than the remaining size of the subtree to be generated, it will stop early and take a terminal. This results in a non-full tree. 

A bigger problem is when at depth 1 a node is chosen, for which all possible parameters are always size > 1. In this case, the generation breaks and throws an exception, because no valid terminals are available. 

It looks like currently a function should always have a possible terminal for each of its parameters, but it is not the case in my model. As far as I can tell, my use case seems to be valid. I could give a small example if my question is unclear.

Am I missing/overlooking something?

**Comment by dhadka** [comment]
Hi, thank you for your question.  I think I have a good idea of what you're encountering, but a small example wouldn't hurt.

This implementation essentially assumes that you can initialize the tree to any depth (from 2 up to the user's max depth).  This essentially requires each function parameter to have at least one valid terminal.

A few possible solutions are (1) allow the trees to violate the depth when these situations arise, (2) provide a special terminal that indicates an error - which results in a constraint violation, or (3) somehow calculate the min/max depth for a given node and use that to choose only those nodes that would result in a valid tree.

**Comment by ccreeten** [comment]
Yes, this is the problem I am having. At the second to last depth, functions are taken with parameters which can only be non-terminals themselves. 

Currently this also means the documentation of the ```buildTreeFull``` method is not entirely consistent with what is returned, as there might exist leaf nodes at a depth lower than the maximum given depth. This because of the reason you gave about what the implementation assumes.

In my case I prefer to only get valid trees, and with an expected structure. So option 3 seems the best in my case, and personally feels like the natural way. It can be implemented for example as stated in the [Strongly Typed Genetic Programming](http://davidmontana.net/papers/stgp.pdf) paper, page 11.
