### ISSUE TITLE
Plotting Pareto Front

### ISSUE THREAD

**Issue by Tomisiak** [MOEAFramework/MOEAFramework#115]
Hello,

Is there any way to read `.adf` file created using Diagnostic Tool in order to view objective values of Approximation Set? I would like to plot the curve of solutions Pareto Front.

Thanks in advance

**Comment by dhadka** [comment]
Hi,

When I wrote the Diagnostic Tool, I simply serialized the data for convenience.  You can follow a similar procedure to deserialize the file to obtain the data.  See https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/analysis/diagnostics/Controller.java#L415

```java

	public void loadData(File file) throws IOException {
		ObjectInputStream ois = null;

		try {
			ois = new ObjectInputStream(new FileInputStream(file));

			Map<?, ?> data = (Map<?, ?>)ois.readObject();

			for (Map.Entry<?, ?> entry : data.entrySet()) {
				ResultKey key = (ResultKey)entry.getKey();
				List<?> list = (List<?>)entry.getValue();

				for (Object element : list) {
					add(key, (Accumulator)element);
				}
			}
		} catch (StreamCorruptedException e) {
			throw new IOException("This file does not appear to be a data " +
					"file generated by the diagnostic tool.", e);
		} catch (Exception e) {
			throw new IOException(e);
		} finally {

			if (ois != null) {
				ois.close();
			}
		}
	}
```

If I remember correctly, ResultKey identifies the algorithm/problem.  The list stores the results from each seed.

Hope this helps!
