### ISSUE TITLE
Why running the NSGA-II algorithm in MOEA framework always delivers small number of solutions

### ISSUE THREAD

**Issue by lsun0** [MOEAFramework/MOEAFramework#116]
Hi, 
I used MOEA  framework to solve two-objective, and employed the NSGA-II algorithm with populationSize=130. I don't know why the number of output solutions are very small (e.g 2 or 3 solutions)?! How can I fix this problem in the jave code?

Thanks in advance for your help.

**Comment by saviosampaio** [comment]
Hi,

What is your configuration? maxEvaluations? Seeds? "problem" (function)?

**Comment by dhadka** [comment]
I suspect you're only seeing 2-3 solutions because the algorithm only returns the non-dominated solutions, not the entire population.

Closing the issue for now since there has been no response.  Please reopen or create a new one.
