### ISSUE TITLE
MOEA-D/DRA (MOEAD) with problem UF6 gets very different from CEC2009 results: using prune(100)

### ISSUE THREAD

**Issue by saviosampaio** [MOEAFramework/MOEAFramework#117]
Dear Sirs,

I'm trying to reproduce approximate results to those contained in the MOEAD algorithm paper, published in CEC2009.

- http://dces.essex.ac.uk/staff/zhang/MOEAcompetition/CEC09final/papers/MOEAD.pdf

The IGD average, for UF6 problem, in paper is 0.00587.

In my tests I gets 0.11863, 0.11388, 0.13488, approximately.

I am using this configuration:

> properties.setProperty("populationSize", 600);
> properties.setProperty("maxEvaluations", 300000);
> properties.setProperty("de.crossoverRate", "1.0"); // CR
> properties.setProperty("de.stepSize", "0.5"); // F
> properties.setProperty("updateUtility", "50"); // Recommended in MOEAD.java

and:

> .withProblem("UF6")
> .withAlgorithm("MOEAD")
> .runSeeds(30)

But, to reduce last population from 600 to 100, to calculate IGD average, I used "prune(100)" with "NondominatedSortingPopulation":

> Collection<NondominatedPopulation> seedsResults = executor.runSeeds(seeds);
> Collection<NondominatedPopulation> seedsResults2 = new ArrayList<NondominatedPopulation>();
> for(NondominatedPopulation pop : seedsResults) {
> 	NondominatedSortingPopulation pop2 = new NondominatedSortingPopulation();
> 	pop2.addAll(pop);
> 	if(pop2.size()>100){
> 		pop2.prune(100);
> 	}
> 	NondominatedPopulation pop3 = new NondominatedPopulation();
> 	pop3.addAll(pop2);
> 	seedsResults2.add(pop3);
> }

In the MOEAD paper (CEC2009) we can read:

>
>"In calculating the IGD values, 100 nondominated solutions selected from each ﬁnal population were used in the case of two objectives, 150 in the case of three objectives and 800 in the case of ﬁve objectives.
>
>The ﬁnal solution set A is selected from the output O = { F(x1), ... , F(xN) } of the algorithm is as follows:
>
>* For the instances with two objectives, the set 100 ﬁnal solutions are the solution set consisting of the best solutions in O for the subproblems with weights (0, 1), (1/99, 98/99), ... , (98/99, 1/99), (1, 0).
>

Can anyone replicate this 100-solution selection strategy for calculating IGD, according to MOEAD paper and using MOEAFramework?

Thank you very much.

**Comment by dhadka** [comment]
Also note that the paper doesn't provide much detail on how they compute IGD.  Some papers calculate the sum of squares distance (similar to how generational distance is calculated), others simply sum the distances. Do they normalize? How many points are in the reference set?

They do provide source code, so you could try looking there.  I unfortunately am traveling and can't check right now.

**Comment by saviosampaio** [comment]
Hi David,

I searched the source code in "moead-cppcec2009.zip" but did not find anything related.

In file "moead_cec2009_2011version.zip" there is a code "cec09filter.cpp". Should be it.

Thank you.
