### ISSUE TITLE
Analzyer.showAggregate() calculate mean or only the sum?

### ISSUE THREAD

**Issue by abdulhameedpk** [MOEAFramework/MOEAFramework#12]
I found no information in the code which explain what is calculated by ```Analzyer.showAggregate()```. 
Is it calculated the mean value of a metric for all seeds (i.e runs) OR only the sum for all runs is calculated?

**Comment by dhadka** [comment]
The aggregate value combines the Pareto approximate sets from each seed into a single combined Pareto set.  Then, the performance metric is calculated using this combined Pareto set.

**Comment by abdulhameedpk** [comment]
So I Should not use the printed aggregate value as the average of all runs. Instead should calculate the average at the end of simulation. A quick hint is requested in this regard.

**Comment by dhadka** [comment]
Correct, you should use the median value that is output by the analyzer.  If you want the mean, you can call:

    analyzer.showStatistic(new org.apache.commons.math3.stat.descriptive.moment.Mean());

before running the analysis.  These will output the median/mean value across all runs.

**Comment by abdulhameedpk** [comment]
Thanks Dr. David
