### ISSUE TITLE
How to get my problem from NondominatedPopulation result

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [MOEAFramework/MOEAFramework#121]
Hi, 
I want to get my problem from result population 

        NondominatedPopulation result = new Executor()
                .withProblemClass(myProblem.class)
                .withAlgorithm("NSGAII")
                .withMaxEvaluations(50000)
                .distributeOnAllCores()
                .run();

bw.write("Food Id : " + **problem.getFoodId(0)** + "  Food Name : " + **problem.getFoodName(0)** + " ");

As we did in Jmetal : 
     problem = new MKP("Binary", "man", 25);
     algorithm = new NSGAII(problem);
    SolutionSet population = algorithm.execute();
bw.write("Food Id : " + **problem.getFoodId(0)** + "  Food Name : " + **problem.getFoodName(0)** + "

**Comment by dhadka** [comment]
Please try passing the problem instance directly to the Executor:

```java

        Problem problem = new myProblem();

        NondominatedPopulation result = new Executor()
                .withProblemClass(problem)
                .withAlgorithm("NSGAII")
                .withMaxEvaluations(50000)
                .distributeOnAllCores()
                .run();

        bw.write("Food Id : " + problem.getFoodId(0) + "  Food Name : " + problem.getFoodName(0));
```

**Comment by CumaliTurkmenoglu** [comment]
Thanks for your answer. unfortunately it says:

no suitable method found for withProblemClass(DietProblem)
    method ProblemBuilder.withProblemClass(Class<?>,Object...) is not applicable
      (argument mismatch; DietProblem cannot be converted to Class<?>)
    method ProblemBuilder.withProblemClass(String,Object...) is not applicable
      (argument mismatch; DietProblem cannot be converted to String)
    method Executor.withProblemClass(Class<?>,Object...) is not applicable
      (argument mismatch; DietProblem cannot be converted to Class<?>)
    method Executor.withProblemClass(String,Object...) is not applicable
      (argument mismatch; DietProblem cannot be converted to String)
----
(Alt-Enter shows hints)

**Comment by dhadka** [comment]
I'm sorry, I had that wrong.  Use `withProblem` instead of `withProblemClass`.  http://moeaframework.org/javadoc/org/moeaframework/Executor.html#withProblem(org.moeaframework.core.Problem)

**Comment by CumaliTurkmenoglu** [comment]
Thank you. The problem is solved. I am geting familiar with MOEA.
