### ISSUE TITLE
Do variable range discrepancies matter?

### ISSUE THREAD

**Issue by fstonedahl** [MOEAFramework/MOEAFramework#123]
For how many of the algorithms/operators would it matter if variable ranges are drastically different between variables...  i.e. 
var1 ranges from 0.0 to 1.0
var2 ranges from -5000 to 5000

Are the variation (mutation/crossover) operators particularly sensitive to things like this?  Other aspects of the algorithms?

I'm trying to write some general-purpose code that uses MOEA, and I *could* normalize all the variable ranges (e.g. to be between 0 and 1) if it would help the search algorithms perform better, but it's an extra scaling step that would have to be performed on the way in & out, so it would be more convenient to skip this if it's not necessary.

**Comment by dhadka** [comment]
Hi,

It depends heavily on the algorithm and operator as to whether they are impacted by the scaling of variables.  I unfortunately don't have that information immediately available.

If you're concerned about the scaling, then I'd recommend scaling.  You could also potentially create a wrapper class, e.g., NormalizedProblem, that takes a problem and normalizes it's decision variables.  We know what the min/max are for ints and doubles.

Kind Regards

**Comment by fstonedahl** [comment]
Okay, I'll think about it some more.  Thanks.
