### ISSUE TITLE
Interfaces for evaluators in other languages

### ISSUE THREAD

**Issue by imilos** [MOEAFramework/MOEAFramework#124]
Dear David,

Examples 5 and 6 work perfectly, but I'd like to employ MOEA Framework to solve multi-objective optimization problem whose evaluator is written in C#. Is there a simple way to do it? 
Of course, one can use **ProcessBuilder** within normal **AbstractProblem**, but this includes multiplication of process create and termination overhead.

**Comment by fstonedahl** [comment]
Hi -- fellow user here.  It sounds to me like using standard I/O with a subclass of the **ExternalProblem** class is exactly what you're looking for.  The external process gets launched once, and they communicate data to/from using a very simple  protocol across stdin/stdout.  There's an example of it (using Python) given in Section 10.4 of the Beginner's Guide e-book (which is well worth the $15 price! see: http://www.lulu.com/shop/david-hadka/beginners-guide-to-the-moea-framework/ebook/product-22522401.html).

**Comment by imilos** [comment]
Thanks Forrest! I will check this out! The specification of that simple stdio interface is exactly what I was loking for.
