### ISSUE TITLE
the pareto fronts of DTLZ & WFG in the "pf" folder is calculated when k==? , l==?

### ISSUE THREAD

**Issue by zhoudiprivateChina** [MOEAFramework/MOEAFramework#126]
Hi,  may i know the setting of parameters k and l for .pf in DTLZ & WFG?
 eg: WFG1.2D.pf

Thx

**Comment by dhadka** [comment]
Hi,

You can find that information here: https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/problem/StandardProblems.java#L654

The three arguments are k, l, and m.  The defaults you see there are what was used to produce the Pareto front files.  You can, of course, provide different values if desired.

Best Regards

**Comment by AmirHosein-Ahf** [comment]
as time goes on, I found them more attractive!!!!!!!!!
