### ISSUE TITLE
exposing Algorithms' default parameters via code

### ISSUE THREAD

**Issue by fstonedahl** [MOEAFramework/MOEAFramework#128]
**Feature request:** For writing a graphical tool that uses MOEA as a backend, it would really be great if it was possible to inspect the properties that a given Algorithm supports.  (This would also be excellent for MOEA's graphical DiagnosticTool.)

The simplest version of this would be to have each AlgorithmProvider provide a `getDefaultPropertiesForAlgorithm(String algorithmName)` method that returns a `TypedProperties` object that contains the default key/value pairs that the algorithm uses.  (To avoid redundancy in parameter specification, all of the default values that are currently hardcoded into the newXXX methods could be removed.)

This feature would make it possible to have a UI query the AlgorithmProvider to find out what sensible defaults are, stick them into a table or something, and allow users to play with them.

An even better (but more complex) version could provide additional reflection abilities -- e.g., providing information about the Type of each property.

Finally, it would also be nice to programmatically discover which variation operators and which types of variables are supported by a given algorithm.  

However, I think extracting out the default properties is the low-hanging fruit here.  In fact, I might be able to find an undergraduate student to do the easier version of this, as long as your test coverage is good enough that it would catch any mistakes that might be made in the process!

**Comment by dhadka** [comment]
I've considered implementing something like this, where you could query each parameter including name, description, type, min/max value, etc.  Where it got tricky is that the available parameters can change based on other selected parameters.  If you're interested in tackling this problem, please go ahead.  I can try to dig up my attempt at implementing this feature and push it to a separate branch.

**Comment by fstonedahl** [comment]
Hmm, yeah I see the difficulty.  I think one could make the _default_ parameters available without worrying about dependencies between parameters, but this wouldn't describe the full range of options for people.

It would be nice to solve this problem in a comprehensive way (perhaps using some sort of tree structure to capture the dependencies?), but I'm not sure if I have time to tackle that.  Maybe I will just do something hack-ish in my own codebase to provide default parameter suggestions...
