### ISSUE TITLE
Minor correction in  MOEAD.updateSolution() as part of issue#10

### ISSUE THREAD

**Issue by abdulhameedpk** [MOEAFramework/MOEAFramework#13]
Dear David,

A minor correction is required as part of  issue#10. The default version of MOEAD does not use `updateUtility`, so the `MOEAD.updateSolution()` should looks 

```
private void updateSolution(Solution solution,
            List<Integer> matingIndices) {

int c = 0;
        PRNG.shuffle(matingIndices);

        for (int i = 0; i < matingIndices.size(); i++) {
            Individual individual = population.get(matingIndices.get(i));

            if (fitness(solution, individual.getWeights()) < fitness(
                    individual.getSolution(), individual.getWeights())) {
                individual.setSolution(solution);


                if(updateUtility>=0) **//do this only for MOEA/D-DRA**
                c = c + 1; 
            }


            **//if (c >= eta) {**
            if (updateUtility>=0 && c >= eta) {  **//do this only for MOEA/D-DRA**
                break;
            }


```

**Comment by dhadka** [comment]
The authors introduce the c / eta parameters in

    Li, H. and Zhang, Q. "Multiobjective Optimization problems with Complicated Pareto Sets,
    MOEA/D and NSGA-II." IEEE Transactions on Evolutionary Computation, 13(2):284-302, 2009

which is the version the MOEA Framework's MOEA/D implementation is derived from (the MOEA/D authors indicate these changes overcome many limitations of the original MOEA/D).

You're right that the original MOEA/D in

    Q.  Zhang and  H. Li,  MOEA/D: A Multi-objective Evolutionary Algorithm Based on Decomposition,
    IEEE Trans. on Evolutionary Computation, vol.11, no. 6, pp712-731  2007.

does not use c / eta.  If we want to support the original MOEA/D, there are likely several other differences that need to be addressed.  One I can think of is that the original MOEA/D restricted parent selection to the neighborhood, whereas the newer version (implemented in the MOEA Framework) has a small probability (1-delta) of selecting from the entire population.  This provides increased exploration.
