### ISSUE TITLE
about DBEA algorithm

### ISSUE THREAD

**Issue by zhoudiprivateChina** [MOEAFramework/MOEAFramework#132]
Hi, when i run Example2 to test DBEA, it seems DBEA performs much worse than other algorithms on all the metrics, especially on DTLZ1_2, DTLZ4_2, DTLZ7_2. 
DBEA can only find two candidate solutions on DTLZ4_2. I'm confused, the performance of DBEA in MOEA Framework is far from what declared in its original paper "A Decomposition Based Evolutionary Algorithm for Many-Objective Optimization."

**Comment by zhoudiprivateChina** [comment]
DBEA performs poorly on ZDT6 too.

**Comment by dhadka** [comment]
That's odd.  When I run DTLZ4_2 using the diagnostic tool, it looks as one would expect:

![image](https://user-images.githubusercontent.com/2496211/29373239-9a7c3cac-827b-11e7-8b6e-df760ed998cd.png)

Could you please share the code you're using to run DBEA?

If you're not, perhaps try running multiple seeds.  Maybe one bad seed is only producing two candidate solutions.

**Comment by zhoudiprivateChina** [comment]
OOOOOOOOO,,,,my fault, really sorry, you are right.

**Comment by zhoudiprivateChina** [comment]
OOOO...., my fault, you're right, i forget i just output the result of the  i-th round. Sorry for bothering you. Thanks a lot for your prompt reply. 

		double[] f1 = new double[100];
		double[] f2 = new double[100];

		List<NondominatedPopulation> result = new Executor()
				.withAlgorithm("DBEA")
				.withProblem("DTLZ4_2")
				.withMaxEvaluations(25000)
				.runSeeds(30);
		
		NondominatedPopulation nondominatedSet;
		int j = 0;
		
		Random rand = new Random();
		int i = rand.nextInt(); 
		i = rand.nextInt(30); 
		
			nondominatedSet = result.get(i);
			
			for (Solution solution: nondominatedSet){
				if (!solution.violatesConstraints()){
					f1[j] = solution.getObjective(0);
					f2[j] = solution.getObjective(1);
					j++;
				}
			}

**Comment by zhoudiprivateChina** [comment]
But how could i obtain the average pareto front of 30 rounds? I tried to sort f1 like follows:
                       for (int k = 0 ; k < 100; k++) {
				map.put(f1[k], k);
			}
			Arrays.sort(f1);
			for (int k = 0; k < 100; k++) {
				f22[k] = f2[(Integer) map.get(f1[k])];
			}
Then i tried to average these 30 (f1)s and 30 (f2)s. But since in some round, the number of obtained candidate solutions are less then 100, there are some 0.0 in f1 and f2. So  i couldn't just simply average these 30 (f1)s and 30 (f2)s.
