### ISSUE TITLE
The computation of Hypervolume takes a long time

### ISSUE THREAD

**Issue by VictorPih** [MOEAFramework/MOEAFramework#133]
Hi. I use MOEAFramework to test algorithms. Here is my code

		String[] algorithms = {"NSGAII", "NSGAIII", "I-DBEA"};

		//setup the experiment
		Executor executor = new Executor()
				.withProblemClass(WFG2.class, 28, 20, 15)
				.withProperty("populationSize", 136)
				.withMaxEvaluations(30000);

		Analyzer analyzer = new Analyzer()
				.withProblemClass(WFG2.class, 28, 20, 15)
				.includeHypervolume()
				.showStatisticalSignificance();

		//run each algorithm for 30 seeds
		for (String algorithm : algorithms) {
			System.out.println();
			System.out.println(algorithm);
			analyzer.addAll(algorithm, 
					executor.withAlgorithm(algorithm).runSeeds(30));
		}

I wait for hours, without any results.
I find that, it takes just a few minutes to run 3 algorithms. And I can get results if with other metrics, so as IGD and GD.

Any suggestions?

Waiting for your reply.

**Comment by dhadka** [comment]
The built-in hypervolume calculation will slow down significantly when the number of objectives increases beyond 6 or so.

Follow the instructions here (https://github.com/MOEAFramework/Hypervolume) to compile and link one of the faster hypervolume calculations.  I'd recommend WFG.

**Comment by VictorPih** [comment]
Thanks for your reply! I try the WFG hypervolume calculation with a smaller number of objectives, it works.
However, while I use it with the code above, it still take too long time. I have wait for 9 hours, the program is still running, without any output.

**Comment by dhadka** [comment]
Can you please verify that WFG.exe is running?  If it is and it still takes a long time, try the HOY hypervolume code next.  If it still takes a long time, it could simply be that the # of points + the # of objectives is too large to compute the exact hypervolume.  If that's the case, then you'd likely need to look for codes that approximate the hypervolume.

**Comment by VictorPih** [comment]
I found that, the distribution of solutions in the PS is a important factor of the computation time. With the same PS size generated by the same algorithm on the same test problem, some PS only need a few seconds to calculate HV, others need hours to calculate.

**Comment by VictorPih** [comment]
The WFG/HOY is running. I check it with a process manager.
