### ISSUE TITLE
Doubt on Example 4 (http://moeaframework.org/examples.html#example4)

### ISSUE THREAD

**Issue by tsprates** [MOEAFramework/MOEAFramework#140]
Hi,
Recently I looking at the examples at http://moeaframework.org/examples.html and I saw that on **line 67** of the `Example 4` there's a call to `CoreUtils.castVariablesToDoubleArray(solution)` but searching in the file `Example4.java` it seems it was renamed to `EncodingUtils.getReal(solution)`. 
BTW Great work! Amazing project!

**Comment by dhadka** [comment]
Thanks! Updated the code and it'll appear on the website after the next release.
