### ISSUE TITLE
Use of DV as Permutations with Borg MOEA 

### ISSUE THREAD

**Issue by mariocastrogama** [MOEAFramework/MOEAFramework#142]
Hello,

This is more of a question rather than an issue
- Is it possible to use Borg MOEA having Permutations as decision variables?

If NOT the case:
- Which algorithms are more suitable within MOEA Fr? 

mvg

**Comment by dhadka** [comment]
Hi,

> Is it possible to use Borg MOEA having Permutations as decision variables?

Currently no.  This is a limitation of the implementation and not the algorithm.  The original implementation in C only supports real-valued types.

> Which algorithms are more suitable within MOEA Fr?

You can find a list of the algorithms and what types they support here: [moeaframework.org/javadoc/overview-summary.html#listOfAlgorithms](http://moeaframework.org/javadoc/overview-summary.html#listOfAlgorithms).  Any that have Permutation marked as Yes are supported.  NSGA-II is a good one to start with.

**Comment by mariocastrogama** [comment]
Thank you!
