### ISSUE TITLE
MOEA Dianostic Tool does not plotting chart correct in my problem

### ISSUE THREAD

**Issue by rickshido** [MOEAFramework/MOEAFramework#145]
Dear users,

Anyone has the problem with chart plotting?
All "Displayed Metrics" are presenting a flat horizontal line. It occurs both in my problem and the MOEA examples.

However, when I run the examples in Dianostic tool provided by MOEAFramework-2.12-Demo.jar, the "Displayed metrics" are shown correctly.

Anyone can help me?

Best regards

**Comment by dhadka** [comment]
Hi,

I suspect you need to provide a reference set for your problem if you haven't done so already.  Some of the other analysis codes in this software will automatically create a reference set from your collected data, but the diagnostic tool doesn't...it expects the reference set to be given explicitly.

The easiest way to achieve this is to edit StandardProblems.java and add the code to create your problem and load the reference set from a file.

The more flexible approach is to create a ProblemProvider for your custom problem.  This is a bit more complex to set up and is covered in Chapter 6 in the beginner's guide, if you have a copy.

Thanks
