### ISSUE TITLE
NSGA-II archive set

### ISSUE THREAD

**Issue by toluboltz** [MOEAFramework/MOEAFramework#146]
Please how do I specify an archive set for the NSGA-II algorithm on the framework

**Comment by dhadka** [comment]
NSGAII currently doesn't let you specify an archive.  However, there's a quick way to add this support if you edit StandardAlgorithms.java:

```java

	private Algorithm newNSGAII(TypedProperties properties, Problem problem) {
		int populationSize = (int)properties.getDouble("populationSize", 100);

		Initialization initialization = new RandomInitialization(problem, populationSize);

		NondominatedSortingPopulation population = new NondominatedSortingPopulation();
		
		// Include an archive
		NondominatedPopulation archive = null;

		if (properties.contains("epsilon")) {
			archive = new EpsilonBoxDominanceArchive(
					properties.getDoubleArray("epsilon", 
							new double[] { EpsilonHelper.getEpsilon(problem) }));
		}

		TournamentSelection selection = null;
		
		if (properties.getBoolean("withReplacement", true)) {
			selection = new TournamentSelection(2, new ChainedComparator(
					new ParetoDominanceComparator(),
					new CrowdingComparator()));
		}

		Variation variation = OperatorFactory.getInstance().getVariation(null, properties, problem);

		return new NSGAII(problem, population, archive, selection, variation, initialization);
	}
```

Then, you can run:

```java

		new Executor()
		    .withAlgorithm("NSGAII")
		    .withProperty("epsilon", new double[] { 0.1, 0.1 }) // Turn on epsilon dominance archive
		    ...
```

This example uses an epsilon-dominance archive.  You can also replace this with other archives if desired.
  You would just need to replace the "epsilon" parameter with something else.

**Comment by toluboltz** [comment]
Thank you for the response. Please how do I use the FitnessBasedArchive in this case?

**Comment by dhadka** [comment]
In the example above, instead of using the property "epsilon", you can create the "indicator" property which lets you select the kind of indicator used.  Then you create the fitness evaluator and the fitness-based archive.

```java

		int archiveSize = properties.getInt("archiveSize", 100);
		String indicator = properties.getString("indicator", "hypervolume");
		IndicatorFitnessEvaluator fitnessEvaluator = null;

		if ("hypervolume".equals(indicator)) {
			fitnessEvaluator = new HypervolumeFitnessEvaluator(problem);
		} else if ("epsilon".equals(indicator)) {
			fitnessEvaluator = new AdditiveEpsilonIndicatorFitnessEvaluator(
					problem);
		} else {
			throw new IllegalArgumentException("invalid indicator: " +
					indicator);
		}

		FitnessBasedArchive archive = new FitnessBasedArchive(fitnessEvaluator, archiveSize);

		return new NSGAII(problem, population, archive, ...);
```

**Comment by toluboltz** [comment]
Thanks. Running the code seems to be running into the problem of casting the FitnessBasedArchive to EpsilonBoxDominanceArchive.

**Comment by dhadka** [comment]
Could you please include the stack trace shown in the exception?  Thanks!

**Comment by toluboltz** [comment]
Here is the stack trace:

Exception in thread "main" java.lang.ClassCastException: org.moeaframework.core.fitness.FitnessBasedArchive cannot be cast to org.moeaframework.core.EpsilonBoxDominanceArchive
	at org.moeaframework.algorithm.NSGAII.getArchive(NSGAII.java:161)
	at org.moeaframework.algorithm.NSGAII.getArchive(NSGAII.java:1)
	at org.moeaframework.algorithm.AbstractEvolutionaryAlgorithm.initialize(AbstractEvolutionaryAlgorithm.java:96)
	at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:159)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:816)
	at org.moeaframework.Executor.run(Executor.java:743)
	at com.kml.emo.RunIUUProblemV1.main(RunIUUProblemV1.java:17)

**Comment by dhadka** [comment]
That's my fault for not testing my example.  The NSGAII class only allows EpsilonBoxDominanceArchives.  Here's an example that supports FitnessBasedArchive.  I had to create a new class called FitnessBasedNSGAII.

https://gist.github.com/dhadka/b03d753291c12a8035a28e82af77baab
