### ISSUE TITLE
Subset encoding with varying lengths

### ISSUE THREAD

**Issue by toluboltz** [MOEAFramework/MOEAFramework#147]
Hello David,
Is it possible to use the subset encoding with varying lengths? Say......I want to a choose between 3 - 5 objects for 100 based on their objective function values. For example [1, 2, 3, 4, 5] will give the solution pick objects 1 - 5 and [12, 2, 4] the solution objects 12, 2, 4 and [8] will mean pick only object 8. And all these solutions are non dominated.

Is there a way I can achieve this using subset encoding?

Thank you.

**Comment by dhadka** [comment]
Subset is only for fixed-size subsets.

If you want to pick k out of N items, where k ranges from 0 to N, then you can use a BinaryVariable.  If the i-th bit is 1, then you pick the i-th item.

If you want to limit the number of items picked, you would need a new encoding for variable-size sets.  This includes implementing the corresponding operators (e.g., set crossover, replace, add, remove).  You can probably reuse a lot from the subset implementation if you choose this option.

I'm interesting in implementing the second option myself, but given my time constraints, I can't guarantee I'd have something anytime soon.

**Comment by dhadka** [comment]
I've added an initial implementation of variable-length subsets in commit 69649d4d5cf9b16e045a8592a12348847e380135.  Use the new three-argument constructor (`new Subset(3, 5, 100)`) to set the minimum size, maximum size, and number of items to pick from.  Please be aware that this needs more testing and the implementation may change in the future.

**Comment by toluboltz** [comment]
Thank you for the implementation. I tried it and it worked just as you described. But what I was describing was the results containing a mixture of different lengths. For example like the sample argument constructor, the results can contain [a, b, c], [a, d, e, f, I], [w, a, b], [x, y, f, b] etc.

Can this be achieved? Sorry for the back and forth. Thank you

**Comment by toluboltz** [comment]
Hi David,

Sorry about the earlier comment. I debugged it and it works exactly as described. Thank you
