### ISSUE TITLE
NondominatedPopulation: Adding solutions with the same objective values

### ISSUE THREAD

**Issue by Nozo** [MOEAFramework/MOEAFramework#15]
At the end I attached the implementation of the add method of the NondominatedPopulation. Especially I respond to the following line:

    else if (!allowDuplicates && distance(newSolution, oldSolution) < Settings.EPS) {
		
I recognized, if there are 2 different solutions with different decision variables but the same objective values only one Solution is added to the NondominatedPopulation. In My Opinion this is because the decision is only made in the objective space. There maybe should be a possibility to check the decision variables to distinguish if the solutions are duplicates or only have the same objective values but different decision variables.

```javascript
	@Override
	public boolean add(Solution newSolution) {
		Iterator<Solution> iterator = iterator();

		while (iterator.hasNext()) {
			Solution oldSolution = iterator.next();
			int flag = comparator.compare(newSolution, oldSolution);

			if (flag < 0) {
				iterator.remove();
			} else if (flag > 0) {
				return false;
			} else if (!allowDuplicates &&
					distance(newSolution, oldSolution) < Settings.EPS) {
				return false;
			}
		}

		return super.add(newSolution);
	}
```

**Comment by dhadka** [comment]
Thanks for the suggestion!  I think this would be a useful feature.  We would want it to support three cases:

1. Do not allow any solutions with duplicate objectives.
2. Allow duplicates if the solutions have different decision variables.
3. Allow all duplicates (needed for nondominated sorting)

I will likely make this an additional argument to the constructor and also allow it to be set as a global property.

**Comment by Nozo** [comment]
Can you estimate when you are publishing a new version of the MOEA-Framework with this features?

**Comment by dhadka** [comment]
@Nozo, I plan to work on this over the weekend, so likely by next Monday.

**Comment by Nozo** [comment]
perfect, thank you very much!

**Comment by dhadka** [comment]
Hi, this feature is implemented in the branch fix_issue_15.  If you do not have Git, you can download the contents directly from https://github.com/MOEAFramework/MOEAFramework/tree/fix_issue_15 by clicking the "Download ZIP" button on the right-hand side of the page.

The handling of duplicate solutions can be controlled with three options: NO_DUPLICATES, ALLOW_DUPLICATES, and ALLOW_DUPLICATE_OBJECTIVES.  These options can either be set when creating a NondominatedPopulation, or set globally by modifying global.properties:

      org.moeaframework.core.duplicate_mode = ALLOW_DUPLICATE_OBJECTIVES

In your case, you would want ALLOW_DUPLICATE_OBJECTIVES, as it will allow two solutions that have identical objectives but different decision variables.

Needs more testing before moving into the master branch.

**Comment by Nozo** [comment]
Thank you very much, yesterday I already integrated the code and it works fine!

**Comment by dhadka** [comment]
Closing this ticket.  Please open a new one if you have additional questions.
