### ISSUE TITLE
Print Out Initial Population

### ISSUE THREAD

**Issue by toluboltz** [MOEAFramework/MOEAFramework#151]
Hello,

Please is there a way to print out the initial population to help with my debugging

**Comment by toluboltz** [comment]
Figured out how to print it. Thanks

**Comment by Amit-1984** [comment]
hello @toluboltz  also kindly share the same with others also so that it can be understood by others

**Comment by toluboltz** [comment]
Hello @Amit-1984, you have manually run the algorithm like this

              `// define the problem
		Problem problem = new IUUProblemV5();
				
		// create an initial random population of 100 individuals
		Initialization initialization = new RandomInitialization( problem, 100);
				
		// set the destination of the initial population print out
		try {
			PrintStream filestream = new PrintStream("files/output/IUUProblemV5.txt");
			System.setOut(filestream);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		// print out the initial population
		System.out.println("Initial Population:");
		for(Solution solution : initialization.initialize()) {
			for(int i = 0; i < 72; i++) {
				System.out.print(solution.getVariable(i) + ", ");
			}
			System.out.println();
		}`

**Comment by toluboltz** [comment]
Its better you output to a file cause eclipse might chop off some of them

**Comment by Amit-1984** [comment]
@toluboltz can you please share how the initial generated population will be printed in case of any custom problem?

**Comment by toluboltz** [comment]
`// define the problem
	Problem problem = new IUUProblemV5();
			
	// create an initial random population of 100 individuals
	Initialization initialization = new RandomInitialization( problem, 100);
			
	// set the destination of the initial population print out
	try {
		PrintStream filestream = new PrintStream("files/output/IUUProblemV5.txt");
		System.setOut(filestream);
	} catch (FileNotFoundException e) {
		e.printStackTrace();
	}
	// print out the initial population
	System.out.println("Initial Population:");
	for(Solution solution : initialization.initialize()) {
		for(int i = 0; i < 72; i++) {
			System.out.print(solution.getVariable(i) + ", ");
		}
		System.out.println();
	}`

**Comment by Amit-1984** [comment]
@toluboltz  thanks for helping and sharing the idea....
I have further questions, kindly help me:-
1). the above code only stores the initial population generated. What if i want to store all the population generated in each iteration of the evolutionary algorithm say nsga-iii?
2) how to store only the non-dominated pareto-front solution to a file? or print it to the console?
Thanks

**Comment by Amit-1984** [comment]
@toluboltz  thanks for helping and sharing the idea....
I have further questions, kindly help me:-
1). the above code only stores the initial population generated. What if i want to store all the population generated in each iteration of the evolutionary algorithm say nsga-iii?
2) how to store only the non-dominated pareto-front solution to a file? or print it to the console?
Thanks

**Comment by Amit-1984** [comment]
@toluboltz  thanks for helping and sharing the idea....
I have further questions, kindly help me:-
1). the above code only stores the initial population generated. What if i want to store all the population generated in each iteration of the evolutionary algorithm say nsga-iii?
2) how to store only the non-dominated pareto-front solution to a file? or print it to the console?
Thanks
