### ISSUE TITLE
Continously save solutions of every generation

### ISSUE THREAD

**Issue by randUsr** [MOEAFramework/MOEAFramework#158]
I'm not sure yet what data I will need for analysis, but have to evolve a long running GA now.

Is there a way to save all solutions of a GA?
I'm thinking of a .csv with fields like generation, evaluation, objective1, objective2, solutionvariables.

Optimally this works with the checkpoint file, too.

I know of the ProgressListener but it seems that access to the current solution is not possible from there.
Maybe I missed something?

**Comment by dhadka** [comment]
Currently, you can only access solutions that make it into the population.  This can be done using the ProgressListener, where you get the algorithm from the ProgressEvent and access the population.

However, it sounds like you want to access all solutions generated by the GA.  There is no built-in way currently, but with some work it's possible.  For example, we could create a special Variation class that records the data or invokes a callback with each generated solution so you can log them:

```java

public class CallbackVariation implements Variation {
    private Variation nestedVariation;

    public CallbackVariation(Variation nestedVariation) {
        this.nestedVariation = nestedVariation;
    }

    public int getArity() {
        return nestedVariation.getArity();
    }

    public Solution[] evolve(Solution[] parents) {
        Solution[] offspring = nestedVariation.evolve(parents);
        // Save the offspring or invoke callback to log solutions
        return offspring;
    }
}
```

You would still need to construct the algorithm and wrap the variation operators with this class:

```java

		Problem problem = new SchafferProblem();
		
		Initialization initialization = new RandomInitialization(
				problem,
				100);

		TournamentSelection selection = new TournamentSelection(2, 
				new ChainedComparator(
						new ParetoDominanceComparator(),
						new CrowdingComparator()));

		Variation variation = new GAVariation(
				new SBX(1.0, 25.0),
				new PM(1.0 / problem.getNumberOfVariables(), 30.0));

		// Use the new callback variation to record all solutions
		variation = new CallbackVariation(variation);

		Algorithm algorithm = new NSGAII(
				problem,
				new NondominatedSortingPopulation(),
				null,
				selection,
				variation,
				initialization);

		// Make sure you delete the checkpoints file after a successful run
		algorithm = Checkpoints(algorithm,
				new File("checkpoints.txt"),
				100);
		
		while (algorithm.getNumberOfEvaluations() < 10000) {
			algorithm.step();
		}
		
		NondominatedPopulation result = algorithm.getResult();
```

**Comment by randUsr** [comment]
Thanks for this fast and amazingly detailed answer!
I might go for your proposed answer, but I'm curious how to get the algorithm object from the ProgressEvent.
From the ProgressEvent I can get the Executor, but this does not let me access the algorithm object...
What am I missing there?

**Comment by dhadka** [comment]
You're right.  I thought I saw a method to get the algorithm, but must have been looking at a different class.

**Comment by randUsr** [comment]
I ended up creating the algorithm like you suggested and log things after each `algorithm.step()`.

Thanks for your help!
