### ISSUE TITLE
Adding a jMetal algorithm

### ISSUE THREAD

**Issue by inowe** [MOEAFramework/MOEAFramework#159]
Hello, I see that the current MOEA/D implementation does not support bit string or permutation variable types. I believe jMetal's MOEA/D does, so I'm wondering if it's possible for the user to add an external jMetal algorithm to the MOEA Framework, and if it is, is there any documentation on how to do that?

Thanks

**Comment by dhadka** [comment]
I've pushed a branch that allows MOEA/D to be used with all types here: https://github.com/MOEAFramework/MOEAFramework/tree/moead_fix

You can use JMetal's MOEA/D as well, but you need to create a custom AlgorithmFactory.  Look here for the one I setup for testing: https://github.com/MOEAFramework/MOEAFramework/blob/moead_fix/test/org/moeaframework/algorithm/MOEADTest.java

**Comment by inowe** [comment]
Thank you for the swift answer, David. I'll look into both suggested solutions.
