### ISSUE TITLE
Faster truncate Implementation?!

### ISSUE THREAD

**Issue by Nozo** [MOEAFramework/MOEAFramework#16]
Is there a way to speed-up the truncate operation especially for NondominatedSortingPopulations (NSGA2 Algorithm). 
I measured the time and recognized that about 80+% in iteration is needed for the truncate operation. Do you have any advice to speed-up this method ?

**Comment by dhadka** [comment]
The truncate operation for NondominatedSortingPopulations requires non-dominated sorting the population to get the rank and crowding distance.  This is an O(MN^2) operation if I remember correctly (M = # of objectives, N = # of solutions).  As you observe, it is usually the slowest operation.

We use a very simple implementation, so it's speed probably could be improved by using a faster implementation (e.g., [[1]](http://www.soft-computing.de/ENS.pdf) or [[2]](http://www.mitpressjournals.org/doi/abs/10.1162/evco.2008.16.3.355?url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org&rfr_dat=cr_pub%3Dpubmed&#.Vjy37r-lgXg)).  You could also potentially use threads to parallelize the dominance checks, but that is a bit more involved.

**Comment by Nozo** [comment]
Maybe I should be a little bit more preciser. 
I compare the MOEA-NSGAII Implementation with an NSGAII implementation only for Integer-Problems. and the Integer-Implementation  (for a discrete Integer Problem) is way 4-5 faster then the MOEA-Version. And the factor increases by increasing the population size. I do not expect this huge distinction. Is it possible that this is caused primary of the real implementation of the selection process? Or is there a way to speed up especially for discrete integer problems for all algorithms?

**Comment by dhadka** [comment]
Thanks for the response.  I'd like to investigate this further to see if the speed can be improved.  Could you please clarify which implementations you are using?  Is the other NSGAII implementation from a different library?  If so, which one?  Thanks in advance!

**Comment by Nozo** [comment]
I think you can close this issue....
I found an error in the measurement evaluation.
Sorry for the wrong informations

**Comment by dhadka** [comment]
Closing.  Please reopen if you spot any other issues.
