### ISSUE TITLE
Using custom types and operators 

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#164]
Hi @dhadka, 

I am reading chapter 5 of the **beginner's guide**, particularly section 5.6 where it discusses the creation of custom decision variables. These conditions are given as the basis for creating and using new operators;
1. Data cannot be represented by a composite of built-in types
2. Provide better structure (grouping) of variables
3. Define custom variation operators

 I am trying to find a solution to a transit network design problem which involves finding a set of network routes and their frequencies that best meet stated objectives. The representation of the variable is complex; Each gene(route) is a list of nodes in the network's graph. The genes have frequency variable which is a tuple of two doubles representing the morning and afternoon peak demand frequencies on the route. A single individual in the population is, therefore, a List of ArrayLists. The ArrayList holds the route list and frequency tuple. 

**Questions**
1) The Color example in section 5.6 shows how to implement a **mutation variator** the question is why is mutation alone used in the example and not together with the crossover? also,  can you please show me how a custom crossover operator can be implemented so that I can adapt it to my problem.  

2) The evaluation of the population in MOEA is done twice right? once when the parents are initialized and after the offspring are created? Assume I use a custom evaluation method, does MOEA implicitly calls the evaluation method after offspring are created, or does the evaluation have to be called explicitly in my code.

Thanks

**Comment by dhadka** [comment]
Are there any constraints on routes, such as a route must visit every node exactly once?

1. Crossover is implemented in an almost identical way to mutations.  Both mutation and crossover implement the Variation interface.  For crossover, `getArity()` should return 2 (or a larger value if it requires more than 2 parents).  The `evolve` method will typically look like:

    ```java

	@Override
	public Solution[] evolve(Solution[] parents) {
		Solution result1 = parents[0].copy();
		Solution result2 = parents[1].copy();

		for (int i = 0; i < result1.getNumberOfVariables(); i++) {
			Variable variable1 = result1.getVariable(i);
			Variable variable2 = result2.getVariable(i);

			if ((PRNG.nextDouble() <= probability)
					&& (variable1 instanceof Permutation)
					&& (variable2 instanceof Permutation)) {
				applyCrossover((Permutation)variable1, (Permutation)variable2);
			}
		}

		return new Solution[] { result1, result2 };
	}
    ```

    This essentially scans each variable, checks to see if both are the appropriate type (e.g., Permutation in the example above), and calls `applyCrossover(...)` with some probability.

    Inside applyCrossover you would modify the two variables as required.  In this example, you can just modify the variables directly since we are referencing the variables in `result1` and `result2`, which are copies of the parents.  Check out https://github.com/MOEAFramework/MOEAFramework/tree/master/src/org/moeaframework/core/operator for some examples.

2. Each solution is evaluated once.  The solutions in the initial population will be evaluated once, and each offspring will be evaluated once.  The Algorithm implementation (e.g., NSGAII) is responsible for evaluating the solutions, so you do not need to explicitly evaluate the solutions.

**Comment by Nobik2** [comment]
Thanks for raising the issue of constraints because it is important to understand how those can be used in this problem. The constraints on the route are the route length and total demand a route can serve while the frequency is constrained to not exceed the maximum number of vehicle trips on the route (these are obtained externally from a simulation). How can the constraints be applied?
