### ISSUE TITLE
Help regarding mutation and crossover operation in NSGA-II

### ISSUE THREAD

**Issue by Amit-1984** [MOEAFramework/MOEAFramework#166]
A Great Greeting to all first....
i have designed a custom moea problem and want to use NSGA-II to solve that. while applying the algorithm, the end results are not fruitful to me. i have use the default values for NSGA-II and only provided the custom problem to it. Now, i want to examine and want to define my own crossover and mutation operations in order to adapt the NSGA-II algorithm to my custom problem. Kindly help me in this direction and where and how i can do this, if my idea is feasible?

**Comment by dhadka** [comment]
Probably the best place to start is to look at the existing crossover and mutation operators for your encoding: https://github.com/MOEAFramework/MOEAFramework/tree/master/src/org/moeaframework/core/operator

Once you're ready to create your own operator, either by modifying an existing one or creating a new crossover/mutation operator from scratch, define them in new files, e.g., `MyCrossover.java`, `MyMutation.java`.

Then, you need to register the new operators with the framework.  To do this, you would place something similar to the following before you create/run the algorithm.  

```java

OperatorFactory.getInstance().addProvider(new OperatorProvider() {
    public String getMutationHint(Problem problem) {
        return null;
    }

    public String getVariationHint(Problem problem) {
        return null;
    }

    public Variation getVariation(String name, Properties properties, Problem problem) {
        TypedProperties typedProperties = new TypedProperties(properties);

        if (name.equalsIgnoreCase("MyCrossover")) {
            return new MyCrossover(
                typedProperties.getDouble("MyCrossover.Rate", 1.0));
        } else if (name.equalsIgnoreCase("MyMutation")) {
            return new MyMutation(
                typedProperties.getDouble("MyMutation.Rate", 0.1));
        }

        // No match, return null
        return null;
    }
});
```

Then, when you create and run your algorithm, you can specify the operator:

```java

new Executor()
    .withProblem(...)
    .withAlgorithm("NSGAII")
    .withProperty("operator", "MyCrossover+MyMutation")
    .withProperty("MyCrossover.Rate", 0.9)
    .withProperty("MyMutation.Rate", 0.25)
    .withMaxEvaluations(10000)
    .run()
```

As can be seen, the names provided to `withProperty(...)` match the strings used in `getVariation(...)` above.

The only part that may not be clear is the + in the operator property: `"MyCrossover+MyMutation"`.  This simply says: First apply MyCrossover to the parents.  Then apply MyMutation to each offspring.

Hope this all makes sense!  Feel free to ask questions if it doesn't.

**Comment by PickHub** [comment]
Is it possible to register a new operator that is written in Scala?

**Comment by dhadka** [comment]
@PickHub I'm not very familiar with Scala, but as long as you can implement the Variation interface you should be able to create and register the operator.

**Comment by PickHub** [comment]
How come that in the above example both _MyCrossover_ and _MyMutation_ result in a call of the same construct with different values?

For example if I'd try to implement my own version of PCX, how would that call look like?

`public PCX(int numberOfParents, int numberOfOffspring) `

**Comment by Amit-1984** [comment]
@dhadka  thanks for suggesting about custom mutation and crossover operators. I tried to create MyCrossover file but still i am facing problem regarding implementing MyMutation file. I am having the following points:-
1. MyMutation file is implemented by which interface class?
2. Which method is necessary to override? (e.g. evolve() in case of MyCrossover file).
3. Any example of custom mutation created file that can be judged and modified as per requirements.
Thanks....

**Comment by dhadka** [comment]
1. The `Variation` interface; it is used for both mutation and crossover.
2. The `evolve()` method.  In this case, the array will contain a single solution.
3. See the [UM](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/core/operator/real/UM.java) operator as an example.
