### ISSUE TITLE
Introducing an intermediate step while evaluating offspring with NSGA-II

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#175]
Hello @dhadka 

**Context**
In my problem, I am then using an external simulation  as the evaluation module for the problem within MOEA, hence, the simulation is being called within the evaluate method of the problem class, then the objectives are set to the outcome of the simulation (you helped me with some clarification of that in the past). The individuals in the problem are transit networks in xml format which is the format the simulation accepts to evaluate the networks. Each network.xml comprises of routes and schedules. In MOEAFramework, from a given number of network.xml files I want to get a Pareto front using the NSGA-II algorithm. I opt for a JSON decision variable representation of the network.xml file because it will allow me to easily apply variation operator on each network in one piece and write the pareto set back as xml files, that can then be used for further analysis in the simulation.

**The twist** 
The parent population are JSON equivalents of the initial network.xml files, so to evaluate the parents I  simulate their corresponding xml. But the children JSON objects, do not yet have any corresponding xml format, Therefore, to evaluate them I need to convert them back to their corresponding XML, before the simulation can evaluate them. 

**My question**
Since NSGA-II evaluates the initial population once and the offspring once, how can I keep track of the offspring, so that I can inform MOEAframework to convert them before it starts evaluating with the simulation? Essentially in which method within the framework can I write code for this and what can such code look like.

Thank you

**Comment by dhadka** [comment]
If I'm understanding your setup correctly, I would set this up in the `evaluate` method as follows:

```
public void evaluate(Solution solution) {
    // 1. Read the JSON from the decision variable

    // 2. Create a temp file and write the network XML
    File file = File.createTempFile("input", ".xml");
    ...write XML to file...

    // 3. Run your simulation with this file as input
    String filename = file.getAbsolutePath();
    ...run your simulation and pass in this filename...

    // 4. Read the outputs and store the objectives back 

    // 5. Cleanup the temp file
    file.delete();
}
```
