### ISSUE TITLE
NGSA-II result always returns only 1 solution in the NonDominatedPopulation

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#176]
Hi @dhadka,

NSGA-II runs but even when I set the population size property, I notice that the results(Pareto set) only contains 1 solution i.e. (`results.size() == 1`) I have tried running different population sizes and still get the same outcome. Also, I have two objectives and I notice that the values of the objectives when printed are `0.0000` and `0.0000`. Please what am I doing wrong?
 
```java
    public Solution newSolution() {
    	Solution solution = new Solution(1, 2);
        solution.setVariable(0, new TransitScheduleJSONDecisionVariable());
        return solution;
    }
```

```java
	public void evaluate(Solution solution) {
  
    	System.out.println(callsToEvaluate++);
    	TransitScheduleJSONDecisionVariable var = (TransitScheduleJSONDecisionVariable) solution.getVariable(0);
        System.out.println("Number of MOEA Evaluations is:" + " " + currentMOEAEvaluationNumber++);
        JSONObject Jvar = var.getTransitSchedule();
        TransitScheduleXMLFileUtils.getXMLFromJSONDecisionVar(Jvar);

        runSimulation(Simulation inputs);
		Objectives objectives = processOutputFiles(Simulation results);
		solution.setObjective(0, objectives.objectives[0]);
                solution.setObjective(1, objectives.objectives[1]);
        
    }
```

```java
public class TransitScheduleJSONDecisionVariable implements Variable {

    private static final long serialVersionUID = 1L;
    private JSONObject transitSchedule; // transitSchedule.xml file's json representation

    public TransitScheduleJSONDecisionVariable() {
    	super();
    }
    public TransitScheduleJSONDecisionVariable(JSONObject transitSchedule) {
		this();
		this.transitSchedule = transitSchedule;
    }

    public Variable copy() {
        TransitScheduleJSONDecisionVariable v = new TransitScheduleJSONDecisionVariable();
        v.setTransitSchedule(new JSONObject(this.getTransitSchedule().toString()));
        return v;
    }

    public void randomize() {
    	
        transitSchedule = TransitScheduleXMLFileUtils.getRandomTransitSchedule();	
        
    }

    public JSONObject getTransitSchedule() {
        return transitSchedule;
    }

    public void setTransitSchedule(JSONObject transitSchedule) {
        this.transitSchedule = transitSchedule;
    }
}
```

**Comment by dhadka** [comment]
The code looks fine.  I would suggest adding some sanity checks or print statements to make sure it's reading the objectives correctly in `processOutputFiles`.  If the objectives it's reading are always 0.0, then having only one solution in the result makes sense since the result is a NondominatedPopulation (which by default removes solutions with duplicate objective values).

**Comment by Nobik2** [comment]
@dhadka 
This is a print out I get after running with a pop size of 25. The simulation gives results its only strange that the algorithm cannot pick them up

```java
Total time objective: 48.22                // objective 1
Second objective: 2488301.1410     // objective 2
Size of Pareto front is: 1
Evaluate called 25 times...
System.out.format("%.4f      %.4f%n", solution.getObjective(0), solution.getObjective(1));  //0.0000      0.0000
```

**Comment by dhadka** [comment]
Interesting.  Can you please confirm that `objectives.objective[0]` and `objectives.objective[1]` have the expected values inside `evaluate`?

Would you be able to share your code with me so I can investigate further?  If you don't want to share it here publicly, you can e-mail it to admin@moeaframework.org.

Thanks!

**Comment by Nobik2** [comment]
Yes, I prefer emailing it, I will get it to you in about 2 hours. Thanks a lot for your time!
