### ISSUE TITLE
Repetitive file reading in Abstract Problem

### ISSUE THREAD

**Issue by bolatmerve** [MOEAFramework/MOEAFramework#178]
Hi everyone,

I have constructed a bi-objective model by extending Abstract Problem. I have to import data from a .txt file in order to define objective function. At first, I scanned the data in evaluate() but then I realized that at each iteration, .txt file was re-read which consumes a lot of time. Then I tried to scan the .txt file at another class and call it in the evaluate() part but it did not solve my problem. In the Knapsack example, there is a load() function which enables to load the instances. So, is there a way to import instances once for a customized problem which extends Abstract Problem class? 

Thanks in advance,

**Comment by dhadka** [comment]
Yes, put the code to load the data in the constructor.

```java

public class MyProblem extends AbstractProblem {

    public MyProblem() {
        super(nvars, nobjs, nconstrs);

        // Put your code here to load the data.
    }

}
```

**Comment by bolatmerve** [comment]
Thank you very much for your quick response, it works!

Have a nice day,
