### ISSUE TITLE
Parallelizing the MOEAframework

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#189]
Hi @dhadka,

Regarding parallelizing the MOEAframework, is the user only required to specify the .distributeOnAllCores() or .distributeOn() properties or are there other things one needs to look out for? I guess my main question is about how MOEA handles the evaluation function in the optimization. Does it just run a new instance of the function (in my case a simulation model) on each core where the problem is distributed on the parallel computer? or are there other intrigues involved?

E.g. If I specify `.runSeeds(10)` and `.distributeOn(10)` for my problem, I assume this means that each core will handle a seeded run and in that case, the evaluation is called once on each of the cores? Please shed more light on this for me.

Best Regards

**Comment by dhadka** [comment]
Parallelization here applies to the function evaluations.  Each seed is run serially.  This assumes that the function evaluation is re-entrant, meaning it can be called multiple times by different threads without causing any issues.
