### ISSUE TITLE
Parallelizing algorithm runs vs evaluation function

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#190]
Hi @dhadka 

I have gone through an older issue #127 in which you had a conversation with @fstonedahl regarding; _runSeeds, random seeds, and multi-threaded reproducibility_. The crux of the discussion was essentially about achieving **reproducible** results when parallelizing algorithm runs rather than the evaluation function in situations where the evaluation is a stochastic simulation . This lead to the `distributedProblem Class ` as a contribution from @fstonedahl. I have a similar situation where I want to paralellize the algorithm runs. 

**Questions**
1) Does the code snippet below demonstrate how I can parallelize the runs? if not, can you please  demonstrate by the way of a code snippet how I can use the `distributedProblem Class ` to get reproducible results. 
2) Does calling the function iteratively a given number of times have the same effect of doing multiple seeded runs?

```java
	private double getResultFromStochasticRun(int numThreads) {
		PRNG.setSeed(....); // set seed
		NondominatedPopulation result = new Executor()
				.withAlgorithm("NSGA-II")
				.withProblem(new SimulationBasedTransitOptimizationProblem())
				.withProperty("populationSize", 10)
				.withMaxEvaluations(1000)
				.distributeOn(numThreads)
				.run();
		return result; 
```
Regards

**Comment by dhadka** [comment]
1. Yes, when you call this function, it will parallelize one run by distributing the function evaluations across multiple cores.

2. Yes, this is pretty much what runSeeds does (https://github.com/MOEAFramework/MOEAFramework/blob/41b4a77076bfe83820ffb20598cb8f474e72e250/src/org/moeaframework/Executor.java#L705).

**Comment by Nobik2** [comment]
Thanks very much @dhadka. So is there a  way to get the seeds used in the runSeeds(....) method, or is the only way by using PRNG.setSeed() with run() which only works for single seed scenarios?

**Comment by dhadka** [comment]
If you want to use a specific seed for each run, the only way is to use PRNG.setSeeds with run().

runSeeds(...) doesn't actually set any specific seeds, it just executes N runs with the current state of the random number generator.

**Comment by Nobik2** [comment]
This is clear, thank you!
