### ISSUE TITLE
SMS-EMOA report hypervolume 0

### ISSUE THREAD

**Issue by YaliWang15** [MOEAFramework/MOEAFramework#193]
Hello,

When I run the following code, I always get wrong hypervolume for SMS-EMOA, is this a bug?

String problem = "dtlz1_3";
String[] algorithms = { "HSMS1E", "hsms", "NSGA2", "NSGA3", "SMS-EMOA", "MOEAD"};
//"HSMS1E", "hsms" are my own algorithms.
Executor executor =new Executor()
				.withProblem(problem
				.withMaxEvaluations(100000)
				.distributeOnAllCores();

Analyzer analyzer = new Analyzer()
				.withProblem(problem)
				.includeHypervolume()
				.includeInvertedGenerationalDistance()
				.showStatisticalSignificance()
				.showAll();

for (String algorithm : algorithms) {
			System.out.println(algorithm);
			for (int j = 0; j < 10; j++) {
				String alg= new String(algorithm);
				long startTime=System.currentTimeMillis();
				PRNG.setSeed(j+1);
				System.out.println(j+1);
                analyzer.add(alg, executor.withAlgorithm(algorithm).run());
               
    			long endTime=System.currentTimeMillis();
    			System.out.println("running time:" + (endTime-startTime)+"ms");
                         }
}
		analyzer.printAnalysis();

the result is:
SMS-EMOA:
    Hypervolume: 
        Aggregate: 0.0
        Min: 0.0
        Median: 0.0
        Max: 0.0
        Count: 10
        Indifferent: []
        Values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    InvertedGenerationalDistance: 
        Aggregate: 0.9047874693928144
        Min: 0.9047874693928144
        Median: 3.7752888472898833
        Max: 9.88806790622756
        Count: 10
        Indifferent: []
        Values: [9.287910129041936, 1.5169250910403136, 4.303880130977711, 3.2466975636020563, 9.88806790622756, 6.886913047202555, 1.6876463077502584, 5.540069919260596, 0.9047874693928144, 2.7051767429850915]
NSGA2:
    Hypervolume: 
        Aggregate: 0.8060467411
        Min: 0.7358960755
        Median: 0.7499248114
        Max: 0.7588220438
        Count: 10
        Indifferent: []
        Values: [0.7519842455, 0.7525871549, 0.7588220438, 0.7553166052, 0.7490817397, 0.74556232, 0.7507678831, 0.7470848406, 0.7358960755, 0.7482477181]
    InvertedGenerationalDistance: 
        Aggregate: 0.021488537075627073
        Min: 0.05943583781391191
        Median: 0.06826214241121792
        Max: 0.08260154433969157
        Count: 10
        Indifferent: []
        Values: [0.06785203335600898, 0.06506522510147106, 0.05943583781391191, 0.06375945845412595, 0.06867225146642686, 0.07348307038336657, 0.07119991299386479, 0.06612989490067102, 0.08260154433969157, 0.07156095978831506]

Thank you very much!

Best regards,
Yali

**Comment by WendiWang** [comment]
Hello,

I found that it only happened when NSGA3 and SMS-EMOA run together,
String[] algorithms = { "NSGA3", "SMS-EMOA"};
you can also reduce maxevaluation:
.withMaxEvaluations(20000)

Sms-emoa still got 0 hypervolume:
SMS-EMOA:
    Hypervolume: 
        Aggregate: 0.0
        Min: 0.0
        Median: 0.0
        Max: 0.0
        Count: 2
        Indifferent: [NSGA3]
        Values: [0.0, 0.0]
    InvertedGenerationalDistance: 
        Aggregate: 17.54984913134499
        Min: 17.54984913134499
        Median: 30.833979534644158
        Max: 44.11810993794333
        Count: 2
        Indifferent: [NSGA3]
        Values: [44.11810993794333, 17.54984913134499]
NSGA3:
    Hypervolume: 
        Aggregate: 0.7650974649495849
        Min: 0.7350254433919021
        Median: 0.7354716904469649
        Max: 0.7359179375020276
        Count: 2
        Indifferent: [SMS-EMOA]
        Values: [0.7359179375020276, 0.7350254433919021]
    InvertedGenerationalDistance: 
        Aggregate: 0.04931617699624688
        Min: 0.07084647201907834
        Median: 0.07359979805270278
        Max: 0.07635312408632723
        Count: 2
        Indifferent: [SMS-EMOA]
        Values: [0.07635312408632723, 0.07084647201907834]

Thanks a lot and looking forward to your response.

**Comment by dhadka** [comment]
Thanks for reporting this.  Taking a look.

**Comment by dhadka** [comment]
I'm getting non-zero values for SMS-EMOA's hypervolume when running this example (some values are 0.0, but at least half are non-zero).  If you are not using the latest version, I would first suggest updating to the latest version of the MOEA Framework.

You can also look at setting a different Reference Point for the hypervolume calculation.  By default, the reference point is based on the bounds of the reference set.  However, there are settings in `global.properties` that let you change this behavior.

For example, if you set:

    org.moeaframework.core.indicator.hypervolume_delta = 0.5

to make the reference point offset a relative amount from the bounds of the reference set.  Or you can explicitly provide the reference point for a problem:

    # Use the reference point (2, 2, ..., 2) for DTLZ1
    org.moeaframework.core.indicator.hypervolume_refpt.DTLZ1 = 2

See the comments in `global.properties` for a description of these options.

**Comment by WendiWang** [comment]
Thank you very much.

I am now sure that this is a problem, because it happened when I put "NSGA3" before "SMS-EMOA", like String[] algorithms = { "NSGA3", "SMS-EMOA"}. 
and it doesn't happen when I put  "SMS-EMOA" before "NSGA3".

When I use
String[] algorithms = {"SMS-EMOA",  "NSGA3"}.  all results are normal.

btw: I am using moea framework 2.12.

in the case of String[] algorithms = { "NSGA3", "SMS-EMOA"}, you can run only once for each algorithm to find the problem, on line 824 in Executor.java, after running SMS-EMOA, you can find that all the solutions of algorithm (sms-emoa) are not normal:
result.addAll(algorithm.getResult());

I am using MOEA framework under ubuntu.

**Comment by WendiWang** [comment]
Thank you again, I replied through website, I hope you can reproduce the
problem.

**Comment by WendiWang** [comment]
hello,

Can you reproduce the problem? It looks almost obviously a bug. Thank you
very much.

Best regards,
Yali
