### ISSUE TITLE
No provider for NSGAII, caused by "unable to find suitable variation operator"

### ISSUE THREAD

**Issue by hernan91** [MOEAFramework/MOEAFramework#196]
I'm new at MOEA and created an AbstractProblem to solve a Wireless Sensor Network Layout Design problem. For the moment my idea is to consider only one objetive, until i solve the error below.
It says that there is no Provider, like the issue in  #183. The solution (as suggested in the issue's post) is creating a provider. I created it and the error remains being the same. What calls my atention is that the exception thrown acuses that the problem is caused by the incapacitity of find a "suitable variation operator".

**The error:**

`Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for NSGAII
	at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:331)
	at org.moeaframework.core.spi.AlgorithmFactory.instantiateAlgorithm(AlgorithmFactory.java:175)
	at org.moeaframework.core.spi.AlgorithmFactory.getAlgorithm(AlgorithmFactory.java:137)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:785)
	at org.moeaframework.Executor.runSeeds(Executor.java:722)
	at main.main(main.java:22)
Caused by: org.moeaframework.core.spi.ProviderLookupException: unable to find suitable variation operator
	at org.moeaframework.core.spi.OperatorFactory.lookupVariationHint(OperatorFactory.java:347)
	at org.moeaframework.core.spi.OperatorFactory.getVariation(OperatorFactory.java:182)
	at org.moeaframework.core.spi.OperatorFactory.getVariation(OperatorFactory.java:160)
	at org.moeaframework.algorithm.StandardAlgorithms.newNSGAII(StandardAlgorithms.java:415)
	at org.moeaframework.algorithm.StandardAlgorithms.getAlgorithm(StandardAlgorithms.java:271)
	... 5 more
`
**The code:** 

```
import java.util.List;

import org.moeaframework.Executor;
import org.moeaframework.core.NondominatedPopulation;
import org.moeaframework.core.Solution;
import org.moeaframework.core.spi.ProblemFactory;

public class main {

	public static void main(String[] args) {
		ProblemFactory.getInstance().addProvider(new MyProblemProvider());
		Executor executor = new Executor();
		SensorsFieldData sensorsFieldData = new SensorsFieldData(5, 60, 60);
		executor.withProblemClass(SensorsProblem.class, 40, 1, sensorsFieldData);
		//executor.withProblem("UF1");
		executor.withAlgorithm("NSGAII");
		executor.withMaxEvaluations(100);
		executor.withProperty("populationSize", 20);

		executor.distributeOnAllCores();
		List<NondominatedPopulation> resultPopulation = executor.runSeeds(10);
		for (int i = 0; i < resultPopulation.get(0).size(); i++) {
			Solution solution = resultPopulation.get(0).get(i);
			System.out.println(solution.getObjective(0));
		}
	}
}```

```
import org.moeaframework.core.NondominatedPopulation;
import org.moeaframework.core.Problem;
import org.moeaframework.core.spi.ProblemProvider;

public class MyProblemProvider extends ProblemProvider {
    public Problem getProblem(String name) {
        if (name.equalsIgnoreCase("SensorsProblem")) {
        	SensorsFieldData sensorsFieldData = new SensorsFieldData(5, 60, 60);
            return new SensorsProblem(40, 1, sensorsFieldData);
        } else {
            return null;
        }
    }

    public NondominatedPopulation getReferenceSet(String name) {
        if (name.equalsIgnoreCase("SensorsProblem")) {
            // If you don't have a reference set, return null.  But some functionality will be disabled.
            return new NondominatedPopulation();
        } else {
            return null;
        }
    }
}
```

```import org.moeaframework.core.Solution;
import org.moeaframework.core.variable.EncodingUtils;
import org.moeaframework.problem.AbstractProblem;
import java.util.ArrayList;

public class SensorsProblem extends AbstractProblem{
	private SensorsFieldData sensorsFieldData;
	private int alleleLength;
	
	public SensorsProblem(int alleleLength, int numberOfObjectives, SensorsFieldData sfData) {
		super((alleleLength*2)+1, numberOfObjectives);	
		this.alleleLength = alleleLength;
		this.sensorsFieldData = sfData;
	}
	
	public SensorsProblem() {
		super(51, 1);
		this.alleleLength = 25;
		this.sensorsFieldData = new SensorsFieldData(5, 60, 60);
	}

	public Solution newSolution() {
		Solution solution = new Solution(numberOfVariables, numberOfObjectives);
		solution.setVariable(0, EncodingUtils.newBinary(alleleLength));
		for(int i=1; i<=alleleLength*2; i=i+2) {
			solution.setVariable(i, EncodingUtils.newInt(0, sensorsFieldData.getGridSizeX()));
			solution.setVariable(i+1, EncodingUtils.newInt(0, sensorsFieldData.getGridSizeY()));
		}
		return solution;
	}
	
	@Override
	public void evaluate(Solution solution) {
		ArrayList<Location> sensorsLocations = generateArray(solution);
		ObjectiveFunction objFunc = new ObjectiveFunction(sensorsFieldData, 2);
		double f1 = objFunc.getFitness(sensorsLocations);
		solution.setObjective(0, f1);
	}
	
	public ArrayList<Location> generateArray(Solution solution){
		boolean status[] = EncodingUtils.getBinary(solution.getVariable(0));
		ArrayList<Location> sensorsLocations = new ArrayList<>();
		for(int i=1; i<=alleleLength*2; i=i+2) {
			if(status[i/2]) {
				int xLoc = EncodingUtils.getInt(solution.getVariable(i));
				int yLoc = EncodingUtils.getInt(solution.getVariable(i+1));
				Location loc = new Location(xLoc, yLoc);
				sensorsLocations.set(i, loc);
			}
			else {
				sensorsLocations.set(i, null);
			}
		}
		return sensorsLocations;
	}
}
```
Thanks in advance.

**Comment by dhadka** [comment]
The underlying issue is using two different types (binary and int) in the solution.  The code doesn't know how to combine the operators of different types and throws the exception (of course, this could use a better error message so it's more clear what's wrong).  There are two solutions:

1. Explicitly tell it what operators to use, for example: `executor.withProperty("operator", "sbx+hux+pm+bf");`.  This essentially combines the binary and int 

2. Use a single type.  Here, it would be easiest to use a binary int.  Change `EncodingUtils.newInt` to `EncodingUtils.newBinaryInt`.
