### ISSUE TITLE
Save algorithm populations and quality indicators in every generation

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#199]
hi @dhadka,

 Kindly give me your opinion about saving the solutions and their indicators. 

I have looked at issues #158, #126, #51, #160 to get an understanding of how to deal with this subject, but they have only talk about saving populations in each generation. In #73 you said that _"The instrumenter only reports the data from the last run"_.

I observed that when a run of my problem terminates unexpectedly, and I restart it from the last saved state of the checkpoint file, the indicators for those previous runs are never retrieved. The indicators that I get at the end are only for those that commenced from the last checkpoint restart.

**Questions**
1) Is it then possible to calculate and save the indicators in every generation, without having to wait till the end of the last evaluation or is there a mechanism to save them internally as the algorithm evaluations progress.

2) If the above in question 1 is possible, how can they be subsequently retrieved later? 

Thank you for all your assistance.

**Comment by dhadka** [comment]
Yes, you're right that if the problem terminates unexpectedly and you restart from the last saved checkpoint, it does not pick up any data from the previous run.  This is because the checkpoint only saves the current state of the algorithm.  No history is recorded.

(1) can be accomplished by running the algorithm directly, for example:

```java

		Problem problem = ProblemFactory.getInstance().getProblem("DTLZ2_2");
		Algorithm algorithm = AlgorithmFactory.getInstance().getAlgorithm("NSGAII", new Properties(), problem);
		
		NondominatedPopulation referenceSet = new NondominatedPopulation(PopulationIO.readObjectives(new File("./pf/DTLZ2.2D.pf")));
		QualityIndicator qi = new QualityIndicator(problem, referenceSet);
		
		while (algorithm.getNumberOfEvaluations() < 10000) {
			algorithm.step();
			qi.calculate(algorithm.getResult());
			
			System.out.println(algorithm.getNumberOfEvaluations() + " "
					+ qi.getGenerationalDistance() + " "
					+ qi.getHypervolume());
		}
```

The following extends the above example with checkpoints.  The output is appended to a file.

```java

		Problem problem = ProblemFactory.getInstance().getProblem("DTLZ2_2");
		Algorithm algorithm = AlgorithmFactory.getInstance().getAlgorithm("NSGAII", new Properties(), problem);
		
		NondominatedPopulation referenceSet = new NondominatedPopulation(PopulationIO.readObjectives(new File("./pf/DTLZ2.2D.pf")));
		QualityIndicator qi = new QualityIndicator(problem, referenceSet);
		
		File checkpointFile = new File("checkpoint.dat");
		File outputFile = new File("output.txt");
		
		if (checkpointFile.exists()) {
			System.out.println("Using checkpoint file!");
		}
		
		Checkpoints checkpoint = new Checkpoints(algorithm, checkpointFile, 100);
		
		try (FileWriter writer = new FileWriter(outputFile, true)) {
			while (checkpoint.getNumberOfEvaluations() < 10000) {
				checkpoint.step();
				qi.calculate(checkpoint.getResult());
				
				writer.write(checkpoint.getNumberOfEvaluations() + " "
						+ qi.getGenerationalDistance() + " "
						+ qi.getHypervolume()
						+ System.lineSeparator());
			}
		}
	
		System.out.println("Finished!");
```

**Comment by Nobik2** [comment]
@dhadka,

Thanks so much for your reply, one question; will this work for a custom problem without a predefined reference set, how can the solution be modified to that effect?
