### ISSUE TITLE
Island-Model Parallelization Example IllegalArgumentException

### ISSUE THREAD

**Issue by Nozo** [MOEAFramework/MOEAFramework#2]
I try to use the island model parallelization code example of the MOEA Framework documentation v2.5 chapter 10.2. With the orignal code form the document sometimes a IllegalArgumentException is thrown from one of the created threads. 
Do you have any idear whats the problem in this example?

Exception in thread "Thread-3" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(Unknown Source)
	at java.util.TimSort.mergeAt(Unknown Source)
	at java.util.TimSort.mergeCollapse(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at org.moeaframework.core.Population.sort(Population.java:273)
	at org.moeaframework.core.NondominatedSortingPopulation.sort(NondominatedSortingPopulation.java:151)
	at org.moeaframework.core.Population.truncate(Population.java:285)
	at org.moeaframework.core.NondominatedSortingPopulation.truncate(NondominatedSortingPopulation.java:160)
	at org.moeaframework.core.NondominatedSortingPopulation.truncate(NondominatedSortingPopulation.java:170)
	at org.moeaframework.algorithm.NSGAII.iterate(NSGAII.java:97)
	at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:161)
	at org.moeaframework.algorithm.PeriodicAction.step(PeriodicAction.java:108)
	at AlgThread.run(AlgThread.java:15)

**Comment by dhadka** [comment]
Hi,

Sorry you're running into this issue.  I'm unable to reproduce this on Windows.  To help recreate the issue, can you please indicate:

1. Your operating system and version (e.g., Windows 8, Ubuntu 14.04).

2. Your version of Java (run `java -version`)

Thanks!

**Comment by Nozo** [comment]
Hi dhadka, 

I use Windows 7  and the Java version 7 with update 79. 
the exception is only  thrown from time to time and the code finishes his job but for later development based on your example it is important for me to fix this issue. 

Tanks for your time!

**Comment by dhadka** [comment]
Thanks, I was finally able to recreate the issue.  Will be working on a solution.

**Comment by dhadka** [comment]
It looks like this is caused by Java's switch from MergeSort to TimSort.  Until I have a more permanent solution, you can temporarily tell Java to use the old MergeSort.  See https://gist.github.com/dhadka/559be932acc55b1ada6b

**Comment by Nozo** [comment]
Thanks for your fast reply and the solution!

**Comment by dhadka** [comment]
Hi, after some further testing, it looks like the root cause was due to not creating a copy of the migrating solutions (which was an error in the example from the manual).

    newIsland.add(oldIsland.get(emigrant).copy());

I've updated https://gist.github.com/dhadka/559be932acc55b1ada6b to reflect this change and the example as it appears in the manual.

Thanks for bringing this to my attention!

**Comment by Nozo** [comment]
Another remark for the island parallelization example with the NSGAII:

to keep consistency with the original paper of NSGAII, the population size should be consistently. 
Therefore it may be useful to add a sorting for the solutions in the population and remove 1 for the new migration solution. Then the found solutions are always the population size otherwise the migration solution is just attached and the population size increases with time. It is only a remark becouse I was first confused about the increasing population size with time. 

For example:
.........
Comparator<Solution> Comparator = new NondominatedSortingComparator();
.........
for (Thread otherThread : islands.keySet()) {
       if (otherThread != thisThread) {
             Population oldIsland = (Population)islands.get(thisThread).getPopulation();
             Population newIsland = (Population)islands.get(otherThread).getPopulation();
		    synchronized (oldIsland) {
			      synchronized (newIsland) {
			           int emigrant = PRNG.nextInt(oldIsland.size());//Random Choose of the emigrant
				   if(!newIsland.add(oldIsland.get(emigrant).copy())){
					      System.out.println("migration failed");
				    }
				   newIsland.sort(Comparator);
				   newIsland.remove(0);
                             }
                    }
          }
}
...............
........

**Comment by dhadka** [comment]
Yes, I noticed that too.  I'll update the example.  One note: the solution at index 0 is the best solution, so you likely want to remove a solution from the other end of the list:

~~~~~~
newIsland.sort(Comparator)
newIsland.remove(newIsland.size()-1)
~~~~~~

A somewhat simpler way is to use the truncate method, which will automatically non-dominated sort the population and remove the worst solution:

~~~~~~
newIsland.truncate(newIsland.size()-1);
~~~~~~
