### ISSUE TITLE
Only one solution left on population after executing runSeeds()

### ISSUE THREAD

**Issue by hernan91** [MOEAFramework/MOEAFramework#206]
I'm new at MOEA and i have some difficulties with a custom problem called SensorsProblem i implemented using NSGAII and some operators. 
The issue is that for each seed's population, i get only one solution as result. (NonDominatedPopulation)
I know there's lack of information on my question, but i hoped perhaps someone with experience at MOEA suspect what things can be wrong or need to be checked.
By the way, the population i set is over 100 solutions at start, already checked that.

Thanks! Let me know if you need more infomation to answer.

**Comment by dhadka** [comment]
The usual culprit for seeing only one solution in the NondominatedPopulation is having infeasible solutions.  Per the non-dominance rules, if two solutions violate constraints, we pick the one with the smallest constraint violation.  However, if all of your solutions violate constraints, then there will only be one "best" solution, the one with the smallest constraint violation.  Please check solution.violatesConstraints() or look at the individual constraints to see if any are non-zero.
