### ISSUE TITLE
Is it possible to extend the Solution class?

### ISSUE THREAD

**Issue by hernan91** [MOEAFramework/MOEAFramework#212]
I'm getting an error saying that "org.moeaframework.core.Solution cannot be cast to SensorsSolution".
SensorsSolution is a class that extends Solution. **Does MOEA allow this? It's a recomended practice?**

The reason i'm extending it, is because i need each individual to store information about sensors locations.
After evaluating the use of the attribute's HashMap of this class i realized that when running on multiple threads (using .distributeOnAllCores() method) it's data erases after each evaluation cause it's casted to Future Solution. 

Thanks.

**Comment by dhadka** [comment]
Have you overridden the copy() and deepCopy() methods?

**Comment by whhxp** [comment]
I think you can use "attribute" to store data, see #149. I believe the code is not in 2.12, so you need to clone the latest version.

**Comment by dhadka** [comment]
Removed my previous comment as it doesn't solve the issue for FutureSolution.  whhxp's answer will help in the near term as it'll copy the attributes from FutureSolution.

I think longer term it would make sense to redesign FutureSolution.  Currently, when you convert a Solution to a FutureSolution, it internally copies the variables, objectives, constraints, etc. to the FutureSolution.  If it instead kept a reference to the original solution, the original solution could be any type.

**Comment by hernan91** [comment]
First of all, thanks for responding!
I'm at version 2.12 but if i use attributes to store data, it happens that no attributes are being copied when running distributedly, as i pointed out.

I made a mistake when i said "cause it's casted to Future Solution". That is wrong. Is not being casted, a new object is being instanced. See:

At DistributedProblem class: 
`public Solution newSolution() {
		return new FutureSolution(innerProblem.newSolution());
	}`

The constructor of FutureSolution:
`public Solution newSolution() {
		return new FutureSolution(innerProblem.newSolution());
	}`

Solution class:
`protected Solution(Solution solution) {
		this(solution.getNumberOfVariables(), solution.getNumberOfObjectives(),
				solution.getNumberOfConstraints());

		for (int i = 0; i < solution.getNumberOfVariables(); i++) {
			setVariable(i, solution.getVariable(i).copy());
		}

		for (int i = 0; i < getNumberOfObjectives(); i++) {
			setObjective(i, solution.getObjective(i));
		}

		for (int i = 0; i < getNumberOfConstraints(); i++) {
			setConstraint(i, solution.getConstraint(i));
		}
	}`

The constructor of the Solution class (with "Solution solution" as parameter) isn't taking attributes from the solution parameter/variable, so it seems that they are being lost.
My problem is that i need them to calculate fitness.

I'm a noob at MOEA and i'm probably doing something wrong. Could you tell me why? 
Sorry about my English.

Thank you very much!
