### ISSUE TITLE
Constraint normalization

### ISSUE THREAD

**Issue by emelmdn** [MOEAFramework/MOEAFramework#213]
Hello, 

I am trying to use MOEA for my maximization problem. I normalized my score function, so that my score is always between 0 and 1. However I didn't normalize the punishment values. How is punishment values used in the score? If it is summed up to the score, then my real score values could be unimportant due to the huge punishment score values. As a summary, do I need to normalize the punishment as well? 

Thanks in advance,
Emel

**Comment by dhadka** [comment]
Hi,

The MOEA Framework don't have the concepts of score and punishment built in, so it's up to your code to aggregate those two values into an objective value.  Normalization would be a good idea, but it can be non-trivial to choose an appropriate normalization.  If you know approximately the min/max bounds, that can help a lot.

If you take the multi-objective approach, you could have your score and punishment as two objectives.  Then, you would see the tradeoff between those two values.  Also, no normalization is necessary.

Kind Regards,
Dave

**Comment by emelmdn** [comment]
Hi,

Thanks a lot for your prompt answer. I did not aggregate the score and punishment. I used constraints in the evaluate() method to assign punishment to my solution candidate of my single objective problem. Even if my score is normalized (I know the maximum value), I cannot normalize the punishment (as you mentioned, I don't know its maximum value.). As I understood from your answer, this is ok, right?

Just to be sure: I will add some new objectives to my problem. I do not need to make any normalization for the new objectives, right? The existing one is already normalized and I don't want it to be ignored due to the bigger rank of the new objectives. (In other words, 10.000 of another objective might be more selectable than 0.8 of the first objective.)

Thanks and regards,
Emel

**Comment by emelmdn** [comment]
Hi again,

I guess, I misstated my problem: I did not enter any specific punishment, but I used the "constraint" of MOEA, as you can see in the evaluate method below. Sorry for the confusion. So, back to my question: Does it matter that my objectives in the evaluate method are normalized (in range 0 to 1) but my constraints in the same method are not normalized and can be around the value 100.0000? 

	public void evaluate(Solution solution){
		...
		double[] objectives = new double[nObjectives]; 
		objectives = evaluateObjectives(assignment);
	        ...
		double[] constraints = new double[nConstraints];
		constraints = evaluateConstraints(assignment);
		
		// negate the objectives since CSAP is maximization and MOEA is minimization only
		solution.setObjectives(Vector.negate(objectives));
	        solution.setConstraints(constraints);
                ...
