### ISSUE TITLE
Implementation of PSO algorithm in moea

### ISSUE THREAD

**Issue by Amit-1984** [MOEAFramework/MOEAFramework#216]
I was trying to use PSO algorithm for solving our problem. I found that moea framework has omopso class to implement the same. but, right now i do not know how to implement and run OMOPSO?
Earlier, i have implemented and tested the NSGA-III by going through following steps:
1) Defined our own problem by extending the problem class by "AbstractProblem" and overriding the mandatory "evolve()" and "newSolution()" functions in it.
2) Defined own "Mutation" and "Crossover" classes by extending them by "Variation" class. 
3) running the algorithm by defining a new class that has "main()" function in it. in the main function i used the instrumenter and Executor to run the problem by passing the NSGA-III algorithm name to the Executor.

Here, i tried to run the same problem using OMOPSO by replacing NSGA-III name passed to the Executor but i got the following error message:
Exception in thread "main" java.lang.IllegalArgumentException: key not defined in accumulator: Population
	at org.moeaframework.analysis.collector.Accumulator.get(Accumulator.java:102)
	at paper9.RunClusteringProblem.main(RunClusteringProblem.java:137)
Right now, i am unable to understand and solve it. I will be very thankful if you guys help me to overcome this problem by suggesting some example or starting point for the same or giving reference to some other similar problem that has been solved using pso algorithm. 
My motive is not to change the original pso but to use it to solve our problem.

Thanks

**Comment by Amit-1984** [comment]
@dhadka  kindly help me as i have to urgently use the same for my research paper.

**Comment by dhadka** [comment]
Hi Amit,

Sorry for not replying earlier, was away for the holiday.  The issue here is that PSOs do not have a "population", so the default PopulationCollector wasn't working.  I've committed a change (c6f40275) to add a PSOCollector which will read the following fields:

* Particles
* LocalBestParticles
* Leaders

And is used as follows:

```java

Instrumenter instrumenter = new Instrumenter()
	.withProblem("UF1")
	.withFrequency(100)
	.attach(new PSOCollector());
		
new Executor()
	.withProblem("UF1")
	.withAlgorithm("OMOPSO")
	.withMaxEvaluations(10000)
	.withInstrumenter(instrumenter)
	.run();
		
Accumulator accumulator = instrumenter.getLastAccumulator();

for (int i=0; i<accumulator.size("NFE"); i++) {
	System.out.println("NFE: " + accumulator.get("NFE", i));
	ArrayList<Solution> solutions = (ArrayList<Solution>)accumulator.get("Leaders", i);
			
	for (Solution s : solutions) {
		double[] vars = EncodingUtils.getReal(s);
		System.out.println("  " + Arrays.toString(vars) + " => " + Arrays.toString(s.getObjectives()));
	}
			
	System.out.println();
}
```

**Comment by Amit-1984** [comment]
@dhadka  kindly guide in this matter......

**Comment by dhadka** [comment]
1. The position/velocity updates are determined by the optimization algorithm.  In general, the velocity updates are based on the difference between local and global best solutions.  The position is updated by the velocity, plus usually some additional mutation.

2. You only need to implement the Problem interface, so newSolution() and evaluate().

    1. OMOPSO currently does not let you change the Crossover and Mutation operators.  The operators it uses are already well-defined...it uses the standard PSO position/velocity update plus a combination of uniform and non-uniform mutation.  If you are changing it to use different operators, I would suggest naming it something else.

    2. Using your own Mutation operator would be straightforward.  You can just copy [OMOPSO.java](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/pso/OMOPSO.java) and use your own operators instead.  See the mutate() method.

    3. Changing the Crossover operator will be more difficult.  Since this is PSO, the crossover operator is the position/velocity update.  This is built into [AbstractPSOAlgorithm.java](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/pso/AbstractPSOAlgorithm.java).  Changing this may make it so your algorithm can no longer be classified as "PSO".

    4. If you do end up creating a new class to implement PSO with your custom operators, you would also need to create an [AlgorithmProvider](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/core/spi/AlgorithmProvider.java) and register it with `AlgorithmFactory` before using the Executor.  This is similar to how you introduce a new problem using `ProblemProvider`.

**Comment by Amit-1984** [comment]
@dhadka , i have doubt in the code given in the file AbstractPSOAlgorithm.java. In this class file, i have doubts in the following function:
/**
	 * Update the position of an individual particle.
	 * 
	 * @param i the index of the particle
	 */
	protected void updatePosition(int i) {
		Solution parent = particles[i];
		Solution offspring = parent.copy();
		
		for (int j = 0; j < problem.getNumberOfVariables(); j++) {
			RealVariable variable = (RealVariable)offspring.getVariable(j);
			double value = variable.getValue() + velocities[i][j];
			
			if (value < variable.getLowerBound()) {
				value = variable.getLowerBound();
				velocities[i][j] *= -1;
			} else if (value > variable.getUpperBound()) {
				value = variable.getUpperBound();
				velocities[i][j] *= -1;
			}
			
			variable.setValue(value);
		}
		
		particles[i] = offspring;		
	}
My doubts are:
1) in this function the "offspring" may not be updated (however, according to my viewpoint, i think it should be updated as per the velocity values.
2) as offspring values is not changed during code, so what is the use of the line particles[i] = offspring in the code.
3) how and where the particles are being updated for each of the iteration of the algorithm.

Thanks in advance.

**Comment by dhadka** [comment]
The offspring variables should be updated when calling `variable.setValue(value);`.

**Comment by Amit-1984** [comment]
@dhadka  thanks for the help....
Further i have few doubts and these are:-
1) how the NFE actually works? In my case every time i prints its value, it always starts from NFE = 100 and then if my population size is 2 then next value is NFE = 102. Is it linked with population size? and why it starts with 100 only even when i set the maxEvaluation as 1 or 2.
2) how can i print the particles iterations by iteration in pso . actually i want to check how the particles are being updated?

**Comment by Amit-1984** [comment]
Hello Everyone, kindly help me implement a scenario and solve it using PSO. The description is as follows:
1). i want to implement a multi-objective scenario for obtaining the optimized clustering solution using pso. the clusters are obtained as pair of 2/3/4 (specified in different run of the problem).
2). for the same, i have designed a class named "ClusteringProblem.java" and it overrides two functions namely newSolution() and evolve() functions.
3). to run the problem, i have created a new class named "RunClusteringProblem.java".
4). The code of these files are as follows:-

// ClusteringProblem.java
package PSO;

import java.io.BufferedReader;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Random;
import java.util.StringTokenizer;
import java.util.Vector;

import org.moeaframework.core.Solution;
import org.moeaframework.core.variable.EncodingUtils;
import org.moeaframework.problem.AbstractProblem;

public class ClusteringProblem extends AbstractProblem {
	private int clusterSize = 3;
	
	public ClusteringProblem() {
		//number of classes, number of objectives
		super(tClass, 2);
		String line = null;
	}
	
	public void evaluate(Solution solution) {
		int clusterScheme[] = EncodingUtils.getInt(solution);
		
		System.out.print("\nEvaluating the Particle: ");
		for(int i = 0; i<clusterScheme.length; i++)
			System.out.print(clusterScheme[i]+" ");
		System.out.println();
		
		// finding unique cluster numbers in the given solution
		HashSet<Integer> uniqueClustNumber = new HashSet<Integer>();
		for(int i = 0; i<clusterScheme.length; i++)
		{
			if(!uniqueClustNumber.contains(clusterScheme[i]))
				uniqueClustNumber.add(clusterScheme[i]);
		}
		//System.out.println("Unique Cluster Numbers Are: "+uniqueClustNumber);
		
		// finding FUP based cohesion at component level
		double avgRankScore = Math.random();
		// finding semantic based cohesion at component level
		double avgSemanticScore = Math.random();
		
		// setting objective "the rank score based on Frequent Usage patterns"
		obj_rankScore = avgRankScore;
		obj_semanticScore = avgSemanticScore;
		//obj_rankScore = 0;
		//obj_semanticScore = 0;
		
		//System.out.println("Different Objective Funtion's Values Are: ");
		//System.out.println("\t1. The Rank-Score based on FUP (Maximizing): "+ obj_rankScore);
		//System.out.println("\t2. The Semantic-Relatedness (Maximizing): "+ obj_semanticScore);
		
		solution.setObjective(0, -obj_rankScore);
		solution.setObjective(1, -obj_semanticScore);
	}
	
	@Override
	public Solution newSolution() {
		Solution solution = new Solution(getNumberOfVariables(), getNumberOfObjectives());
		ArrayList<Integer> indices = new ArrayList<Integer>();
		int clusterNumber = 1;
		int totalClusters = (int) getNumberOfVariables()/clusterSize;
		//System.out.println("Clusters= "+totalClusters);
		for(int i = 0; i<totalClusters; i++)
		{
			for(int j = 0; j<clusterSize; j++)
			{
				Random rand = new Random();
				int index = rand.nextInt(getNumberOfVariables());
				while(indices.contains(index))
					index = rand.nextInt(getNumberOfVariables());
				indices.add(index);
				solution.setVariable(index, EncodingUtils.newInt(clusterNumber, clusterNumber));
			}
			clusterNumber++;
		}
		if(indices.size() != getNumberOfVariables())
		{
			for(int i = 0; i<getNumberOfVariables(); i++)
			{
				if(!indices.contains(i))
					solution.setVariable(i, EncodingUtils.newInt(clusterNumber, clusterNumber));
			}
		}

		return solution;
	}
	
	//private int totalCount = 0;
	private static int tClass = 10;
	//private static int tClass = 5;
	private static int tVariables = 119;
	//private static int tVariables = 10;
	private static Vector<String> classNameArray = new Vector<String>();
	private static Vector<Integer> variablePackages = new Vector<Integer>();
	@SuppressWarnings("rawtypes")
	private static HashMap<String, Vector> FUPVectorHashMap = new HashMap<String, Vector>();
	private static HashMap<String,  ArrayList<Double>> semanticVectorHashMap = new HashMap<String,  ArrayList<Double>>();
	private HashMap<String, ArrayList<Double>> tfidfMap = new HashMap<String, ArrayList<Double>>();
	private static Vector<Integer> tempfupVector;
	private static ArrayList<Double> tempSemanticVector;
	private static double obj_rankScore;
	private static double obj_semanticScore;
	private BufferedReader br;
	private int totalTokens = 0;
	private ArrayList<Double> idfArrayList = new ArrayList<Double>();
	private int totalClasses = 0, totalInterfaces = 0;
}


// Class designed to run the problem is as follows:-
//RunClusteringProblem.java
package PSO;

import java.util.ArrayList;
import java.util.Arrays;
import org.moeaframework.Executor;
import org.moeaframework.Instrumenter;
import org.moeaframework.analysis.collector.Accumulator;
import org.moeaframework.analysis.collector.PSOCollector;
import org.moeaframework.core.Solution;
import org.moeaframework.core.variable.EncodingUtils;

public class RunClusteringProblemPSO {
	@SuppressWarnings("unchecked")
	public static void main(String[] args) throws ClassNotFoundException {
		Instrumenter instrumenter = new Instrumenter()
			.withProblemClass(ClusteringProblem.class)
			.withFrequency(100)
			.attach(new PSOCollector());
				
		new Executor()
			.withProblemClass(ClusteringProblem.class)
			.withAlgorithm("OMOPSO")
			.withProperty("populationSize", 30)
			//.withProperty("populationSize", 2)
			.withMaxEvaluations(1000)
			//.withMaxEvaluations(100)
			.withInstrumenter(instrumenter)
			.run();
				
		Accumulator accumulator = instrumenter.getLastAccumulator();

		for (int i=0; i<accumulator.size("NFE"); i++) {
			System.out.println("NFE: " + accumulator.get("NFE", i));
			ArrayList<Solution> solutions = (ArrayList<Solution>)accumulator.get("Leaders", i);
			
			for (Solution s : solutions) {
				int[] vars = EncodingUtils.getInt(s);
				System.out.println("  " + Arrays.toString(vars) + " => " + Arrays.toString(s.getObjectives()));
			}
					
			System.out.println();
		}
	}	
}

My problem in this created solution is as follows:
1). As i have created 30 particles containing random clustering initialization obtained usiing newSolution() function. When the OMOPSO algorithm finishes, the obtained optimized result is one from the created 30 random particles only. I fear, my implementation is somehow not able to modify the clustering solutions/ particles during various iterations (i am unable to identify why this is happening).

I am stuck at this point and clueless right now. So, i request if someone, help me in this matter and guide me by running my files.

Thanks in advance.

**Comment by Amit-1984** [comment]
@dhaka sir kindly help me in this direction.......

**Comment by Amit-1984** [comment]
@dhaka sir kindly help me in this direction.......

**Comment by Amit-1984** [comment]
Anybody kindly help in this matter.......
