### ISSUE TITLE
Where is Test functions

### ISSUE THREAD

**Issue by rrreza** [MOEAFramework/MOEAFramework#217]
You say: "Over 1200 test cases to ensure validity. Every release of the MOEA Framework undergoes
extensive testing and quality control checks. And, if any bugs are discovered that
survive this testing, we will promptly x the issues and release patches."
but where is these functions.
I want use NSGA-II for MOP6. (Evolutionary Algorithms for Solving Multi-Objective Problems -Second Edition- Carlos A. CoelloCoello, Gary B. Lamont and David A. Van Veldhuizen- Page:102) 
I do not see any table to show 1200 functions and any help(tutorial) to create new function.
I need NSGA-II for MOP6. please help me...

**Comment by dhadka** [comment]
Hi @rrreza , "over 1200 test cases" refers to the unit tests in the test/ folder.  These are not multiobjective problems.  

The multiobjective problems you're looking for are in [src/org/moeaframework/problem](https://github.com/MOEAFramework/MOEAFramework/tree/master/src/org/moeaframework/problem).   You'll need to create a new problem for MOP6 by extending AbstractProblem.  [OKA1](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/problem/misc/OKA1.java) would be a good starting point, for example.

**Comment by rrreza** [comment]
Hello. OK
But I want to see the real issue and not its code.
Please provide a reference to receive the problem form.
