### ISSUE TITLE
Urgent help regarding customizing pso for a clustering problem

### ISSUE THREAD

**Issue by Amit-1984** [MOEAFramework/MOEAFramework#220]
Hello Everyone, kindly help me implement a scenario and solve it using PSO. The description is as follows:
1). i want to implement a multi-objective scenario for obtaining the optimized clustering solution using pso. the clusters are obtained as pair of 2/3/4 (specified in different run of the problem).
2). for the same, i have designed a class named "ClusteringProblem.java" and it overrides two functions namely newSolution() and evolve() functions.
3). to run the problem, i have created a new class named "RunClusteringProblem.java".
4). The code of these files are as follows:-

// ClusteringProblem.java
package PSO;

import java.io.BufferedReader;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Random;
import java.util.StringTokenizer;
import java.util.Vector;

import org.moeaframework.core.Solution;
import org.moeaframework.core.variable.EncodingUtils;
import org.moeaframework.problem.AbstractProblem;

public class ClusteringProblem extends AbstractProblem {
private int clusterSize = 3;

public ClusteringProblem() {
	//number of classes, number of objectives
	super(tClass, 2);
	String line = null;
}

public void evaluate(Solution solution) {
	int clusterScheme[] = EncodingUtils.getInt(solution);
	
	System.out.print("\nEvaluating the Particle: ");
	for(int i = 0; i<clusterScheme.length; i++)
		System.out.print(clusterScheme[i]+" ");
	System.out.println();
	
	// finding unique cluster numbers in the given solution
	HashSet<Integer> uniqueClustNumber = new HashSet<Integer>();
	for(int i = 0; i<clusterScheme.length; i++)
	{
		if(!uniqueClustNumber.contains(clusterScheme[i]))
			uniqueClustNumber.add(clusterScheme[i]);
	}
	//System.out.println("Unique Cluster Numbers Are: "+uniqueClustNumber);
	
	// finding FUP based cohesion at component level
	double avgRankScore = Math.random();
	// finding semantic based cohesion at component level
	double avgSemanticScore = Math.random();
	
	// setting objective "the rank score based on Frequent Usage patterns"
	obj_rankScore = avgRankScore;
	obj_semanticScore = avgSemanticScore;
	//obj_rankScore = 0;
	//obj_semanticScore = 0;
	
	//System.out.println("Different Objective Funtion's Values Are: ");
	//System.out.println("\t1. The Rank-Score based on FUP (Maximizing): "+ obj_rankScore);
	//System.out.println("\t2. The Semantic-Relatedness (Maximizing): "+ obj_semanticScore);
	
	solution.setObjective(0, -obj_rankScore);
	solution.setObjective(1, -obj_semanticScore);
}

@Override
public Solution newSolution() {
	Solution solution = new Solution(getNumberOfVariables(), getNumberOfObjectives());
	ArrayList<Integer> indices = new ArrayList<Integer>();
	int clusterNumber = 1;
	int totalClusters = (int) getNumberOfVariables()/clusterSize;
	//System.out.println("Clusters= "+totalClusters);
	for(int i = 0; i<totalClusters; i++)
	{
		for(int j = 0; j<clusterSize; j++)
		{
			Random rand = new Random();
			int index = rand.nextInt(getNumberOfVariables());
			while(indices.contains(index))
				index = rand.nextInt(getNumberOfVariables());
			indices.add(index);
			solution.setVariable(index, EncodingUtils.newInt(clusterNumber, clusterNumber));
		}
		clusterNumber++;
	}
	if(indices.size() != getNumberOfVariables())
	{
		for(int i = 0; i<getNumberOfVariables(); i++)
		{
			if(!indices.contains(i))
				solution.setVariable(i, EncodingUtils.newInt(clusterNumber, clusterNumber));
		}
	}

	return solution;
}

//private int totalCount = 0;
private static int tClass = 10;
//private static int tClass = 5;
private static int tVariables = 119;
//private static int tVariables = 10;
private static Vector<String> classNameArray = new Vector<String>();
private static Vector<Integer> variablePackages = new Vector<Integer>();
@SuppressWarnings("rawtypes")
private static HashMap<String, Vector> FUPVectorHashMap = new HashMap<String, Vector>();
private static HashMap<String,  ArrayList<Double>> semanticVectorHashMap = new HashMap<String,  ArrayList<Double>>();
private HashMap<String, ArrayList<Double>> tfidfMap = new HashMap<String, ArrayList<Double>>();
private static Vector<Integer> tempfupVector;
private static ArrayList<Double> tempSemanticVector;
private static double obj_rankScore;
private static double obj_semanticScore;
private BufferedReader br;
private int totalTokens = 0;
private ArrayList<Double> idfArrayList = new ArrayList<Double>();
private int totalClasses = 0, totalInterfaces = 0;

}

// Class designed to run the problem is as follows:-
//RunClusteringProblem.java
package PSO;

import java.util.ArrayList;
import java.util.Arrays;
import org.moeaframework.Executor;
import org.moeaframework.Instrumenter;
import org.moeaframework.analysis.collector.Accumulator;
import org.moeaframework.analysis.collector.PSOCollector;
import org.moeaframework.core.Solution;
import org.moeaframework.core.variable.EncodingUtils;

public class RunClusteringProblemPSO {
@SuppressWarnings("unchecked")
public static void main(String[] args) throws ClassNotFoundException {
Instrumenter instrumenter = new Instrumenter()
.withProblemClass(ClusteringProblem.class)
.withFrequency(100)
.attach(new PSOCollector());

	new Executor()
		.withProblemClass(ClusteringProblem.class)
		.withAlgorithm("OMOPSO")
		.withProperty("populationSize", 30)
		//.withProperty("populationSize", 2)
		.withMaxEvaluations(1000)
		//.withMaxEvaluations(100)
		.withInstrumenter(instrumenter)
		.run();
			
	Accumulator accumulator = instrumenter.getLastAccumulator();

	for (int i=0; i<accumulator.size("NFE"); i++) {
		System.out.println("NFE: " + accumulator.get("NFE", i));
		ArrayList<Solution> solutions = (ArrayList<Solution>)accumulator.get("Leaders", i);
		
		for (Solution s : solutions) {
			int[] vars = EncodingUtils.getInt(s);
			System.out.println("  " + Arrays.toString(vars) + " => " + Arrays.toString(s.getObjectives()));
		}
				
		System.out.println();
	}
}	

}

My problem in this created solution is as follows:
1). As i have created 30 particles containing random clustering initialization obtained usiing newSolution() function. When the OMOPSO algorithm finishes, the obtained optimized result is one from the created 30 random particles only. I fear, my implementation is somehow not able to modify the clustering solutions/ particles during various iterations (i am unable to identify why this is happening).

I am stuck at this point and clueless right now. So, i request if someone, help me in this matter and guide me by running my files.

Thanks in advance.

**Comment by dhadka** [comment]
I believe the issue is in `newSolution()`, where it is using the same value for the lower and upper bounds: `EncodingUtils.newInt(clusterNumber, clusterNumber)`.  You aren't seeing any other values because no other values are valid.

Additionally, since there is randomness in `newSolution()`, each solution will have a different set of valid variables.  This might have unintended consequences.  I would recommend removing any randomness from `newSolution()`.  Each solution returned should have identical lower and upper bounds.

**Comment by Amit-1984** [comment]
@dhadka  thanks for the quick response and help.
Sir, in my generated particles each of the solution has identical lower and upper bounds. I am considering the following scenario to make the things clear:-
Suppose in my system there are total 10 classes and i want to group them as the pair of two. So, in this scenario there will be total 5 groups, which in my solutions are identified from 1 to 5. in the newSolution function, the association of the classes to different groups are created randomly. So, some of the solutions as per my coding will looks like:-
solution1- 2 3 1 1 3 4 5 2 5 4 and 
solution2- 5 1 3 4 2 1 4 3 2 5  (both solution has identical lower and upper bound)
Now, as per my coding these solutions must be evaluated using pso and each one of it must be mutated during different iterations. So, during iteration solution1 can be changed as per velocities to:
new solution1- 2 3 4 1 4 3 5 2 5 1 (handled by pso during iteration).

I think my situation is clear now, so i request you if you help me by running my code. Actually, my obtained result is always one of the generated initial particles only and the particles are not changing during iterations.

Kindly help

**Comment by Amit-1984** [comment]
anyone kindly help in this direction
