### ISSUE TITLE
Please advice for MOEA.

### ISSUE THREAD

**Issue by MisooKim** [MOEAFramework/MOEAFramework#223]
I am implementing a many-objective optimization problem based on NSGA II and DBEA.
But, because I am not an expert of Evolutionary Algorithms,
I have no idea how to select just "one" (near-optimal) solution from the output list of solutions.

Currently, I am comparing average ranks from each value of objectives for each solution.

If there is a better solution selection method than this, I would like to know how to choose a single solution in general.

Or, are there any related features in this open source?

**Comment by alxbrd** [comment]
Look for the definition of a knee point.

**Comment by GreyWoolf** [comment]
Hi guys,
I have the same question, can anybody help me?

**Comment by MisooKim** [comment]
@GreyWoolf 
I hope that my approach below helps you.

I had wanted to know if there was a related function within the MOEA framework but still couldn't find a function that fit my needs.

As an alternative, I could use the function of Non-dominated sorting, but I think this doesn't seem to be the right choice for selecting the final solution even if it helps the evolution.

So I am choosing the distance-based final solution (knee point), which is the easiest, in my opinion. (Of course, there are other methods.)

To choose a single solution that maximizes all the values ​​of the multiple objective functions, I have selected one solution that satisfies the equation below.

argmax sum (normalize(obj)*normalize(obj))
- obj = a value of each objective function

You can imagine the theorem of Pythagorean. The above equation is for selecting the solution farthest from the zero points based on this theory.


(Reference: Performance Analysis on Knee Point Selection Methods for Multi-objective Sparse Optimization Problems)
