### ISSUE TITLE
Distribute in all cores without Executor() exception

### ISSUE THREAD

**Issue by Reem-Alfayez** [MOEAFramework/MOEAFramework#224]
Hi David,

I tried to distribute my custom problem according to #53 issue. However, I'm getting an exception. 
Where else should I modify my code? 
"Exception in thread "main" org.moeaframework.problem.ProblemException: requires FutureSolution"

Thanks,

**Comment by blysin** [comment]
![image](https://github.com/MOEAFramework/MOEAFramework/assets/13923312/a0e23983-c9a5-40b4-a9ad-6f4238d47235)
I also encountered the same exception. The constructor of the FutureSolution class is not public, and I'm not sure how to handle it.
