### ISSUE TITLE
Genetic Algorithm with many objectives

### ISSUE THREAD

**Issue by emelmdn** [MOEAFramework/MOEAFramework#228]
Hello,

I created a problem with 4 objectives and compared the performance of NSGA2 and NSGA3 on this problem. I also tried to solve the problem with Genetic Algorithm, which should be working for single objective problems only. However, GA found a solution candidate. How can GA work for a problem with 4 objectives? Does it try to optimize only the first objective and ignore the others? Or, is there any other logic behind?

Many thanks and regards,
Emel

**Comment by dhadka** [comment]
It will default to a linear-weighted sum of the objectives using equal weights.  This is all configurable via properties.  See https://github.com/MOEAFramework/MOEAFramework/blob/ee9acb0e09c3abed613106fabaf7231790baea34/src/org/moeaframework/algorithm/StandardAlgorithms.java#L1169 for more details.

**Comment by emelmdn** [comment]
Perfect, thank you very much for your quick and detailed reply.
