### ISSUE TITLE
handling optimization problems with linear inequality and equality constraints

### ISSUE THREAD

**Issue by Alireza-** [MOEAFramework/MOEAFramework#23]
Would you please give me some hints how linear inequality and equality constraints can be defined in the framework. The Knapsack problem is the only example that contains constraints, however I couldn't figure it out when two for-loops that form the constraint g is going to be executed and how it looks like for simple constraints. Long story short, how I can define the following constrains:
Min f(x), f(y), f(z)
S.t.
x+y+z>=c
x=ay
x=dz
y<=bz

Thanks.

**Comment by Alireza-** [comment]
So the answer seems straightforward. One workaround is

**Comment by Alireza-** [comment]
The answer seems straightforward. we need to rearrange equality/inequality constraints in a way that they get handy for comparison within evaluate method.
e.g. x+y+z>=c can be rewritten as x+y+z-c>=0 and then we need to check it does not get negative.
So, it looks like:
cons[0] = x+y+z-c;
if (cons[0] < 0)
cons[0] = 0;

**Comment by dhadka** [comment]
Hi @Alireza- 

That is correct.  The constraint field in the MOEA Framework can be interpreted as "how far is a solution from being feasible?"  A value of 0 means it is feasible, and any non-zero value (both positive and negative) indicates the constraint is violated, with larger values indicate the violation is more severe.  The MOEA then tries to minimize the constraint violation until it can start generating feasible solutions.

(I'm also unable to delete the issue, but it's helpful to have these issues recorded as it's likely others have the same or similar questions.)
