### ISSUE TITLE
The number of param sets in solutions.txt?

### ISSUE THREAD

**Issue by mount10** [MOEAFramework/MOEAFramework#232]
I use the Borg MOEA algorithm, and set the number of iterations to 10,000, use 5 objective functions for my hydrologic model runs. In the output solutions.txt file, there are 24 parameter sets. I want to ask that how were they selected? Are they selected randomly, or follow a pattern? Is it possible to control the number of parameter sets in the solutions.txt? Are the parameter sets there represent the pareto front, but not the whole front? Because I draw the these parameter sets with respect to other parameter sets in runtime.txt file, and found that the parameter sets from solutions.txt do not represent the whole front. Thanks for your help.

**Comment by dhadka** [comment]
Borg uses an epsilon-box dominance operator and the output only contains the epsilon-box non-dominated solutions.  This differs from regular Pareto non-dominance in that we only include one point from each epsilon-box.  This likely accounts for the missing solutions.

**Comment by mount10** [comment]
Thanks for your reply. I am not clear of the epsilon-box dominance operator. What is it specifically? I just know objective functions, parameter ranges, and pareto front.
Is there any value in terms of epsilon-box dominance that I need to set when using Borg? If not, are the 24 parameter sets chosen randomly? That is to say, if I run the 10,000 iterations, will there be different number of parameter sets?
Also another question is, the total number of parameter sets in runtime.txt is higher than 10,000. So what is the role of the number of iterations here? Thanks.
