### ISSUE TITLE
Sometimes does not find any solution?

### ISSUE THREAD

**Issue by JoseCVieira** [MOEAFramework/MOEAFramework#235]
I've realized that, depending on the number of variables, sometimes it does not find any valid solution, whereas I know it exists.

I've created the following simplified example in which the problem occurs.

```
public class DTLZ2 extends AbstractProblem {
	private static final int NR_VARS = 150;
	private static final int MAX_VALUE = 10;
	private static final int possibleValues[] = new int[NR_VARS];
	
	public DTLZ2() {
		super(NR_VARS, 1, 1);
		
		for(int i = 0; i < numberOfVariables; i++) {
			possibleValues[i] = new Random().nextInt(MAX_VALUE);
		}
	}
 
	public Solution newSolution() {
		Solution solution = new Solution(getNumberOfVariables(), getNumberOfObjectives(), getNumberOfConstraints());
 
		for (int i = 0; i < getNumberOfVariables(); i++) {
			solution.setVariable(i, new BinaryIntegerVariable(0, MAX_VALUE));
		}
 
		return solution;
	}
 
	public void evaluate(Solution solution) {
	  int[] x = EncodingUtils.getInt(solution);
	  double cost = 0;
	  double constraint = 0;
	  
	  	for(int i = 0; i < numberOfVariables; i++) {
	  		cost += x[i];
		  
		  	if(x[i] < possibleValues[i]) {
		  		constraint++;
		  	}
	  	}
	  	
	  	solution.setObjective(0, cost);
	    solution.setConstraint(0, constraint);
	}
	
	public static void main(String[] args) {
		NondominatedPopulation result = new Executor()
				.withProblemClass(DTLZ2.class)
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(10000)
				.run();
		  
		for (Solution solution : result) {
			if (solution.violatesConstraints()) continue;
			System.out.println(solution.getObjective(0) + "\n");
		}
	}
}

```

I need always a solution, despite the number of variables. There is something which I'm missing? Or this is the normal behavior? Is it better to start the algorithm with an initial solution, and if so, how can I implement it?

Thanks in advance

**Comment by dhadka** [comment]
This is the expected behavior.  The problem is highly constrained.  Given that it randomly sets the constraint threshold, some of the constraints will require that the decision variable is exactly 0.  Let's just consider those.  There are 11 possible values (0 through 10) for each decision variable, so we would expect on average 150 * (1 / 11) =~ 13 decision variables must have the value 0.  There are 11^13 =~ 34 trillion possible states for these 13 decision variables, but only one state is valid.  You can see how the feasible space is extremely small, and we haven't counted the remaining 137 decision variables.

You can inject initial solutions.  See the answer for https://github.com/MOEAFramework/MOEAFramework/issues/51

**Comment by JoseCVieira** [comment]
@dhadka thanks for the prompt response. Yes, yo're totally right. However, because I'm using the NSGAII, the solver does not pass through all possible states right? Should't it be attracted to the least constrained solutions and, then, use them to preform mutations and crossovers in order to find new ones? Still, if this is the expected behavior, what can I do in this kind of problems?

Thanks once again

**Comment by JoseCVieira** [comment]
@dhadka Sorry to bother you again. I've tried to implement the initialization, however in most of the cases the initial provided solution end-up to be the only final solution. Also, tried to inject the final solutions of an algorithm execution into another execution, in a loop, but it's final solutions are not improving when using a big number of variables. There is something else I can use to check if it can solve this kind of problems?

Below goes the changes I've made to the above code:

```
final Problem problem = new DTLZ2();
final int populationSize = 100;
		
Initialization initialization = new Initialization() {
    @Override
    public Solution[] initialize() {
        Solution[] result = new RandomInitialization(problem, populationSize).initialize();
        for(int j = 0; j < NR_VARS; j++) {
            result[0].setVariable(j, new BinaryIntegerVariable(MAX_VALUE, 0, MAX_VALUE));
        }
        return result;
    }
 };

TournamentSelection selection = new TournamentSelection(2, 
        new ChainedComparator(
                new ParetoDominanceComparator(),
                new CrowdingComparator()));

Variation variation = new GAVariation(
		new SBX(1.0, 15.0),
        new PM(1.0 / problem.getNumberOfVariables(), 20.0));

NSGAII algorithm = new NSGAII(
        problem,
        new NondominatedSortingPopulation(),
        null, // no archive
        selection,
        variation,
        initialization);

while (algorithm.getNumberOfEvaluations() < 10000) {
    algorithm.step();
}

NondominatedPopulation result = algorithm.getResult();

while (true) {
	List<Solution> injectedSolutions = new ArrayList<Solution>();
    
	for (Solution solution : result) {
		if (solution.violatesConstraints()) continue;
                injectedSolutions.add(solution);
		System.out.println(solution.getObjective(0) + "\n");
	}
	
	initialization = new InjectedInitialization(problem, populationSize, injectedSolutions);

    algorithm = new NSGAII(
            problem,
            new NondominatedSortingPopulation(),
            null, // no archive
            selection,
            variation,
            initialization);

    while (algorithm.getNumberOfEvaluations() < 10000) {
        algorithm.step();
    }

    result = algorithm.getResult();
}
```

**Comment by dhadka** [comment]
I would recommend changing the constraint calculation to provide a better gradient for selection.  For example, instead of 

```
		  	if(x[i] < possibleValues[i]) {
		  		constraint++;
		  	}
```

I would try

```
		  	if(x[i] < possibleValues[i]) {
		  		constraint += possibleValues[i] - x[i];
		  	}
```
