### ISSUE TITLE
Evaluating WFG1-9 with more objectives and variables

### ISSUE THREAD

**Issue by Milenche** [MOEAFramework/MOEAFramework#246]
Hi, 

Is there a way to use the inbuilt scalable test problems (like DTLZ, WFG, etc.) by passing arguments for different number of objectives and variables? I see there are k, l, M variables defined for these problems, but how does one pass these arguments when solving a problem?
NondominatedPopulation result = new Executor()
				.withProblem("UF1")
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(10000)
				.run();
I also see there is a way to define a new problem, but that requires explicit coding the functions. 

Thank you in advance!

**Comment by dhadka** [comment]
You can call any of the constructors with:

```
new Executor()
    .withProblem(<Problem Class>, <Constructor args>, ...)
```

Such as:

```
new Executor()
    .withProblem(WFG1.class, 1, 10, 2)
```

The three numbers above correspond to the k, l, and m arguments used by the constructor - http://moeaframework.org/javadoc/org/moeaframework/problem/WFG/WFG1.html#WFG1(int,%20int,%20int)

**Comment by Milenche** [comment]
Thank you so much for the fast response!

For DTLZ test suite works great:
		NondominatedPopulation result = new Executor()
				.withProblem**Class**(DTLZ1.class, 5)
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(10000)
				.run();

But for WFG I get NaN for all objective functions when I increase the number of objective to >2
		NondominatedPopulation result = new Executor()
				.withProblemClass(WFG1.class, 1,10,3)
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(10000)
				.run();

Any idea why this is happening?

**Comment by dhadka** [comment]
It looks like there's some conditions of the args that must be true, as shown here: https://github.com/MOEAFramework/MOEAFramework/blob/41b4a77076bfe83820ffb20598cb8f474e72e250/src/org/moeaframework/problem/WFG/Problems.java#L54

One is that `k % (m-1) == 0`.  I would try making the first argument 2.

These are currently assertions which will only throw if you have the `-ea` option enabled (e.g., `java -ea ...`).  I might make these exceptions instead so they are thrown at runtime.

**Comment by Milenche** [comment]
ok, thank you
