### ISSUE TITLE
MOEAFramework Setup Help

### ISSUE THREAD

**Issue by chelsmpeterson** [MOEAFramework/MOEAFramework#255]
I am having trouble with setting up MOEAFramework. I installed the latest JDK package 14.0.2, Maven, and set all of the paths, but whenever I try to launch the diagnostic tool I get an error:
![image](https://user-images.githubusercontent.com/53186732/92523543-255f5c00-f1e6-11ea-84eb-2e0704f9e156.png)

I looked up the Error message on Stack Exchange but could not find something similar. Does anyone know where I am going wrong?

**Comment by dhadka** [comment]
Hi, I think changing `-Djava.ext.dirs=lib` to `-classpath lib` will work.  If you're using the `.bat` file, edit it and make this change.

**Comment by chelsmpeterson** [comment]
Ok, I did updated the .bat file, but I get another error:

![image](https://user-images.githubusercontent.com/53186732/93384778-e73beb00-f82a-11ea-9f5e-25521e2e8671.png)

**Comment by dhadka** [comment]
Sorry, use `java -classpath lib/* org.moeaframework.analysis.diagnostics.LaunchDiagnosticTool` instead.

**Comment by chelsmpeterson** [comment]
That worked, thank you.

**Comment by dhadka** [comment]
Closing. This is fixed in `master` and will be included in the next release (`3.1`).
