### ISSUE TITLE
How to define .exe with arguments

### ISSUE THREAD

**Issue by chelsmpeterson** [MOEAFramework/MOEAFramework#261]
I want to supply an argument to the executable of an external C program so that I can run several optimizations in parallel without recompiling the exe multiple times with different names. When I try to add an argument ("E") to the problem class

  public static class CalRuntime extends ExternalProblem
  {
    public CalRuntime() throws IOException
    {
	    super("./Calibration/rzRun.exe E");
    }

I get a long error which includes "Caused by: java.io.IOException: Cannot run program "./Calibration/rzRun.exe E": CreateProcess error=2, The system cannot find the file specified" 

How else could I supply an argument?

**Comment by dhadka** [comment]
Pass them in as separate arguments: `super("./Calibration/rzRun.exe", "E");`

**Comment by chelsmpeterson** [comment]
Ok that worked. Is this the right way to pass an argument to the Java program? 

I made "site" an argument:

public CalRuntime(String site) throws IOException
{
	super("./Calibration/rzRun.exe", site);
}

Then, in main() I get the study site name and added an argument to .withProblemClass()

public static void main(String[] args)
{
  /* study site name */
  String site = args[0];

...

/* set up instrumenter */
Instrumenter instrumenter = new Instrumenter()
		.withProblemClass(CalRuntime.class, site)
		.withReferenceSet(refSet)
		.withFrequency(100)
		.attachAll();

...

}

**Comment by dhadka** [comment]
Yes, looks 👍
