### ISSUE TITLE
How to define a Constraint?

### ISSUE THREAD

**Issue by HamedSharifian** [MOEAFramework/MOEAFramework#262]
Hello.
I can't find any specification about defining constraints in a problem.
I wonder if could know that how can I add a constraint to a problem?

**Comment by loehnertz** [comment]
> The MOEA Framework represents constraints a bit differently. Instead of needing to know the constraint formula, the MOEA Framework simply says “set the constraint value to 0 if the solution is feasible, set it to any non-zero value if the constraint is violated.”

Firstly, You have to instantiate your solution with as many constraints as you have.
Secondly, say your constraint is that the objective `o1` has to be greater than `5.5`, you would use it like so:
```
solution.setObjective(0, o1);
solution.setConstraint(0, o1 > 5.5 ? 0.0 : -1.0);
```
And better to put the hard-coded `-1.0` into a constant to be sure to still know in some time what that was supposed to mean 👍
