### ISSUE TITLE
Probably misleading JavaDoc

### ISSUE THREAD

**Issue by Leative** [MOEAFramework/MOEAFramework#270]
Hi,

I am using MOEA for quite a while now but just realized the JavaDoc of [AbstractAlgorithm](https://github.com/MOEAFramework/MOEAFramework/blob/53d2081b59e084e8df6d0c26240232a4f33c0d99/src/org/moeaframework/algorithm/AbstractAlgorithm.java) doesn't make sense to me.

The class description states that:

> All method extending this class must use the
> {@link #evaluate} method to evaluate a solution.

At the same time, the description of `evaluateAll()` states:

> This method calls
> {@link #evaluate(Solution)} on each of the solutions. Subclasses should
> prefer calling this method over {@code evaluate} whenever possible,
> as this ensures the solutions can be evaluated in parallel.

First, to me this looks like a contradiction. Second, I don't see how `evaluateAll` contributes to paralellism. It just sequentially iterates.

Best wishes,
Stefan

**Comment by dhadka** [comment]
Tried to clarify it in https://github.com/MOEAFramework/MOEAFramework/pull/294.  You can use `evaluate` or `evaluateAll`.  But avoid using `problem.evaluate(...)` as that bypass how we track the number of function evaluations.

**Comment by Leative** [comment]
That makes sense, thanks. I get the feeling that this was also meant by the JavaDoc of `evaluateAll`?
However, the text is totally ambiguous. What I understood when reading it was:

Evaluates the specified solutions. This method calls {@link #evaluate(Solution)} on each of the solutions. Subclasses should prefer calling **this method** (´evaluateAll´) over **{@code evaluate}** (the ´evaluate´ method of this class) whenever possible, as this ensures the solutions can be evaluated in parallel.

With your changes to the class JavaDoc it seems to me that **this method** actually refers to ´evaluate´ of ´AbstractAlgorithm´ and **{@code evaluate}** refers to ´Problem.evaluate´.

If that's what it's all about, I would suggest deleting the "Subclasses should..." part as it is now redundant to the class description.
