### ISSUE TITLE
www.lulu.com is inaccessible, so I can't buy the tutorial

### ISSUE THREAD

**Issue by XDD199** [MOEAFramework/MOEAFramework#272]
www.lulu.com is inaccessible, so I can't buy the tutorial

**Comment by dhadka** [comment]
@XDD199 Are you still having issues accessing lulu.com?  If so, please send me an e-mail at admin (at) moeaframework (dot) org so I can get you a copy.

**Comment by XDD199** [comment]
你好，许冬冬已收到你的邮件~ 祝身体健康，万事如意！

**Comment by dhadka** [comment]
Closing issue as it's moved to e-mail.
