### ISSUE TITLE
IBEA crowding distance indicator

### ISSUE THREAD

**Issue by Gan0k** [MOEAFramework/MOEAFramework#28]
[Missing feature / Typo on the Manual]
MOEAFramework's manual mentions that IBEA can run with an indicator using the crowding distance metric, but when I run IBEA with the parameter "indicator" set to "crowding" the program crashes. Looking through the code I cannot find the portion that implements the usage of the crowding distance indicator for IBEA, and by default the parameter is set to "hypervolume". Was then IBEA ever supposed to run with the crowding distance indicator or is there a typo on the manual?

**Comment by dhadka** [comment]
It looks like a typo.  It should only support hypervolume and epsilon.

**Comment by Gan0k** [comment]
Okay! Thank you for the quick answer.
