### ISSUE TITLE
More like a Question

### ISSUE THREAD

**Issue by Nozo** [MOEAFramework/MOEAFramework#3]
Is there any way to use the Executor and attach an initialization (array of solutions) for the different algorithms?

Because if that`s possible it should be relatively easy to run executors in different threads and build a island parallelization by just initialize the algorithm via the executor with the result of the last evolutionary step. 

I like the concept behind the Executor, Instrumenter and Analyzer and it would be great if I can use it in combination with an island parallelization.

At the moment I evaluate different frameworks for multi object optimization and that would be a great advantage of the MOEAFramwork!

**Comment by dhadka** [comment]
Unfortunately, in the current version, this can't be done.  I think this would be a useful feature, but it unfortunately is not a quick fix as it requires rewriting the algorithm providers to accept an initial population.  Until then, you'll need to manually create the algorithm using its constructor, which lets you specify the initialization method.

**Comment by Nozo** [comment]
Thx for the information!
How is it possible to add multiple Operators to an algorithm ?! 
For example the Executor adds the SBX crossover operator and the PM mutation operator to the SPEA2 or the NSGA2 algorithm. If I now use the constructor to create a SPEA2 object I have only the possibility to the get 1 Operator via the Variation argument to the SPEA2 Object , how I can add multiple operators?

**Comment by dhadka** [comment]
The simplest way is to use the [OperatorFactory](http://moeaframework.org/javadoc/org/moeaframework/core/spi/OperatorFactory.html), which lets you describe your variation operator using a string.  For example, `OperatorFactory.getInstance().getVariation("sbx+pm", new TypedProperties(), problem)`.

For more control, you can also manually create the operator.  If you just need the standard crossover/mutation operator, use [GAVariation](http://moeaframework.org/javadoc/org/moeaframework/core/operator/GAVariation.html).  Use [CompoundVariation](http://moeaframework.org/javadoc/org/moeaframework/core/operator/CompoundVariation.html) to combine two or more operators.

**Comment by Nozo** [comment]
Thanks a lot!
The CompoundVariation is exactly what I am looking for!

**Comment by dhadka** [comment]
Closing this ticket.  Please open a new one if you have additional questions.
