### ISSUE TITLE
ProviderNotFoundException after making changes to JMetal source code

### ISSUE THREAD

**Issue by abdulhameedpk** [MOEAFramework/MOEAFramework#31]
I am using MoeaFramework 2.4. I need to embed my problem repairing code in the JMetal's SBXrossover and PolynomialMutation so I downloaded the JMetal 4.3 source code and import it in the Eclipse. The Eclipse IDE is able to found all changes that I  made in the JMetal 4.3 source code. All changes are compiled without any error. 

The class files are in `/bin/org/..` for moeaframework and  `/bin/jmetal/..` for JMetal 4.3. The following code raises the exception `ProviderNotFoundException no provider for PAES` .
```
Executor executor = new Executor()
.withProblem("myProblem")
.withProperty(..
..
executor.withAlgorithm("PAES");
executor.runSeeds(nSeeds);
```
Thanks in Advance

**Comment by dhadka** [comment]
Please ensure the META-INF/ folder is in your Java Build Path, as shown in the screenshot below.

![screenshot](https://cloud.githubusercontent.com/assets/2496211/12718186/caf00200-c8ba-11e5-9629-f53b838facdc.png)

As an aside, I would encourage you to upgrade to the latest version of the MOEA Framework (v2.8).  It now includes SPEA2, PAES, PESA2, OMPSO, SMPSO, IBEA, and SMS-EMOA natively, so you wouldn't need to worry about modifying JMetal's operators.

**Comment by abdulhameedpk** [comment]
Thanks David that's work
