### ISSUE TITLE
Why running the NSGAII algorithm in MOEA Java framework always deliver 100 pareto solutions

### ISSUE THREAD

**Issue by Naomilicious** [MOEAFramework/MOEAFramework#36]
Hi, I used MOEA Java framework to solve three-objective linear programming problem, and employed the NSGA-II algorithm. I don't know why the number of output solutions are always 100. Does the 100 mean the maximum number of solutions can be generated in MOEA framwork or NSGA-II algorithm? How can I change this number in the jave code?

Looking forward to some help.

**Comment by dhadka** [comment]
The `"populationSize"` parameter for NSGA-II controls the maximum number of solutions:

```java

NondominatedPopulation result = new Executor()
    .withProblem("UF1")
    .withAlgorithm("NSGAII")
    .withProperty("populationSize", 200)
    .withMaxEvaluations(10000)
    .run();
```

Note that the result only contains non-dominated solutions, which may be less than the population size.

**Comment by Naomilicious** [comment]
Hi David,

Thank you for the quick response. I have a question that is the default
popsize 100 in MOEA? How can I check the default value?

Thanks and regards,
Naomi

**Comment by dhadka** [comment]
The parameters, a description, and their default values can be found in Appendx A in the [Beginner's Guide](http://moeaframework.org/documentation.html).  You can also find the defaults in the code in `StandardAlgorithms.java`.

**Comment by Naomilicious** [comment]
Hi David,

Thank you very much, I found it. That means, if I want to constraint the
number of output, let's say 20 non-dominated solutions, I can reduce the
popsize to 20? I am wondering will it affect the optimal searching results
by NSGA when the popsize is set to a very small figure.

Thanks and regards,
Naomi

**Comment by dhadka** [comment]
There are several ways to limit the output.  Changing the population size will have that effect, but it can also change the dynamics of the algorithm (possibly degrading performance as a result of less diversity).

One alternative is to use epsilon dominance.  The epsilons essentially place a grid over the objective space and allow only one solution to fall within each grid cell.  This acts as a minimum resolution or precision.  You can use [Executor#withEpsilon](http://moeaframework.org/javadoc/org/moeaframework/Executor.html#withEpsilon(double...)) to set the epsilon values.

You could alternatively put your results into a [NondominatedSortingPopulation](http://moeaframework.org/javadoc/org/moeaframework/core/NondominatedSortingPopulation.html) and use the `truncate` method to reduce the size to 20.  It will remove points from crowded regions first.

**Comment by Naomilicious** [comment]
Hi David,

Thank you for the response.

I am facing a new problem that the 100 Pareto solutions (popsize=100) are
always some how located centrally on the Pareto frontier after many
iterations (say 50,0000). In other words, the results from NSGAII did not
include any extreme points regarding each objective function (the full
Pareto set should contain the extreme points along each objective right?).
In addition, the the objective function values of the output 100 solutions
are much less than the optimal value when considering single objective
optimization.

I am wondering how can I handle this issue in order to let the results
cover most of the solutions on Pareto front, such as adding a convergence
threshold?


Thanks and regards,
Naomi

**Comment by Naomilicious** [comment]
I am thinking if this issue can be solved by setting Epsilon to a small
value using command .withEpsilon?

Thanks and regards,
Naomi

**Comment by Naomilicious** [comment]
Actually, I found a bug or a problem while running NSGAII in MOEA framework.

See the below simple test: a three-objective linear optimization, the sum
of two variables equal to 50, each less than 30. The Pareto results does
not include the extreme points of the 2nd and 3rd objective functions
regardless of number of iterations and popsize.

import static java.lang.Math.pow;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.moeaframework.Executor;
import org.moeaframework.core.NondominatedPopulation;
import org.moeaframework.core.Solution;
import org.moeaframework.core.variable.EncodingUtils;
import org.moeaframework.core.variable.RealVariable;
import org.moeaframework.problem.AbstractProblem;
import org.moeaframework.util.Vector;

public class Andre {

    public static class MO extends AbstractProblem {

        private int numberOfVariables;
        private int numberOfObjectives;
        private int numberOfConstraints;

        public MO() {
            super(2, 3, 1);
            numberOfVariables = 2;
            numberOfObjectives = 3;
            numberOfConstraints = 1;
        }

        @Override
        public Solution newSolution() {
            Solution solution = new Solution(getNumberOfVariables(),
getNumberOfObjectives(), getNumberOfConstraints());

            for (int i = 0; i < getNumberOfVariables(); i++) {
                solution.setVariable(i, new RealVariable(0.0, 30.0));
            }

            return solution;
        }

        @Override
        public void evaluate(Solution solution) {
            int[] x = EncodingUtils.getInt(solution);
            double[] f = new double[numberOfObjectives];
            double[] g = new double[numberOfConstraints];

            double[][] b = new
double[numberOfObjectives][numberOfVariables];
            b[0][0] = 5.5;
            b[0][1] = 5.5;
            b[1][0] = 2.7;
            b[1][1] = 8.1;
            b[2][0] = 9.9;
            b[2][1] = 1.2;

            //Objective 1.
            f[0] = b[0][0] * x[0] + b[0][1] * x[1];

            //Objectives.
            for (int i = 1; i < numberOfObjectives; i++) {
                f[i] = 0;
                for (int j = 0; j < numberOfVariables; j++) {
                    f[i] += b[i][j] * x[j];
                }
            }

            //Constraints:
            //constraints that are satisfied have a value of zero; violated
constraints have
            //non-zero values (both positive and negative).
            for (int i = 0; i < numberOfConstraints; i++) {
                double sum = 0.0;
                for (int j = 0; j < numberOfVariables; j++) {
                    sum += x[j];
                }
                if (sum <= 50.0) {
                    g[i] = 0.0;
                } else {
                    g[i] = sum - 50.0;
                }
            }

            //Negate the objectives since Knapsack is maximization.
            solution.setObjectives(Vector.negate(f));
            solution.setConstraints(g);
        }

        @Override
        public int getNumberOfConstraints() {
            return numberOfConstraints;
        }

        @Override
        public int getNumberOfObjectives() {
            return numberOfObjectives;
        }

        @Override
        public int getNumberOfVariables() {
            return numberOfVariables;
        }

    }


    // 2.1 Create a class for excel writing
    private static void writeXLSX(boolean flag, Sheet sheet, int row, int
cell, Object value){
           Row rowIn = sheet.getRow(row);
           if(rowIn == null) {
               rowIn = sheet.createRow(row);
           }
           Cell cellIn = rowIn.getCell(cell);
           if(cellIn == null) {
               cellIn = rowIn.createCell(cell);
           }

           if(value==null){
               cellIn.setCellValue("");
           }else{
            if (flag) {
                cellIn.setCellValue(Double.valueOf(value.toString()));
            } else {
                cellIn.setCellValue(value.toString());
            }

           }
    }

    public static void main(String[] args) {
    // 2.2.1 Create Excel workbook
XSSFWorkbook workBook = new XSSFWorkbook();
// 2.2.2 Create Excel sheets by different iterations
XSSFSheet sheet1 = workBook.createSheet("Iteration");

        for (int k = 0; k < 3; k++) {
            int iteration = (int) pow(10, k + 1);
            System.out.println("Iteration: " + iteration);
            NondominatedPopulation result = new Executor()
                    .withProblemClass(MO.class
                    )
                    .withAlgorithm("NSGAII")
                    .withMaxEvaluations(iteration)
                    .withProperty("populationSize", 5000)
                    .run();

            // 2.2.4 Read solutions
            for (int m = 0; m < result.size(); m++) {
                Solution solution = result.get(m);
                int[] x = EncodingUtils.getInt(solution);
                double[] objectives = solution.getObjectives();

                //Negate objectives to return them to their maximized form.
                objectives = Vector.negate(objectives);

                //2.2.5 Print results

                System.out.println("Num of Solutions: "+ result.size());
                System.out.println("Solution " + (m + 1) + ":");
                System.out.print("    Obj 1: " + objectives[0]);
                System.out.print("    Obj 2: " + objectives[1]);
                System.out.println("    Obj 3: " + objectives[2]);
                System.out.println("    Con 1: " +
solution.getConstraint(0));
                   for(int j=0;j<x.length;j++){
                   System.out.print("    Var " + (j+1) + ":"  + x[j]);

               }
                System.out.println();


                //2.2.6 Export results to Excel sheets by different
iterations
                if (k == 2) {
                 // Create Title Row in Excel
                writeXLSX(false, sheet1, 0, 0, "Solution");
                writeXLSX(false,sheet1, 0, 1, "Obj_1");
                writeXLSX(false,sheet1, 0, 2, "Obj_2");
                writeXLSX(false,sheet1, 0, 3, "Obj_3");
                writeXLSX(false,sheet1, 0, 4, "Con_1");
                     for(int n=5; n<x.length+5; n++){
                    writeXLSX(false, sheet1, 0, n, "Var_"+(n-4));
                         }
                     // create data input row in excel
                    writeXLSX(true, sheet1, m+1, 0, m+1);
                    writeXLSX(true, sheet1, m+1, 1, objectives[0]);
                    writeXLSX(true, sheet1, m+1, 2, objectives[1]);
                    writeXLSX(true, sheet1, m+1, 3, objectives[2]);
                    writeXLSX(true, sheet1, m+1, 4,
solution.getConstraint(0));

                    for(int n=0; n<x.length; n++){
                    writeXLSX(true, sheet1, m+1, n+5, x[n]);
                    }
                }




                try{
                FileOutputStream fileOut = new
FileOutputStream("E:\\Andrea.xlxs");
                workBook.write(fileOut);
                fileOut.close();
                } catch(FileNotFoundException e){
                e.printStackTrace();
                } catch(IOException e){
                e.printStackTrace();
                }

            }

        }
    }
}


Thanks and regards,
Naomi

**Comment by dhadka** [comment]
Hi Naomi,

A couple of things you could try.  First, I would recommend using the binary integer encoding, which will likely work better on problems like this:

```java

public class Andre {

	public static class MO extends AbstractProblem {

		private int numberOfVariables;
		private int numberOfObjectives;
		private int numberOfConstraints;

		public MO() {
			super(2, 3, 1);
			numberOfVariables = 2;
			numberOfObjectives = 3;
			numberOfConstraints = 1;
		}

		public Solution newSolution() {
			Solution solution = new Solution(getNumberOfVariables(),
					getNumberOfObjectives(), getNumberOfConstraints());

			for (int i = 0; i < getNumberOfVariables(); i++) {
				solution.setVariable(i, EncodingUtils.newBinaryInt(0, 30));
			}

			return solution;
		}

		public void evaluate(Solution solution) {
			int[] x = EncodingUtils.getInt(solution);
			double[] f = new double[numberOfObjectives];
			double[] g = new double[numberOfConstraints];

			double[][] b = new
					double[numberOfObjectives][numberOfVariables];
			b[0][0] = 5.5;
			b[0][1] = 5.5;
			b[1][0] = 2.7;
			b[1][1] = 8.1;
			b[2][0] = 9.9;
			b[2][1] = 1.2;

			//Objective 1.
			f[0] = b[0][0] * x[0] + b[0][1] * x[1];

			//Objectives.
			for (int i = 1; i < numberOfObjectives; i++) {
				f[i] = 0;
				for (int j = 0; j < numberOfVariables; j++) {
					f[i] += b[i][j] * x[j];
				}
			}

			//Constraints:
			//constraints that are satisfied have a value of zero; violated constraints have
			//non-zero values (both positive and negative).
			for (int i = 0; i < numberOfConstraints; i++) {
				double sum = 0.0;
				for (int j = 0; j < numberOfVariables; j++) {
					sum += x[j];
				}
				if (sum <= 50.0) {
					g[i] = 0.0;
				} else {
					g[i] = sum - 50.0;
				}
			}

			//Negate the objectives since Knapsack is maximization.
			solution.setObjectives(Vector.negate(f));
			solution.setConstraints(g);
		}

		public int getNumberOfConstraints() {
			return numberOfConstraints;
		}

		public int getNumberOfObjectives() {
			return numberOfObjectives;
		}

		public int getNumberOfVariables() {
			return numberOfVariables;
		}

	}
```

Second, I would recommend using a smaller population size.  With a population size of 100, I can consistently get 9 points:

```java
		int iteration = 100000l
		System.out.println("Iteration: " + iteration);
		NondominatedPopulation result = new Executor()
				.withProblemClass(MO.class)
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(iteration)
				.withProperty("populationSize", 100)
				.run();

Solution 1:
    Obj 1: 275.0    Obj 2: 253.8    Obj 3: 303.59999999999997
    Con 1: 0.0
    Var 1:28    Var 2:22
Solution 2:
    Obj 1: 275.0    Obj 2: 248.4    Obj 3: 312.3
    Con 1: 0.0
    Var 1:29    Var 2:21
Solution 3:
    Obj 1: 275.0    Obj 2: 280.8    Obj 3: 260.1
    Con 1: 0.0
    Var 1:23    Var 2:27
Solution 4:
    Obj 1: 275.0    Obj 2: 270.0    Obj 3: 277.5
    Con 1: 0.0
    Var 1:25    Var 2:25
Solution 5:
    Obj 1: 275.0    Obj 2: 264.59999999999997    Obj 3: 286.20000000000005
    Con 1: 0.0
    Var 1:26    Var 2:24
Solution 6:
    Obj 1: 275.0    Obj 2: 259.2    Obj 3: 294.90000000000003
    Con 1: 0.0
    Var 1:27    Var 2:23
Solution 7:
    Obj 1: 275.0    Obj 2: 291.59999999999997    Obj 3: 242.7
    Con 1: 0.0
    Var 1:21    Var 2:29
Solution 8:
    Obj 1: 275.0    Obj 2: 286.2    Obj 3: 251.4
    Con 1: 0.0
    Var 1:22    Var 2:28
Solution 9:
    Obj 1: 275.0    Obj 2: 275.4    Obj 3: 268.8
    Con 1: 0.0
    Var 1:24    Var 2:26
```

The search space here is small enough that we can brute force it:

```java

		MO mo = new MO();
		NondominatedPopulation bruteForce = new NondominatedPopulation();
		for (int i = 0; i < 30; i++) {
			for (int j = 0; j < 30; j++) {
				Solution solution = mo.newSolution();
				EncodingUtils.setInt(solution, new int[] { i, j });
				mo.evaluate(solution);
				
				bruteForce.add(solution);
			}
		}
```

You'll see the same 9 solutions from the brute force.  

If you're expecting to see other solutions at the extremes of the objectives, I would check to make sure they are non-dominated against the 9 solutions above and do not violate the constraints.  While you would expect extreme points to show up in the Pareto set, they must also be feasible.  (Please correct me if my analysis above is wrong).

You could try exploring other algorithms to see if they provide any different results than NSGA-II.  With everything else equal, I would expect a single-objective formulation to perform better than the multiobjective version.  This is usually because you're introducing assumptions in the single-objective formulation (e.g., weights) and focusing on only a subproblem of the multi-objective formulation.  This is partly why decomposition algorithms (MOEA/D for example) have been successful.

**Comment by Naomilicious** [comment]
Hi David,

newBinaryInt(0, 30) is not available in EncodingUtils so I tried newInt(0, 30) and it works: it found the three extreme points of the three objective functions receptively. 

Then I migrated this sample test into my actual problem, which increases the number of variables from two to 388. The parameters b [] [] are read from excel. The problem structure is same, still three linear objective functions, one equality constraint. Results are so weird that all the non-dominated solutions MOEA found are clustered in the center of the Pareto frontier surface. The extreme points (which are also belong to the non-dominated solutions) as well as the non-dominated solutions that close to the end of axes of each objective functions are missing (regardless changing popsize, iteration number and algorithm).

Here I attached the java codes and file I compiled (how can I send you the original file?). It is very appreciated that if you can help me to look at it and give me some hints in terms of how I can find most of the non-dominated solutions (at least include extreme points and several alternative points)

`public class CopyOfNaomiTest {

	    public static class MO extends AbstractProblem {

	        private int numberOfVariables;
	        private int numberOfObjectives;
	        private int numberOfConstraints;

	        public MO() {
	            super(388, 3, 1);
	            numberOfVariables = 388;
	            numberOfObjectives = 3;
	            numberOfConstraints = 1;
	        }

	        public Solution newSolution() {
	            Solution solution = new Solution(getNumberOfVariables(),
	                    getNumberOfObjectives(), getNumberOfConstraints());

	            for (int i = 0; i < getNumberOfVariables(); i++) {
	                solution.setVariable(i, EncodingUtils.newInt(0, 20));
	            }

	            return solution;
	        }

	        public void evaluate(Solution solution) {
	            int[] x = EncodingUtils.getInt(solution);
	            double[] f = new double[numberOfObjectives];
	            double[] g = new double[numberOfConstraints];

	            double[][] b = new
	                    double[numberOfObjectives][numberOfVariables];
	          
	            //Read parameters from Excel
	            ReadMetric data = new ReadMetric();
	            data.Read();
	            data.InputMetric();
	            
	            //Set Parameters for Objective functions
	            for(int i=0;i<numberOfVariables;i++){
	            	b[0][i]=data.b0[i];
	            	b[1][i]=data.b1[i];
	            	b[2][i]=data.b2[i];
	            }

	            //Objectives
	            for (int i = 0; i < numberOfObjectives; i++) {
	                f[i] = 0;
	                for (int j = 0; j < numberOfVariables; j++) {
	                    f[i] += b[i][j] * x[j];
	                }
	            }

	            //Constraints:
	            //constraints that are satisfied have a value of zero; violated constraints have
	            //non-zero values (both positive and negative).
	            for (int i = 0; i < numberOfConstraints; i++) {
	                double sum = 0.0;
	                for (int j = 0; j < numberOfVariables; j++) {
	                    sum += x[j];
	                }
	                if (sum <= 458.0) {
	                    g[i] = 0.0;
	                } else {
	                    g[i] = sum - 458.0;
	                }
	            }

	            //Negate the objectives since Knapsack is maximization.
	            solution.setObjectives(Vector.negate(f));
	            solution.setConstraints(g);
	        }

	        public int getNumberOfConstraints() {
	            return numberOfConstraints;
	        }

	        public int getNumberOfObjectives() {
	            return numberOfObjectives;
	        }

	        public int getNumberOfVariables() {
	            return numberOfVariables;
	        }
	    }


	    
	    
	    public static void main(String[] args) {
	    	int iteration = 100000;
	    	System.out.println("Iteration: " + iteration);
	    	NondominatedPopulation result = new Executor()
	    	        .withProblemClass(MO.class)
	    	        .withAlgorithm("NSGAII")
	    	        .withMaxEvaluations(iteration)
	    	        .withProperty("populationSize", 500)
	    	        .run();
	    
	    
	 // 2.2.4 Read solutions
        for (int m = 0; m < result.size(); m++) {
            Solution solution = result.get(m);
            int[] x = EncodingUtils.getInt(solution);
            double[] objectives = solution.getObjectives();

            //Negate objectives to return them to their maximized form.
            objectives = Vector.negate(objectives);
            
            //2.2.5 Print results
            
            System.out.println("Num of Solutions: "+ result.size());
            System.out.println("Solution " + (m + 1) + ":");
            System.out.print("    Obj 1: " + objectives[0]);
            System.out.print("    Obj 2: " + objectives[1]);
            System.out.println("    Obj 3: " + objectives[2]);
            System.out.println("    Con 1: " + solution.getConstraint(0));
               for(int j=0;j<x.length;j++){
               System.out.print("    Var " + (j+1) + ":"  + x[j]);                
           } 
            System.out.println();
}
	    }
	    
	 
	    
}
`

Here are the ReadMetric class:
`public class ReadMetric {
	static List<Parameter> results = new ArrayList<Parameter>();
	static final int num=388;
// define Parameters
				// Parameter 1: 
				public double [] b0;
				// Parameter 2: 
			   public  double [] b1;
				//Parameter 3: 
				public double [] b2;

// Read Parameters from Excel to Java List
	public void Read(){
		try {
			//Find the location of the file
			FileInputStream file = new FileInputStream(new File("E:"+File.separator+"ua2015"+File.separator+"NGBRMetrics.xlsx"));
			
			//Get the workbook instance for XLSX file
			XSSFWorkbook workbook = new XSSFWorkbook(file);
			
			//Get first sheet from the workbook
			XSSFSheet sheet = workbook.getSheetAt(0);
			
			//Iterate through each rows from first sheet
			Iterator<Row> rowIterator = sheet.iterator();
			while(rowIterator.hasNext()){
				Row row =rowIterator.next();
				
				//For each row, iterate through each columns
				Iterator<Cell> cellIterator = row.cellIterator();
				while (cellIterator.hasNext()){
					Cell cell = cellIterator.next();
					
					//Check data type in excel cell and read cell and add that into Parameter list
					switch(cell.getCellType()){
					case Cell.CELL_TYPE_NUMERIC:
						//System.out.print(cell.getNumericCellValue()+"\n");
						results.add(new Parameter(String.valueOf(cell.getNumericCellValue())));
						break;
					case Cell.CELL_TYPE_STRING:
						//System.out.print(cell.getStringCellValue()+"\n");
						results.add(new Parameter(cell.getStringCellValue()));
						break;
					}
				}
			}
			file.close();
			workbook.close();
			//for(Parameter data : results) {
			//System.out.println(data.getValue());
				
			//}
		}catch (FileNotFoundException e){
			e.printStackTrace();
		}catch (IOException e){
			e.printStackTrace();
		}
}

//Input Excel value to Parameters
		public void InputMetric() {
			int i=0;
			int j=3; // ignore the first row 'title'
			
			b0=new double [num];
			b1=new double [num];
			b2=new double [num];
			for (i=0,j=3;j<1164;i++,j=j+3){
				b0[i]=Double.valueOf(results.get(j).getValue());
				b1[i]=Double.valueOf(results.get(j+1).getValue());
				b2[i]=Double.valueOf(results.get(j+2).getValue());
				
			}
			results.clear();
			}
}`

And the Parameter Class:
`public class Parameter {
		private String value;

		public Parameter(String value) {
			super();
			this.value = value;
		}

		public String getValue() {
			return value;
		}

		public void setValue(String value) {
			this.value = value;
		}
	}`

I also attached the excel file regarding the 388*3 parameters
[NGBRMetrics.xlsx](https://github.com/MOEAFramework/MOEAFramework/files/168251/NGBRMetrics.xlsx)
