### ISSUE TITLE
How can I set an initial population and a seed while continuing to use Executor and Instrumenter classes?

### ISSUE THREAD

**Issue by RenanJViana** [MOEAFramework/MOEAFramework#370]
Hi David,
I am using the Executor and Instrumenter classes to collect approximation sets over time. I created a class to represent my custom problem witch extends of Problem class. To ensure a fair comparison between the algorithms used, I would like to use the same initial population and the same seed for all algorithms in each run. How can I set an initial population and a seed while continuing to use Executor and Instrumenter classes? Thanks in advance.

**Comment by dhadka** [comment]
Hi,

There isn't a way to set the initial population through the `Executor` class.

If you're just interested in running each algorithm with the same initial random population, the seed should work in most cases.  Here's a code snippet we can use to confirm the initial populations are all identical:

```java

import java.util.BitSet;

import org.moeaframework.Executor;
import org.moeaframework.core.NondominatedPopulation;
import org.moeaframework.core.PRNG;
import org.moeaframework.core.Population;
import org.moeaframework.core.Solution;

public class CompareInitialPopulationExample {

	public static void main(String[] args) {
		long seed = 123456789L;
		String problem = "DTLZ2_2";
		String[] algorithms = new String[] { "NSGAII", "GDE3", "MOEA/D", "OMOPSO" };
		
		for (String algorithm1 : algorithms) {
			for (String algorithm2 : algorithms) {
				PRNG.setSeed(seed);
					
				NondominatedPopulation result1 = new Executor()
						.withAlgorithm(algorithm1)
						.withProblem(problem)
						.withMaxEvaluations(1) // run initialization only
						.run();
					
				PRNG.setSeed(seed);
					
				NondominatedPopulation result2 = new Executor()
						.withAlgorithm(algorithm2)
						.withProblem(problem)
						.withMaxEvaluations(1) // run initialization only
						.run();
				
				System.out.println(algorithm1 + " - " + algorithm2 + " = " + equals(result1, result2));
			}
		}
	}
	
	public static boolean equals(Population p1, Population p2) {
		if (p1.size() != p2.size()) {
			return false;
		}

		BitSet matched1 = new BitSet(p1.size());
		BitSet matched2 = new BitSet(p2.size());

		for (int i = 0; i < p1.size(); i++) {
			for (int j = 0; j < p2.size(); j++) {
				if (equals(p1.get(i), p2.get(j))) {
					matched1.set(i);
					matched2.set(j);
				}
			}
		}
		
		return (matched1.cardinality() == p1.size()) && (matched2.cardinality() == p2.size());
	}
	
	public static boolean equals(Solution s1, Solution s2) {
		if (s1.getNumberOfVariables() != s2.getNumberOfVariables()) {
			return false;
		}

		if (s1.getNumberOfObjectives() != s2.getNumberOfObjectives()) {
			return false;
		}

		if (s1.getNumberOfConstraints() != s2.getNumberOfConstraints()) {
			return false;
		}

		for (int i = 0; i < s1.getNumberOfVariables(); i++) {
			if (!s1.getVariable(i).equals(s2.getVariable(i))) {
				return false;
			}
		}

		for (int i = 0; i < s1.getNumberOfObjectives(); i++) {
			if (Math.abs(s1.getObjective(i) - s2.getObjective(i)) >= 0.00000001) {
				return false;
			}
		}

		for (int i = 0; i < s1.getNumberOfConstraints(); i++) {
			if (Math.abs(s1.getConstraint(i) - s2.getConstraint(i)) >= 0.00000001) {
				return false;
			}
		}

		return true;
	}

}
```

If you want to initialize the population with some set of known good solutions, we have to construct the algorithm directly and provide the initialization method:

```java
		Problem problem = new DTLZ2(2);
		
		Solution solutionA = problem.newSolution();
		EncodingUtils.setReal(solutionA, new double[] { 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 });
		
		Solution solutionB = problem.newSolution();
		EncodingUtils.setReal(solutionB, new double[] { 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 });
		
		NSGAII algorithm = new NSGAII(problem);	
		algorithm.setInitialization(new InjectedInitialization(problem, solutionA, solutionB));
		algorithm.run(100);
		
		algorithm.getResult().display();
```


Hope this helps!
David

**Comment by RenanJViana** [comment]
Hi David, thanks for the explanation. I believe that will works for me. But I have another question. I defined the Instrumenter class object to retrieve the approximation set every 10.000 objective function evaluations. But I also need the initial population. Is there any way to get it?

**Comment by dhadka** [comment]
The code isn't setup to get the initial population.

Are you running this experiment using the MOEA Framework source code?  If so, I think you can tweak `src/org/moeaframework/algorithm/PeriodicAction.java` and change the behavior of the `step()` method.

For example, below I've added `lastInvocation == 0` to have it collect the data on the very first call - which should get you the initial population.

```java

		if (frequencyType.equals(FrequencyType.EVALUATIONS)) {
			if (lastInvocation == 0 || (getNumberOfEvaluations() - lastInvocation) >= frequency) {
				doAction();
				lastInvocation = getNumberOfEvaluations();
			}
		} else if (frequencyType.equals(FrequencyType.STEPS)) {
			iteration++;
			
			if (lastInvocation == 0 || (iteration - lastInvocation) >= frequency) {
				doAction();
				lastInvocation = iteration;
			}
		} else {
			throw new IllegalStateException("unsupported frequencyType: " + frequencyType);
		}
```

One note...this will offset all your collection points by the population size.  So instead of getting the data at round numbers, like `10000, 20000, 30000, ...`, it'll be `100, 10100, 20100, 30100, ...`.

(I'm planning to add this functionality, but I'd recommend making this change yourself so you're not waiting on me.)

**Comment by RenanJViana** [comment]
Apparently, everything is working correctly. One last question, is there a way to collect the current population instead of the approximation set using the Instrumenter and Accumulator? Thanks to your help I am able to carry out my experiments using the MOEA Framework.

**Comment by dhadka** [comment]
Yes, I apparently never added a convenience method for it,  but the
following should work:

instrumenter.attach(new PopulationCollector())
