### ISSUE TITLE
How to handle a large number of variables in MOEA using the least number of computing iterations 

### ISSUE THREAD

**Issue by Naomilicious** [MOEAFramework/MOEAFramework#38]
Hi David,

I found as the number of variables increases, the number of iterations/evaluations that are needed to generate an approximation of the Pareto front rises dramatically. Because my problem has 388 variables and three objectives, I have tried 150,000,000 iterations using NSGAII, but the results were still not reaching at the Pareto front. In addition, there is a limit of iterations in MOEA (probably 2 billion). I tried to run 2 billion iterations in MOEA, but it was too slow that results cannot be generated within 2 days*24 hours therefore I stopped the program.

By searching literature, it is found that the current practice of GA is typically focusing on problems with a relatively low number of decision variables (normally no more than 30). Using cooperative co-evolution may reduce the number of evaluation for large scale multi-objective optimization problem. Here I attached a literature proposed a cooperative co-evolution for GDE3. I am wondering how I can do cooperative co-evolution using MOEA, probably by adding some codes in NSGAII or GDE3 algorithms, in order to subdivide the decision variables space and separate sub-populations.
[Luis Miguel Antonio and Carlos A. Coello Coello.pdf](https://github.com/MOEAFramework/MOEAFramework/files/171112/Luis.Miguel.Antonio.and.Carlos.A.Coello.Coello.pdf)

**Comment by dhadka** [comment]
You can certainly modify or extend the classes (in `org/moeaframework/algorithms`) to implement co-evolution.  I would also recommend upgrading to the latest version (2.9) and using the binary integer encoding.  It searches discrete spaces more effectively than the standard integer encoding (which encodes integers as real-values and will produce many duplicate values - e.g., 2.0 through 2.999 all convert to 2).  

In your problem, the state space size is 20^388 = 6.3 * 10^503, which is larger than the number of atoms in the known universe!  Of course, it's probably not necessary to search this entire space, but it gives an idea of the potential difficulty.

**Comment by Naomilicious** [comment]
Hi David,

Yes, I have already upgraded MOEA to version 2.9 and used binary integer
encoding.
Could you tell me more about how to do co-evolution in
org/moeaframework/algorithms. Thanks.

Thanks and regards,
Naomi

**Comment by Naomilicious** [comment]
In addition, how to change the initial population?

Thanks and regards,
Naomi

**Comment by dhadka** [comment]
You may find it easier to use an existing library that specializes in co-evolution, such as http://www.cs.put.poznan.pl/mszubert/projects/cecj.html.  The MOEA Framework doesn't have any co-evolution support built-in, so someone would need to write the necessary code.

One would essentially need to replicate the algorithm descriptions from the cited paper.  For example, instead of having a single population in NSGA-II and GDE3, they would need to create species (consisting of one or more variables), each of which resides in its own population.  Additionally, since each species is incomplete (only defines one or more variables), they would need to combine a solution with others so that all variables are defined.  There are several ways of doing this combination, each with its own advantages and disadvantages (see the references in the paper you cited for details).  This is also why I recommend the library above since it provides all these options.

**Comment by Naomilicious** [comment]
Thank you David. I am looking at the library now.  BTW, can you tell me how
to specify the initial population myself in MOEA?

Thanks and regards,
Naomi

**Comment by dhadka** [comment]
When using the `Executor`, you can set the population size using the `"populationSize"` parameter, generally.  See [Appendix A in the Beginner's Guide](https://github.com/MOEAFramework/MOEAFramework/releases/download/v2.9/MOEAFramework-2.9-BeginnersGuidePreview.pdf) for a list of available parameters and their descriptions.

If using the Java classes (i.e., calling the constructors directly), the population size is typically controlled by the `Initialization` class that creates the initial population.  If you look at [StandardAlgorithms.java](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/StandardAlgorithms.java), which is a good place to look when considering creating custom algorithms, you'll see:

```java

		int populationSize = (int)properties.getDouble("populationSize", 100);
		Initialization initialization = new RandomInitialization(problem, populationSize);
```

where it's reading the `"populationSize"` parameter, giving the default of 100, and setting up the initialization method.  Again, please refer to Appendix A in the Guide to see the available parameters, as some algorithms may have other parameters controlling the population size (e.g., epsilon)

**Comment by Naomilicious** [comment]
Hi David,

Thank you for the information. I've got results very close to the true
Pareto front by running GDE3 with 2 billion iterations in MOEA. However, 2
billion iterations are the upper limit that I cannot further increase the
value. I want to use/reload the results of the 388 variables as the initial
population in the GDE3 algorithm and run the algorithm again, probably I'll
get the true front within few iterations. Can you tell me how I can change
the initialization class in order to do this step?



Thanks and regards,
Naomi

**Comment by Naomilicious** [comment]
How can I change this codes `solution.getVariable(j).randomize()` in order to set variables' values using my own data.

```
@Override
	public Solution[] initialize() {
		Solution[] initialPopulation = new Solution[populationSize];

		for (int i = 0; i < populationSize; i++) {
			Solution solution = problem.newSolution();

			for (int j = 0; j < solution.getNumberOfVariables(); j++) {
				solution.getVariable(j).randomize();
			}

			initialPopulation[i] = solution;
		}

		return initialPopulation;
	}
```
