### ISSUE TITLE
NormalBoundryDivision class can't handle `divisions` as Double,

### ISSUE THREAD

**Issue by Lenkense** [MOEAFramework/MOEAFramework#384]
I'm currently using Evaluator cli tool for sensibility analysis. When I try to probe `divisions` parameter for sensitivity analysis I get a `NumberFormatException` claiming that my values are passed as floating-points. To be precise, I get an error saying that I have provided string `5.0`. However my inputfile clearly has a `5`. From a similar log message from parameter `populationSize` I can see that when a similar exception is thrown, the value is casted as `int`. This is in line 190 of `ConfigurationUtils.java`. However, this method is not used by `NormalBoundryDivision.java` to get parameter `divisions` leading to an exception that's not properly handled. This issue happens with two multi-objective algorithms, both NSGA-III and DBEA. 

Has anyone else reproduced this issue?

**Comment by dhadka** [comment]
Hi @Lenkense, sorry you're experiencing this issue.

Are you running or building the MOEA Framework from its source code?  If so, you could quickly fix this by editing https://github.com/MOEAFramework/MOEAFramework/blob/0bf21d9a2047e9639552f43f613a20468c5dfae1/src/org/moeaframework/util/weights/NormalBoundaryDivisions.java#L148-L164

and changing

```
properties.getInt(...)
```

to

```
(int)properties.getDouble(...)
```

I'll work on a fix, but can't get to it immediately.  So ☝ is your best option to get unblocked.

**Comment by Lenkense** [comment]
Currently I'm using the library in a bigger project. Due to that, I'm using maven to handle dependencies so I never compile the code or just execute it.
