### ISSUE TITLE
Executor withAlgorithm using my Algorithm instance instead of String name

### ISSUE THREAD

**Issue by jabiercoding** [MOEAFramework/MOEAFramework#387]
In the Executor class, for the Problem we can use by name or by instance. However, for the Algorithm we can only use by String name. I have an IBEA where I added my own Variations, so it will be much better if I can use executor.withAlgorithm(ibea)... Is there a workaround? Can the API of Executor include also Algorithm instances? Thanks.

**Comment by dhadka** [comment]
The `runSeeds(...)` capability, and possibly others, prevents using an algorithm instance directly, as each seed needs to construct a new instance of the algorithm.

Depending on what you're trying to do, it might make sense to create `IBEA` directly using its constructor.  You can then call `setVariation` to configure it.  See https://github.com/MOEAFramework/MOEAFramework/blob/b3b03fa3a5686fccc086eab3b2342cae250eb1f2/examples/Example3.java#L39 for an example.

**Comment by jabiercoding** [comment]
Thanks David for your response. Actually this is what I did. I instantiated IBEA, added my variations, and then I want to use instrumenter and executor but I cannot do executor.withAlgorithm(my ibea instance) as it expects always a String. See the arrow. I can only add "IBEA" as parameter, and not the modified ibea instance I created.

```
IBEA ibea = new IBEA(problem);
Variation crossover = new MyCrossover();
Mutation mutation = new MyMutation();
Variation variations = new CompoundVariation(crossover, mutation);
ibea.setVariation(variations);
Instrumenter instrumenter = new Instrumenter();
instrumenter.withProblem(problem);
instrumenter.withFrequency(100);
instrumenter.attachElapsedTimeCollector();
	
Executor executor = new Executor();
executor.withProblem(problem);
executor.withMaxEvaluations(10000);
executor.withInstrumenter(instrumenter);
executor.withAlgorithm("IBEA"); <------------------------------------
executor.run();

instrumenter.getObservations().display();
```

**Comment by dhadka** [comment]
The following will let you use the instrumenter with an algorithm directly:

```java

Problem problem = new DTLZ2(2);
		
Variation crossover = new PCX();
Mutation mutation = new PM();
Variation variation = new CompoundVariation(crossover, mutation);

IBEA ibea = new IBEA(problem);
ibea.setVariation(variation);
		
Instrumenter instrumenter = new Instrumenter()
		.withProblem(problem)
		.withFrequency(100)
		.attachElapsedTimeCollector();
		
InstrumentedAlgorithm algorithm = instrumenter.instrument(ibea);
algorithm.run(10000);
algorithm.getObservations().display();
```

I subbed in PCX and PM for testing, but it should just work if you replace them with your custom operators.

**Comment by jabiercoding** [comment]
Thanks for the answer
