### ISSUE TITLE
The setComparator method in GeneticAlgorithm does not change the comparator in selection

### ISSUE THREAD

**Issue by chaoyi-studio** [MOEAFramework/MOEAFramework#394]
Hello, developers of MOEAFramework. I really like your framework and thank you for your contributions.

Recently I use GeneticAlgorithm, and when the setComparator method is called, the selection of comparators in the algorithm does not change. I believe this feature can be misunderstood by developers, such as the following example.

```
    GeneticAlgorithm algorithm = new GeneticAlgorithm(concurrentProblem);
    algorithm.setInitialization(new InjectedInitialization(concurrentProblem, initializedSolutions));
    algorithm.setInitialPopulationSize(populationSize);
    algorithm.setComparator(new LinearObjectiveComparator(weights));
    algorithm.setVariation(new CompoundVariation(
        new UniformCrossover(crossoverRate),
        new UM(mutatorRate)
    ));
```

In fact, the comparator in the algorithm runtime selection for this example is the default when the algorithm is initialized. Rather than  `LinearObjectiveComparator`.

My debugging results are attached here:

![image](https://github.com/MOEAFramework/MOEAFramework/assets/32929218/11f00432-273c-4cdc-b1a2-c1132b485b16)

**Comment by dhadka** [comment]
Thanks for reporting this.  This should be fixed on the `master` branch with commit https://github.com/MOEAFramework/MOEAFramework/commit/b6ab7ce9866eabeb1c66df7e8798fd5dc6a1fac0.  Calling `setComparator` will now update the comparator referenced by the `GeneticAlgorithm` and the `TournamentSelection` operator.

**Comment by dhadka** [comment]
Closing.  Version 3.10 is published with the fix.
