### ISSUE TITLE
Support email is down

### ISSUE THREAD

**Issue by meganbryson** [MOEAFramework/MOEAFramework#399]
Hi,
The support email on your website is down. Thought you may want to know :)

**Comment by dhadka** [comment]
Thanks for letting me know!  I think it broke a few months ago when the hosting provider changed their e-mail plan.

Filing an issue here is the best way to receive support moving forward.

Also, could you please point me to where you found the support e-mail?  The only two places I'm aware of are (1) the user manual PDF and (2) the Maven `pom.xml`.

**Comment by meganbryson** [comment]
It doesn't appear to be there now but looking at a photo I took on Sunday, it used to be on here too 
![72997696684__C77BF1E8-E9DD-4841-841F-A8C2A2450725](https://github.com/MOEAFramework/MOEAFramework/assets/72516063/d152d13e-b9d1-4cb5-8d30-267079680c29)

**Comment by dhadka** [comment]
Thank you!  I did remove that link recently.
