### ISSUE TITLE
FastPGA crashes when running on ZDT problems

### ISSUE THREAD

**Issue by Gan0k** [MOEAFramework/MOEAFramework#40]
Hi,

I just wanted to report that FastPGA crashes when running any of the ZDT problems (except ZDT5 since it uses binary variables) due to the use of TimSort on the new Java 7. When using the legacy sort algorithm, the issue is fixed. The problem arises from the class `jmetal.util.comparators.FPGAFitnessComparator` which does not adhere to the contract of the Comparator interface (for example, if `A > B` and `B > C`, `A > C` does not hold). 

I could not run MOEAFramework with a newer version of jMetal's jar. I also tried to crate a patch myself but I was not able to compile jMetal from source. 

The error outputted is the following:
```
Exception in thread "main" org.moeaframework.algorithm.AlgorithmException: Comparison method violates its general contract!
	at org.moeaframework.algorithm.jmetal.JMetalAlgorithmAdapter.step(JMetalAlgorithmAdapter.java:118)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:804)
	at org.moeaframework.Executor.runSeeds(Executor.java:709)
	at CompareDef.main(CompareDef.java:201)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:747)
	at java.util.TimSort.mergeAt(TimSort.java:483)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:426)
	at java.util.TimSort.sort(TimSort.java:223)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at java.util.Collections.sort(Collections.java:217)
	at jmetal.core.SolutionSet.sort(SolutionSet.java:109)
	at jmetal.metaheuristics.fastPGA.FastPGA.execute(FastPGA.java:133)
	at org.moeaframework.algorithm.jmetal.JMetalAlgorithmAdapter.step(JMetalAlgorithmAdapter.java:116)
	... 3 more
```

**Comment by dhadka** [comment]
Thanks for reporting this.  Since this is part of JMetal, it may take some time to isolate and fix the issue (or check if it's fixed in their latest version).  In the meantime, you can revert to the old merge sort by adding the following VM argument:

```
-Djava.util.Arrays.useLegacyMergeSort=true 
```

**Comment by Gan0k** [comment]
Thank you for the quick answer. The issue is not fixed in JMetal 4.5.2 (the newest version). I will try to report the bug to them.

**Comment by dhadka** [comment]
@Gan0k 

Can you please also post here the code you're running and your version of Java.  I've tried a few times and haven't been able to reproduce the error.  Thanks.

**Comment by Gan0k** [comment]
I just checked and the error happens only when I set 100 seeds in the Executor.

My java version is the following:
```
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

And running this code crashes consistently in my set-up:
https://gist.github.com/Gan0k/ae0e71fbed89d6b6363d

Using DTLZ4_2 with 100 seeds also crashes consistently.

**Comment by dhadka** [comment]
Thanks.  I was able to reproduce it.  It looks like it's caused when solutions are assigned the same rank and a crowding distance of Infinity.  Since you can't really compare two Infinity values (I believe Inf < Inf and Inf > Inf both return false in Java), it's causing the error.

Here's a fix that treats two solutions with the same rank and infinite crowding distances as having equal fitness.  https://gist.github.com/dhadka/0d008f3d161105c23633

I've also created a new JAR using JMetal 4.5.2 with the fix above.  Note that I haven't extensively tested this JAR, so use caution.
[JMetal-4.5.zip](https://github.com/MOEAFramework/MOEAFramework/files/182345/JMetal-4.5.zip)

**Comment by dhadka** [comment]
I take that back...I had to run it a few times but I eventually got the error again.  Still looking...

**Comment by dhadka** [comment]
@Gan0k 

On further inspection, a NaN for the fitness value appeared right before the error.  I assume this is the cause.  Inspecting JMetal's `FPGAFitness.java` class, the fitness values are calculated with:

```java

  public void fitnessAssign() {
    double [] strength    = new double[solutionSet_.size()];
    double [] rawFitness  = new double[solutionSet_.size()];  
    
    //Ranking  ranking  = new Ranking(solutionSet_);
    //Distance distance = new Distance();
    //distance.crowdingDistanceAsignament(ranking.getSubfront(0),
    //                                    problem_.getNumberOfObjectives());  
    
    for (int i = 0; i < solutionSet_.size(); i++) {
      if (solutionSet_.get(i).getRank()==0) {
        solutionSet_.get(i).setFitness(solutionSet_.get(i).getCrowdingDistance());
        //System.out.println(solutionSet_.get(i).getCrowdingDistance());
      }
    }
           
    //Calculate the strength value
    // strength(i) = |{j | j <- SolutionSet and i dominate j}|
    for (int i = 0; i < solutionSet_.size(); i++) {
      for (int j = 0; j < solutionSet_.size();j++) {
        if (dominance_.compare(solutionSet_.get(i),solutionSet_.get(j))==-1) {
          strength[i] += 1.0;
        } // if        
      } // for
    } // for
       
        
    //Calculate the fitness
    //F(i) = sum(strength(j) | i dominate j) - sum(strenth(j) | j dominate i)
    for (int i = 0;i < solutionSet_.size(); i++) {
      double fitness = 0.0;
      for (int j = 0; j < solutionSet_.size();j++) {
        int flag = dominance_.compare(solutionSet_.get(i),solutionSet_.get(j));
        if (flag == -1) { //i domiante j
          fitness += strength[j];
        }else if (flag==1) {
          fitness -= strength[j];
        } // if
      } // for
    } // for
            
  } // fitnessAsign    
```

You'll see the fitness gets set to the crowding distance:

```java

solutionSet_.get(i).setFitness(solutionSet_.get(i).getCrowdingDistance());
```

This is followed by two additional loops that calculate the strength and fitness, respectively, but note that the fitness value computed in the final loop is never assigned!  I assume this is another bug, but I'm not familiar enough with FastPGA.

As for where the NaN comes from, looking at JMetal's `Distance.java` class (lines 241-246):

```java

      for (int j = 1; j < size-1; j++) {
        distance = front.get(j+1).getObjective(i) - front.get(j-1).getObjective(i);
        distance = distance / (objetiveMaxn - objetiveMinn);
        distance += front.get(j).getCrowdingDistance();
        front.get(j).setCrowdingDistance(distance);
      } // for
```

If all of the i-th objective values are identical, then `distance == 0` and `objetiveMaxn - objetiveMinn == 0`, which will result in `distance / (objetiveMaxn - objetiveMinn)` producing `NaN`

**Comment by Gan0k** [comment]
Thank you very much!
Seeing this makes me wary of the implementation of FPGA and I think I will avoid using it for the moment. I will try later to ensure that it is implemented correctly.
