### ISSUE TITLE
Complications performing Saltelli analysis

### ISSUE THREAD

**Issue by Lenkense** [MOEAFramework/MOEAFramework#412]
I'm using DBEA and NSGAIII to optimize a problem with 2 objectives. I'm trying to perform a sensitivity analysis to pick the best parameters of my simulation. However, when I'm trying to create a reference set, rather than obtaining a Pareto set, I found only one optimal solution. Having only one optimal solution yields issues when trying to calculate metrics such as hypervolume, making sensitivity analysis impossible. What's the best approach in this cases? 

1. Should I pick the parameters that create this optimal solution for my simulation? 
2. Looking for a similar issue I found that sometimes, performing more evaluations solve this issue. Should I try that?
3. Toying around with CLI tools I found that entering negative numbers to the epsilon option `-e` selects the worst solutions rather than the optimal ones. This creates a solution sets that contains more than 1 solution, making analysis viable. However, I suspect this produces nonsense in the metrics, Am I wrong in this interpretation?
4. Are there any papers or references that suggest what to do in this cases?

Looking foward for your guidance.

**Comment by dhadka** [comment]
You are right that using negative epsilon values produces nonsense in the metrics.  I should add a check that prevents this 😄 

Performing more evaluations may help, depending if the solution you've found is already at or near the optimum.  It also depends on the structure of the problem.  Even though you may have multiple objectives, you won't necessarily get multiple Pareto optimal solutions if the objectives do not exhibit tradeoffs.  You can certainly try running for longer to see if that helps in any way.

The issue you're facing with having one solution when computing **normalized** metrics is that they need lower and upper bounds to perform the normalization.  With a single solution, the lower and upper bounds are the same.  For Hypervolume specifically, it does provide a constructor taking the lower and upper bounds:

https://github.com/MOEAFramework/MOEAFramework/blob/381a8e329da07f87ccfdedf1d04cc1c3caffd91e/src/org/moeaframework/core/indicator/Hypervolume.java#L82

If you do use this option, be sure to document what values you use, as the caclulated Hypervolume will be different if the bounds change.

It's also possible to compute **unnormalized** versions of these metrics, but those methods are not public currently...though a small code change can fix that.  Furthermore, some metrics like Spacing become meaningless when there's a single solution.

Happy to help further if you have questions or run into issues with any of these approaches!

**Comment by Lenkense** [comment]
Part of the problem is that I've been using CLI tool ResultFileEvaluator that performs metrics automatically without those bounds as inputs. Calling the class `Hypervolume.java` might require some additional coding on my side. I can make a copy of ResultFileEvaluator that doesn't use the class `Indicators.java` and add code manually to fix that, but I don't know if there's another solution. 

On questions 1. and 2. I had analyzed this problem with other approaches different from evolutionary computation. I have found a similar result, i. e., solutions don't show a trade-off like in Pareto sets. In that sense it seems I shouldn't run more evaluations, but I should consider picking one of the parameters that create the best solution. Would you agree on this conclusion?

**Comment by dhadka** [comment]
I belieave you can also set the min/max bounds in `moeaframework.properties`, and that should work with `ResultFileEvaluator`:

https://github.com/MOEAFramework/MOEAFramework/blob/381a8e329da07f87ccfdedf1d04cc1c3caffd91e/moeaframework.properties#L68-L72

Yes, if you're consistently seeing a single solution regardless of NFE or method, then I would concur with picking the parameter creating the best solution.

**Comment by dhadka** [comment]
Also, I'm not sure which version you're using, but I recently published verison 4.0.  Some of the CLI tools moved from `org.moeaframework.analysis.sensitivity` to `org.moeaframework.analysis.tools`.  If you do upgrade to the latest version, you will need to use the new paths.

**Comment by Lenkense** [comment]
I was trying to remember, `moeaframework.properties` is a simple text file that should be in the same path where I run `ResultFileEvaluator`, right?  `idealpt` is lower bound and `refpt` is upper bound. Did I get everything correct?

**Comment by dhadka** [comment]
Yes, it should be in the folder you're calling `java -claspath ... org.moeframework...` from.  And correct about the ideal and ref points.

**Comment by Lenkense** [comment]
Thanks for all the insights. One last thing I would like to look is how is Hypervolume calulated. For 2 objectives, is it calculated as the area under the curve of the Pareto set? In general, for N objectives, is it the hypervolume in a N dimensional space under the Pareto front?

**Comment by dhadka** [comment]
Yeah, that's a decent way to think of it.  I would just clarify that "under" is really the space between the Pareto front and a given reference point.  For problems being **minimized**, this reference point is typically located near the **maximum** objective values, so it ends up looking like the diagram below.

![Image](https://github.com/MOEAFramework/MOEAFramework/assets/2496211/a043776e-4f26-45a2-887a-455117958360)

Image from https://lopez-ibanez.eu/hypervolume

**Comment by Lenkense** [comment]
Now I have three additional questions:

1) In a problem being minimized, reference sets are maximums? Or did I just confused reference point in hypervolume calculation with reference sets?

2) Looking at `Indicators.java` I found out that these are the metrics calculatd by default.
```
			includeHypervolume();
		}

		includeGenerationalDistance();
		includeInvertedGenerationalDistance();
		includeAdditiveEpsilonIndicator();
		includeMaximumParetoFrontError();
		includeSpacing();
		includeContribution();
```

I believe I need to disable normalization for all those metrics too. Can that be done to with `moeaframework.properties`?

3) The name of my problem include the name of a xml file, "example.xml", Could the character `.` in the name of file be an issue for `moeaframework.properties`?

**Comment by dhadka** [comment]
1. Yes, reference sets and points are two different things.  Referece points are used in the calculation of hypervolume.  

2. I added some options last week to disable normalization or set your own bounds.  However, this is only available on the `master` branch at the moment, so you'd need to work from the source code (or build a `.jar` from the source code).  See https://github.com/MOEAFramework/MOEAFramework/blob/2a1a9c8d06bede37104ca3395fce96da6da09ea4/moeaframework.properties#L58-L72

3. Yes, the `.` in the name should be fine.

**Comment by dhadka** [comment]
Closing out this issue as there hasn't been any recent activity.  Please re-open or create a new issues if you have any further questions!
