### ISSUE TITLE
TSP from an adj list

### ISSUE THREAD

**Issue by meganbryson** [MOEAFramework/MOEAFramework#413]
Do you have an example program that uses the adj list feature in TSP? If you don't no worries, just thought I'd ask. I'm just having a hard time getting my pre-generated graph inputted and stored in edgedata.

**Comment by dhadka** [comment]
I originally wrote the TSP code here - https://github.com/dhadka/TSPLIB4J

That was a long time ago, but it links to http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp/ for datasets.  I don't know which, if any, use the adj list, but that would be the best location to find examples.

**Comment by meganbryson** [comment]
Thank you!

**Comment by dhadka** [comment]
@meganbryson That second link contains a Postscript file that has some more details on the formats:

![Image](https://github.com/MOEAFramework/MOEAFramework/assets/2496211/a4f37026-f372-46ca-bbf4-aca4df6be950)

So I think the format would look something like:

```
1 2 3 -1
2 1 3 4 -1
3 1 2 -1
4 2 -1
-1
```

to create a graph like:

```mermaid
graph LR
    1 <--> 2
    1 <--> 3
    2 <--> 3
    2 <--> 4
```
