### ISSUE TITLE
Looking for default parameter values for GDE3 algorithm

### ISSUE THREAD

**Issue by Naomilicious** [MOEAFramework/MOEAFramework#44]
Hi,

I am looking for the default parameter values for the GDE3 algorithm. I checked the API document from this website http://moeaframework.org/javadoc/org/moeaframework/algorithm/jmetal/JMetalAlgorithms.html, 
and only find these:
GDE3	Real*	populationSize, maxEvaluations, de.crossoverRate, de.stepSize

Can I know the default value in terms of the crossover rate, mutation rate, etc for GDE3?

Thanks.

**Comment by dhadka** [comment]
Check out Appendix A in the Beginner's Guide, available here: https://github.com/MOEAFramework/MOEAFramework/releases/download/v2.9/MOEAFramework-2.9-BeginnersGuidePreview.pdf

**Comment by Naomilicious** [comment]
Thank you, I found them.

Thanks and regards,
Naomi
