### ISSUE TITLE
Working with constraints

### ISSUE THREAD

**Issue by orennahum** [MOEAFramework/MOEAFramework#45]
Hi,

I have the following code implemented in the evaluation function.

if (iSumCapacities1 != m_iTotalDemand)
        {
            objSolution.setConstraint(iConstraintCount, iSumCapacities1);
        } else
        {
            objSolution.setConstraint(iConstraintCount, 0);
        }

How ever, when I check the result, I see that there are solutions in which the constraint is not met.

What am I doing wrong ?

Thanks,
Oren

**Comment by dhadka** [comment]
Hi,

Depending on the algorithm or if no feasible solutions were found during search, the results can include infeasible solutions.  It is a good practice to check [`solution.violatesConstraints()`](http://moeaframework.org/javadoc/org/moeaframework/core/Solution.html#violatesConstraints%28%29) to see if a solution is feasible.  You can find more information on handling constrained problems in Chapter 3 in the [Beginner's Guide to the MOEA Framework](https://github.com/MOEAFramework/MOEAFramework/releases/download/v2.9/MOEAFramework-2.9-BeginnersGuidePreview.pdf), particularly section 3.3.

Best Regards

**Comment by orennahum** [comment]
Thanks for the reply.
I have change the newSolution method such that it create a feasible solution. I have also changed the evaluate method that in case that the solution is not feasible, i change the value of the objectives to Integer.MAX_VALUE. However, I still get wrong solutions.

**Comment by PastelBelem8** [comment]
Changing it to Integer.MAX_VALUE does not solve your problem, as your algorithm is still wasting many evaluations in unfeasible areas of your solution space.
