### ISSUE TITLE
Hypervolume analysis of custom problems (Hypervolume always 0.0)

### ISSUE THREAD

**Issue by TheRealNebus** [MOEAFramework/MOEAFramework#47]
Hello,

I've been experimenting with the MOEA Framework to solve my own custom problem. I would like to compare different algorithms and configurations using the Hypervolume indicator but for some reason I always get a Hypervolume of 0.0.

I've tried using the default reference set, specifying my own reference set manually using the worst possible objective values and generating a reference set using one of the algorithms and exporting it like this:

```
 public void dumpReferenceSet(String path) throws IOException {
        ReferenceSetMerger ref_merger = new ReferenceSetMerger();
        for (int i = 0; i < results.size(); ++i) {
            ref_merger.add("Seed" + i, results.get(i));
        }
        PopulationIO.writeObjectives(new File(path), ref_merger.getCombinedPopulation());
    }
```

The code of the analysis procedure is the following:

```
public void analyzePopulations(Map<String, String> dataset, String ref_fname) throws IOException {
        Analyzer analyzer = new Analyzer()
                .withProblem(VMCWM_PROBLEM)
                .includeInvertedGenerationalDistance()
                .includeHypervolume()
                .withReferenceSet(new File(ref_fname))
                .showStatisticalSignificance();
        for (Iterator<String> it = dataset.keySet().iterator(); it.hasNext();) {
            String label = it.next(), file_path = dataset.get(label);
            analyzer.loadAs(label, new File(file_path));
        }
        analyzer.printAnalysis();
    }
```

The 'dataset' map stores paths to external files storing final populations generated by different algorithms and/or configurations. Those files are generated as follows:

```
public void dumpPopulation(String path) throws IOException {
        System.out.println("c Dumping non-dominated population to " + path);
        Analyzer analyzer = new Analyzer().withProblem(VMCWM_PROBLEM);
        analyzer.addAll("VMCwM", results);
        analyzer.saveAs("VMCwM", new File(path));
    }
```

Any idea what I might be doing wrong? Any help will be much appreciated.

Thank you in advance.

**Comment by dhadka** [comment]
A hypervolume of zero would mean that either (1) the final populations are empty, (2) none of the points lie within the hyperbox formed by the ideal and nadir points of the reference set, or (3) the points like on the boundary of this hyperbox.  Since you're creating the reference set by combining all sets, (2) shouldn't occur but (3) might.  If you could post one example of a final population and the reference set used, I could take a look at what's happening or see if it's a bug.  You can also e-mail them to support@moeaframework.org if you'd like to keep the files private.

For cases (2) and (3), it may help to use a custom reference point in the hypervolume calculation.  The master branch includes some recent additions for customizing the hypervolume calculation.  If you are using the latest code from the master branch, you can edit the `global.properties` file and utilize either of these two options:

```
## When calculating the reference point for the hypervolume calculation, the
## nadir point of the reference set is offset by the delta factor (e.g.,
## min + delta*(max-min)).  A small but non-zero delta is recommended.
#org.moeaframework.core.indicator.hypervolume_delta = 0.01

## A custom reference point can be defined for each problem.  Replace NAME with
## the value returned by Problem#getName().  Separate values with commas.
## The last value will be repeated as needed to define the reference point
## (e.g., the value 2 is expanded to (2, 2, ..., 2)).
#org.moeaframework.core.indicator.hypervolume_refpt.NAME= 2
```

**Comment by kalyanmoydeb** [comment]
I agree with Dave's comments on zero hypervolume -- most commonly it 
happens due to case (1).

Best,

Kalyan


On 10/05/16 10:44 AM, David Hadka wrote:
>
> A hypervolume of zero would mean that either (1) the final populations 
> are empty, (2) none of the points lie within the hyperbox formed by 
> the ideal and nadir points of the reference set, or (3) the points 
> like on the boundary of this hyperbox. Since you're creating the 
> reference set by combining all sets, (2) shouldn't occur but (3) 
> might. If you could post one example of a final population and the 
> reference set used, I could take a look at what's happening or see if 
> it's a bug. You can also e-mail them to support@moeaframework.org 
> <mailto:support@moeaframework.org> if you'd like to keep the files 
> private.
>
> For cases (2) and (3), it may help to use a custom reference point in 
> the hypervolume calculation. The master branch includes some recent 
> additions for customizing the hypervolume calculation. If you are 
> using the latest code from the master branch, you can edit the 
> |global.properties| file and utilize either of these two options:
>
> |## When calculating the reference point for the hypervolume 
> calculation, the ## nadir point of the reference set is offset by the 
> delta factor (e.g., ## min + delta*(max-min)). A small but non-zero 
> delta is recommended. 
> #org.moeaframework.core.indicator.hypervolume_delta = 0.01 ## A custom 
> reference point can be defined for each problem. Replace NAME with ## 
> the value returned by Problem#getName(). Separate values with commas. 
> ## The last value will be repeated as needed to define the reference 
> point ## (e.g., the value 2 is expanded to (2, 2, ..., 2)). 
> #org.moeaframework.core.indicator.hypervolume_refpt.NAME= 2 |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/MOEAFramework/MOEAFramework/issues/47#issuecomment-218179740>
>


-- 
Kalyanmoy Deb
Koenig Endowed Chair Professor
Department of Electrical & Computer Engineering
Professor of Computer Science & Engineering
Professor of Mechanical Engineering
Michigan State University
428 S. Shaw Lane, 2120 EB
East Lansing, MI 48824, USA
Office: 517 432 2144 Beacon: 517 884 2567 Cell: 517 930 0846
Fax: 517 353 1980
Email: kdeb@egr.msu.edu
http://www.egr.msu.edu/~kdeb

**Comment by TheRealNebus** [comment]
I've attached files with two different reference sets that I've used. ref.pf.txt is the reference set generated using one of the algorithms and ref2.pf.txt is a reference set with the origin (ideal point) and the point with the worst possible objective values.

In de-ex.pop.pf.txt are the objective values obtained with one of the algorithms for which I get a hypervolume of 0.0 using those reference sets. I generated de-ex.pop.pf.txt with the following code:

```
public void dumpPopulation(String path) throws IOException {
        System.out.println("c Dumping non-dominated population to " + path);
        Analyzer analyzer = new Analyzer().withProblem(VMCWM_PROBLEM);
        analyzer.addAll("VMCwM", results);
        analyzer.saveAs("VMCwM", new File(path));
        
        // TODO: REMOVE
        ReferenceSetMerger ref_merger = new ReferenceSetMerger();
        for (int i = 0; i < results.size(); ++i) {
            ref_merger.add("Seed" + i, results.get(i));
        }
        PopulationIO.writeObjectives(new File(path + ".pf"), ref_merger.getCombinedPopulation());
    }
```

If you need anything else just let me know.

[ref.pf.txt](https://github.com/MOEAFramework/MOEAFramework/files/257658/ref.pf.txt)
[ref2.pf.txt](https://github.com/MOEAFramework/MOEAFramework/files/257659/ref2.pf.txt)
[de-ex.pop.pf.txt](https://github.com/MOEAFramework/MOEAFramework/files/257660/de-ex.pop.pf.txt)

**Comment by dhadka** [comment]
What version are you using?  I tested with the latest (2.9) and am getting non-zero hypervolume:

```java

import java.io.File;
import java.io.IOException;

import org.moeaframework.Analyzer;
import org.moeaframework.analysis.sensitivity.ProblemStub;
import org.moeaframework.core.NondominatedPopulation;
import org.moeaframework.core.PopulationIO;

public class Test {
	
	public static void main(String[] args) throws IOException {
		Analyzer analyzer = new Analyzer()
				.withProblem(new ProblemStub(2))
				.withReferenceSet(new File("ref.pf.txt"))
				.includeHypervolume();
		
		analyzer.add("Test", new NondominatedPopulation(
				PopulationIO.readObjectives(new File("de-ex.pop.pf.txt"))));
		
		analyzer.printAnalysis();
	}

}
```

which produces the output:

```
Test:
    Hypervolume: 1.0
```

In this case, you get a hypervolume of 1.0 because at least one point in `de-ex.pop.pf.txt`, such as `4744.0271999999995 0.1560685342461309`, is dominating the entire reference set in `ref.pf.txt`.

---

When manually creating the reference set as you did in `ref2.pf.txt`, the bounds should be specified as:

```
18450.0 0.0
0.0 16.0016
```

The reference set is expected to be a set of non-dominated points.  With this change, I get a hypervolume of `0.7546514750865575`.

**Comment by dhadka** [comment]
@TheRealNebus 

I just committed some code to the master branch that will let you provide the ideal and reference points directly to the `Analyzer`.  This should make it easier to setup your analysis.

```java

import java.io.File;
import java.io.IOException;

import org.moeaframework.Analyzer;
import org.moeaframework.analysis.sensitivity.ProblemStub;
import org.moeaframework.core.NondominatedPopulation;
import org.moeaframework.core.PopulationIO;

public class Test {
	
	public static void main(String[] args) throws IOException {
		Analyzer analyzer = new Analyzer()
				.withProblem(new ProblemStub(2))
				.withIdealPoint(0.0, 0.0)
				.withReferencePoint(18450, 16.0016)
				.includeHypervolume();
		
		analyzer.add("Test", new NondominatedPopulation(
				PopulationIO.readObjectives(new File("de-ex.pop.pf.txt"))));
		
		analyzer.printAnalysis();
	}

}
```

**Comment by TheRealNebus** [comment]
I just tried executing the exact same code as given in your first comment after my last one, and it is still returning an Hypervolume of 0.0 for me. I am also using version 2.9, but I'm using the one in the maven repository.

**Comment by dhadka** [comment]
Ah, I also tried with the Maven build and got values of 0.  I'd suggest using the downloadable JARs until I can figure out what's going on.

**Comment by dhadka** [comment]
I made a new Maven build (version 2.9.1) that seems to work.  Please upgrade and try again.

**Comment by TheRealNebus** [comment]
I've just tried the new Maven build and it is working perfectly. Thank you very much for replying and fixing it so quickly.

Best regards.

**Comment by dhadka** [comment]
You're welcome.  Glad to hear it's working.  Closing ticket.
