### ISSUE TITLE
Where is the bit-flip mutation in GA?

### ISSUE THREAD

**Issue by pitangui-cristiano** [MOEAFramework/MOEAFramework#52]
Hello All,

Tried to use the bit-flip mutation, but I was unable to find it. In the manual it says that it is BF(double probability). But it could find the library of it...

Regards!

**Comment by dhadka** [comment]
The actual class is located at `src/org/moeaframework/core/operator/binary/BitFlip.java`.  `"bf"` is the name one would use with the Executor.  For example, here we configure the algorithm to use Half Uniform Crossover (HUX) and Bit Flip Mutation (BF):

```java

    new Executor()
        .withProperty("operator", "hux+bf")
        .withProperty("bf.rate", 0.01)
        ...
```

**Comment by pitangui-cristiano** [comment]
Hello David,

thanks for the answer. But how can I used it without the Executor? In my own method:

Variation variation =   new GAVariation(
		                   new HUX(1), 
		                   new BF(0.01));
Does not work.

**Comment by dhadka** [comment]
Sorry for the confusion.  Use `BitFlip` instead of `BF`:

```java

Variation variation = new GAVariation(
        new HUX(1.0),
        new BitFlip(0.01));
```

Best regards,
Dave

**Comment by pitangui-cristiano** [comment]
Thanks for the rapid support!

Regards!
