### ISSUE TITLE
Can MOEAFramework do 3D plot?

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#54]
Hi, I am wondering whether MOEAFramework can draw the results of 3 objective optimization problem in a 3D plot? If yes I don't need other tools to visualize the results.

**Comment by dhadka** [comment]
No it doesn't, only 2D.  I usually use Python with matplotlib.

**Comment by longmeili** [comment]
OK, thank you.Please close the issue then.

**Comment by dhadka** [comment]
Just to elaborate on this comment now that I'm back from my travels, I use Python with a combination of Numpy/Pandas and Matplotlib to generate 3D plots.  For example, if you want to plot a `Population` or `NondominatedPopulation`, first save the points to a file:

```java

NondominatedPopulation population = ...
PopulationIO.writeObjectives(new File("output.txt"), population);
```

The file will contain on each line the objectives for a solution.  For example:

```
0.0 1.0
0.25 0.75
0.5 0.5
0.75 0.25
1.0 0.0
```

Then read the contents using Numpy:

```python

import numpy as np

data = np.loadtxt("output.txt")
```

Finally follow the instructions [here](http://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html) to create the plot.  In addition to the 3 spatial axes, you can also control color, size, and transparency (using the alpha channel of the color).

Best Regards
