### ISSUE TITLE
Problem to maximize one and minimize other objective

### ISSUE THREAD

**Issue by pitangui-cristiano** [MOEAFramework/MOEAFramework#55]
Hello all,

I'm trying without success to minimize one objective while maximizing the other. Both objectives have restrictions in their values. So my code at the end of _void evaluate(Solution solution)_ is:

```
      solution.setObjective(0,   obj1[0]); //Minimize .
    solution.setObjective(1,  -obj2[0]); //Maximize.

    solution.setConstraint(0, obj1[0] <= NUM1 ? 0 : obj1[0]); 
    solution.setConstraint(1, obj2[0] >= NUM2 ? 0 : obj2[0]);
```

I want my obj1[0] to be smaller than NUM1 and obj2[0] to be greater than NUM2. However, NSGAII is minimizing both objectives. The only way that i find to achieve what I want was to set:

```
    solution.setConstraint(1, obj2[0] <= NUM2 ? 0 : obj2[0]);
```

This way, at first glance it seems that NSGAII is minimizing obj1[0] while maximizing obj2[0], but it is not make any sense to me... Any tips?

Regards!

**Comment by dhadka** [comment]
Hello.  Sorry for not responding earlier; I was traveling the past two weeks.  Are you able to share the code?  You can post it here or send it to me privately at support@moeaframework.org.  Thanks in advance.

**Comment by AMARJEET-NITKKR** [comment]
Sir,

how we can generate the results after certain generations: for example results after generation 10, 20, 30 , 40 ,   .........; and how to plot it with some objective function

**Comment by dhadka** [comment]
You would want to use the `Instrumenter` that, which lets you record runtime dynamics for an algorithm.  Please see [Example3.java](http://moeaframework.org/examples.html#example3) for more information.  For example, here's a quick example where I plot NFE versus the maximum objective value.

```java

		Instrumenter instrumenter = new Instrumenter()
				.withProblem("UF1")
				.withFrequency(100)
				.attachApproximationSetCollector();
		
		new Executor()
				.withProblem("UF1")
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(10000)
				.withInstrumenter(instrumenter)
				.run();
		
		Accumulator accumulator = instrumenter.getLastAccumulator();
		
		List<Integer> xs = new ArrayList<Integer>();
		List<Double> ys = new ArrayList<Double>();
		
		for (int i = 0; i < accumulator.size("NFE"); i++) {
			// determine the maximum objective value
			double maxObj = Double.NEGATIVE_INFINITY;
			
			for (Solution solution : (List<Solution>)accumulator.get("Approximation Set", i)) {
				maxObj = Math.max(maxObj, solution.getObjective(0));
			}
			
			// update the series to plot
			xs.add((Integer)accumulator.get("NFE", i));
			ys.add(maxObj);
		}
		
		new Plot()
				.line("Objective 1 (Max)", xs, ys)
				.show();
```
