### ISSUE TITLE
How to change the color of points in the plotting?

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#56]
Hi, David, I have a simple question. When I plot the result with a simple command I can get a nice graph. But I want to change the color of all the points from red to blue. I think it's easy but I am not familiar with java plots, could you please tell me how to do that ? Thanks in advance.

**Comment by dhadka** [comment]
Using the [Plot](http://moeaframework.org/javadoc/org/moeaframework/analysis/plot/Plot.html) class, there is a [withPaint(...)](http://moeaframework.org/javadoc/org/moeaframework/analysis/plot/Plot.html#withPaint(java.awt.Paint...)) method you can use.  The argument can be any color (predefined or custom) using the [Color](https://docs.oracle.com/javase/7/docs/api/java/awt/Color.html) class.  For example:

```java

new Plot()
        .scatter("Point", new double[] { 0.0, 1.0, 2.0 }, new double[] { 3.0, 4.0, 5.0 })
        .withPaint(Color.BLUE)
        .show();

**Comment by longmeili** [comment]
Thank you.Please close the issue.
