### ISSUE TITLE
how can i read the data in pf folder?

### ISSUE THREAD

**Issue by zhoudiprivateChina** [MOEAFramework/MOEAFramework#59]
Hi, it seems that the pf folder contains the true pareto front of all test problems, but how can i open these .pf things? I want to get the data of true pareto front of each test problem. Thanks very much

**Comment by zhoudiprivateChina** [comment]
Hey, me again. I try to get the true pareto front using the following code:

        WFG2 problem = new WFG2(1,10,2);
		Population trueParetoFront = new Population();
		Solution temp = null;
		double[] f1 = new double[490];
		double[] f2 = new double[490];

		for (int i = 0;  i< 490; i++) {
		    trueParetoFront.add(problem.generate());
		}
		
		for (int i = 0;  i< 490; i++) {
		   temp = trueParetoFront.get(i);
		   f1[i] = temp.getObjective(0);
		   f2[i] = temp.getObjective(1);
		}

However, when i plot(f1,f2,'.') in matlab, i got this:
![image](https://cloud.githubusercontent.com/assets/16380025/16895301/05be23c2-4ba5-11e6-9131-0d4c8eb51f39.png)
It seems the ture pareto front of WFG2 should be a part of the points above, look much like the below:
![image](https://cloud.githubusercontent.com/assets/16380025/16895319/8567d7a8-4ba5-11e6-9819-8a3bb5597928.png)

Is there something wrong in my code ?? Thanks so much

**Comment by dhadka** [comment]
From the documentation for the [generate()](http://moeaframework.org/javadoc/org/moeaframework/problem/AnalyticalProblem.html#generate()) method:

> Returns a randomly-generated solution using the analytical solution to this problem. Note however that discontinuous Pareto surfaces may result in some solutions generated by this method being dominated by other generated solutions. It is therefore recommended using a NondominatedPopulation to removed dominated solutions prior to using the generated reference set.

> The generated solutions should be spread uniformly across the entire Pareto frontier; however, this is a suggestion and is not a requirement of this interface. 

Try putting the solutions in a [NondominatedPopulation](http://moeaframework.org/javadoc/org/moeaframework/core/NondominatedPopulation.html) to remove the dominated points.

You can also load the [PopulationIO.readObjectives(...)](http://moeaframework.org/javadoc/org/moeaframework/core/PopulationIO.html#readObjectives(java.io.File)) method to load one of the files in the pf/ folder.

**Comment by zhoudiprivateChina** [comment]
dhadka, 👍 , I have got what i want according to your suggestion. Thank you so much.

But I have another question:
Comparison results in many paper all demonstrate OMOPSO performs better than NSGAII. But when I test by MOEAFRAMEWORK, i find NSGAII works much better than OMOPSO. Here are my test results, red parts are those NSGAII outperforms OMOPSO:
![image](https://cloud.githubusercontent.com/assets/16380025/16898904/8b7bdb32-4c20-11e6-814c-4a2e3f3474ea.png)
![image](https://cloud.githubusercontent.com/assets/16380025/16898916/4e321150-4c21-11e6-909f-168648968d16.png)
![image](https://cloud.githubusercontent.com/assets/16380025/16898924/c350a0a0-4c21-11e6-8d3e-3d4b5a6126c8.png)

And here are cut from 
![image](https://cloud.githubusercontent.com/assets/16380025/16898933/75f90f9e-4c22-11e6-84c9-9b0b701ac499.png)

![image](https://cloud.githubusercontent.com/assets/16380025/16898928/27fb7b88-4c22-11e6-965e-6427d2fcbefe.png)

![image](https://cloud.githubusercontent.com/assets/16380025/16898942/d42c9658-4c22-11e6-8725-142ce159ecad.png)


Especially on WFG2_2, NSGAII works so good........Is there some special set unlike Durillo's work in NSGAII?

**Comment by zhoudiprivateChina** [comment]
Another question:
How can i get the pareto front data calculated by NSGAII?

**Comment by zhoudiprivateChina** [comment]
Hi, dhadka, I get the pareto front data by the following code:
            
       `double[] f1 = new double[100];
		double[] f2 = new double[100];

		List<NondominatedPopulation> result = new Executor()
				.withAlgorithm("OMOPSO")
				.withProblem("WFG2_2")
				.withMaxEvaluations(25000)
				.runSeeds(2);
		
		NondominatedPopulation nondominatedSet;
		int j = 0;
		for( int i = 0; i < 2; i++){
			nondominatedSet = result.get(i);
			
			for (Solution solution: nondominatedSet){
				if (!solution.violatesConstraints()){
					f1[j] = solution.getObjective(0);
					f2[j] = solution.getObjective(1);
					j++;
				}
			}
		}`

Is there any simple way?

**Comment by dhadka** [comment]
Yes, the performance difference is a known issue (see [here](https://github.com/MOEAFramework/MOEAFramework/issues/25) for a detailed discussion).  Essentially, there is a discrepancy between the OMOPSO algorithm as described in the paper and the OMOPSO implementation in JMetal 4 (which is developed by the same authors).  The paper states that OMOPSO uses an external epsilon-dominance archive and returns this archive as the result.  In the JMetal 4 implementation, they return the leaders.  This results in a difference in performance.  I've personally taken the stance to follow what is described in the paper.  Otherwise, the epsilon-dominance archive in OMOPSO is not used at all.

You can test this in one of two ways.  If you look at the `OMOPSO.java` class, you'll find a `TESTING_MODE=false` variable ([link](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/pso/AbstractPSOAlgorithm.java#L52)).  Setting this to `true` will replicate the OMOPSO implementation from JMetal 4 and produce results close to what you have copied above.  Alternatively, instead of using `.withAlgorithm("OMOPSO")` algorithm, use `.withAlgorithm("OMOPSO-JMetal")` to use the JMetal 4 version.  

For your second question about getting the Pareto set, if you want the data in two arrays (`double[]`), then the code you show is probably the simplest way.

**Comment by zhoudiprivateChina** [comment]
Thank you so much. BTW, how to get the true pareto front of ZDTs?  It seems ZDT1-6 haven't generate() .

**Comment by dhadka** [comment]
I'm not aware of a deterministic way to generate the ZDT pareto fronts.  For such problems, I've either downloaded a Pareto front available online or generated one by combining the best results from many different algorithm runs.  We have provided sample Pareto front files for all of these problems in the `pf/` folder.  You can load one of these files with:

```java

NondominatedPopulation front = new NondominatedPopulation(
        PopulationIO.readObjectives(new File("pf/ZDT1.pf")));
```

The ZDT fronts can be found online, such as http://cpdee.ufmg.br/~fcampelo/files/EMO2011-cone/Pareto%20Fronts/ZDT1.txt or http://people.ee.ethz.ch/~sop/download/supplementary/testproblems/zdt1/index.php.

Just note that the values in the file should be separated by spaces.  The files available on the ETH Zürich link I provided above uses commas, which need to be replaced by spaces if you want to use them.
