### ISSUE TITLE
Query : How are function evaluations counted?

### ISSUE THREAD

**Issue by abhinavgaur** [MOEAFramework/MOEAFramework#60]
Hello

I want to run NSGA-II on a problem with some known number of generations and population size. I find that in MOEA-fw-2.10, I can achieve the same by setting the `Executor()` properties `populationSize` and `MaxEvaluations`. I want to make sure how `MaxEvaluations` is calculated. Putting my question in the form of example. 

If a 2-objective problem is run (single run) with population size `P` and maxEvaluations `E`, then is it equivalent to running NSGA-II with same population size for `E/P` generations?

Thanks

**Comment by dhadka** [comment]
Yes.

More precisely, it would be `ceil(E/P)`.  So if E is not a multiple of P, then it will run for one extra generation.

**Comment by abhinavgaur** [comment]
Thanks for replying so fast. I bought your Beginner's Guide and am finding some minor typos/mistakes. Example, on Page-29, you write; "... Inequality constraints are of the form <img src="http://www.sciweavers.org/tex2img.php?eq=h%28x%29%20%5Cgeq%20d&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="middle" border="0" alt="h(x) \geq d" width="55" height="14" /> for some constant _d_".  But in the Srinivas-Problem that follows, you show the constraint of the form <img src="http://www.sciweavers.org/tex2img.php?eq=h%28x%29%20%5Cleq%20d&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="middle" border="0" alt="h(x) \leq d" width="55" height="14" /> .

How can I make/report changes to the same so that it can be corrected in future versions.

**Comment by dhadka** [comment]
Topos/mistakes can be reported here, on Github's issue tracker.  Thanks for letting me know!
