### ISSUE TITLE
How to write data of each generation?

### ISSUE THREAD

**Issue by abhinavgaur** [MOEAFramework/MOEAFramework#61]
Hello,

I wish to write the data of each generation (all individuals) on to files. Can you tell me which class to modify for the same? Executor class looks little complicated to modify. 

Thanks

**Comment by dhadka** [comment]
Are you interested in all population members, or just the Pareto non-dominated solutions?

The `Instrumenter` class is used to collect runtime data for algorithms.  An example collecting Pareto non-dominated solutions can be found here: https://gist.github.com/dhadka/d3661b52fe0e81f103a5b4c2aedb20bc.  The `Instrumenter` is also discussed in Chapter 4 in the Beginner's Guide.

**Comment by abhinavgaur** [comment]
I am interested in all population members as in my problem, the feasible search space is very limited and I want to track how the different constraints are moving towards the constraint boundary. Solution to problem is not known, so this information may help me to tweak the constraint definitions.

How can I change the `Instrumenter` class to track entire population (all fronts). Do I have to do something like [this](https://gist.github.com/dhadka/a2db62c209ed1e2d90ef5eb25c9c4110)?

**Comment by dhadka** [comment]
Here's some example code: https://gist.github.com/dhadka/50c13c0cce249a6753bce72565e58e2f

In this example, I created a custom collector to record the population members.  Collectors are used by the Instrumenter class to grab specific data from an algorithm while it is running.  In this case, the collector will "attach" to any `EvolutionaryAlgorithm`, which essentially means any algorithm that has a population.  At the end of the example, I print the variables, objectives, and constraints to the console.
