### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by AMARJEET-NITKKR** [MOEAFramework/MOEAFramework#62]
Sir, thanks for reply for the my previous comments.

Now we have one more issue.

how to use NSGA-III algorithm, where is its implementation.

how to use onepoint (single point) crossover and onepoint mutation for integer variables

**Comment by dhadka** [comment]
All standard algorithms are created in [`StandardAlgorithms.java`](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/StandardAlgorithms.java#L358).  You can find the code that initializes NSGA-III and the implementing classes by following that link.

For your second question about using single-point crossover, this is a little bit more involved.  First, the problem must use the [BinaryIntegerVariable](http://moeaframework.org/javadoc/org/moeaframework/core/variable/BinaryIntegerVariable.html) for its decision variables.  Second, we need to define a new crossover operator for single-point crossover (the MOEA Framework only has half-uniform crossover (HUX) for binary types).  Finally, we must configure the algorithm to use this new operator.  All of this is demonstrated in this example: https://gist.github.com/dhadka/9b63587cb34f3115fd05b35f0ce0cdfd
