### ISSUE TITLE
UML charts for MOEA framework

### ISSUE THREAD

**Issue by abhinavgaur** [MOEAFramework/MOEAFramework#64]
Hello David,

Is there a UML chart available for MOEA-fw that might give new users an overall class hierarchical sense of the software? It may not be a detailed one (as that would be an information overload) but something that gives sense of top to bottom hierarchies.

Thanks

Abhinav

**Comment by dhadka** [comment]
No, but if you're using Eclipse, you could use the "Type Hierarchy" to view the class structure.  I got this by right-clicking on the `src/` folder and selecting "Open Type Hierarchy".

![typeheirarchy](https://cloud.githubusercontent.com/assets/2496211/17176952/ff0dd5dc-53dc-11e6-91e9-3f4f85b9a208.png)

**Comment by abhinavgaur** [comment]
Thanks David. I am using Netbeans. 

For anyone interested in accessing the the aforementioned information on Netbeans, please look [here](http://stackoverflow.com/a/1358927/842808).
