### ISSUE TITLE
Difference between NondominatedSortingPopulation and NondominatedPopulation

### ISSUE THREAD

**Issue by abhinavgaur** [MOEAFramework/MOEAFramework#68]
Hello David,

What is the difference between NondominatedSortingPopulation and NondominatedPopulation classes?

**Comment by dhadka** [comment]
NondominatedPopulation - Keeps all Pareto non-dominated solutions.

NondominatedSortingPopulation - Uses fast non-dominated sorting to compute the rank and crowding attributes.  These attributes can then be used to truncate the population to a fixed size, as in NSGA-II.
