### ISSUE TITLE
About the many-objective algorithm DBEA

### ISSUE THREAD

**Issue by henryyuri** [MOEAFramework/MOEAFramework#69]
Hello,

When I execute the following lines:

Executor executor = new Executor()
		.withProblemClass(DTLZ1.class,3)
		.withProperty("populationSize", 100)
		.withMaxEvaluations(10000);

		Analyzer analyzer = new Analyzer()
		.withProblemClass(DTLZ1.class,3)
		.withReferenceSet(new File("path\\XXX.pf"))
		.includeInvertedGenerationalDistance()
		.showIndividualValues();

		for (String algorithm : algorithms) {
			analyzer.addAll(algorithm, 
					executor.withAlgorithm(algorithm).runSeeds(30));
		}
		analyzer.saveAnalysis(new File("path\\DBEA_DTLZ1_3")).printAnalysis();

and error occurs:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 93, Size: 91
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.moeaframework.algorithm.DBEA.updatePopulation(DBEA.java:509)
	at org.moeaframework.algorithm.DBEA.iterate(DBEA.java:207)
	at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:161)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:803)
	at org.moeaframework.Executor.runSeeds(Executor.java:709)
	at Example2.main(Example2.java:488)

Thank you for your attention to this matter.

**Comment by dhadka** [comment]
Hi.  Thanks for reporting this bug.  In DBEA, the population size should be equal to the number of reference points.  However, it's incorrectly using the population size parameter causing the index out of bounds exception.  It is now fixed in the master branch.

**Comment by henryyuri** [comment]
Thank you, David. BTW, the link to the matlab version of DBEA is invalid in class DBEA .

public class DBEA
extends AbstractEvolutionaryAlgorithm
Implementation of the Improved Decomposition-Based Evolutionary Algorithm (I-DBEA). This implementation is based on the Matlab version published by the original authors.

References:

Asafuddoula, M., T. Ray, and R. Sarker (2015). "A Decomposition- Based Evolutionary Algorithm for Many-Objective Optimization." IEEE Transaction on Evolutionary Computation, 19(3):445-460.
**Matlab-DBEA.rar**  <---invalid

**Comment by dhadka** [comment]
Thanks for pointing that out.  Looks like it has moved to http://www.mdolab.net/Ray/Research-Data/Matlab-DBEA.rar
