### ISSUE TITLE
About the leader selection in OMOPSO

### ISSUE THREAD

**Issue by zhoudiprivateChina** [MOEAFramework/MOEAFramework#72]
Hi, me again. 
The function selectLeader() in OMOPSO in MOEAFRAMEWORK seems to select two leaders randomly from the archive, then decides which will be the leader participating the velocity updating by comparing their crowdingDistance. But in the paper "Improving PSO-base Multi-Objective Optimization using Crowding, Mutation and epsilon-Dominance" by Sierra and Coello, they select the leader by means of a binary tournament based on the crowding value of the leaders. I want to know whether it would lead to difference in performance?

**Comment by dhadka** [comment]
Hi, I'm not following what discrepancy you're seeing.  The `selectLeader()` method is performing a binary tournament using the crowding distance of the leaders.  This is the same crowding distance used in NSGA-II.  Could you please clarify/elaborate?  Thanks!
