### ISSUE TITLE
Elapsed Time and  Instrumenter

### ISSUE THREAD

**Issue by WendiWang** [MOEAFramework/MOEAFramework#73]
Elapsed time can be collected using the Instrumenter, but if the Executor is used to run an algorithm for multiple replications(like "runSeeds(50)"), how can I get the elapsed time of each running of the executor ? 

The following code, from my understanding, can only display the Elapsed Time of last running of the executor .

```
for (String algorithm : algorithms) { 
        analyzer.addAll(algorithm, executor.withAlgorithm(algorithm).runSeeds(30));

        Accumulator accumulator = instrumenter.getLastAccumulator();
        System.out.format("  NFE    Time      Hypervolume%n");

        for (int i=0; i<accumulator.size("NFE"); i++) {
            System.out.format("%5d    %-8.4f  %-8.4f%n",
                    accumulator.get("NFE", i),
                    accumulator.get("Elapsed Time", i),
                    accumulator.get("Hypervolume", i));
        }
}

```

Can you enlighten me on how to solve this issue? Thanks a lot!

**Comment by dhadka** [comment]
The instrumenter only reports the data from the last run.  The solution is to use a loop to individually run each of the 30 seed by calling `run()`, instead of calling `runSeeds(30)`.  Then, you can get the accumulator for each seed within the loop.  For example:

```java

		for (String algorithm : algorithms) {
			for (int i = 0; i < 30; i++) {
				analyzer.add(algorithm, executor.withAlgorithm(algorithm).run());
				
				Accumulator accumulator = instrumenter.getLastAccumulator();
				// read values from accumulator
			}
		}
```

**Comment by WendiWang** [comment]
I got it. Thank you very much!
