### ISSUE TITLE
 Decomposition approaches in MOEA/D

### ISSUE THREAD

**Issue by WendiWang** [MOEAFramework/MOEAFramework#74]
Hello, 

I have a question about MOEA/D. MOEA/D mainly includes three decomposition approaches: the weighted sum approach, Tchebycheff approach, and Boundary intersection approach. Which approach is the default approach in the MOEA Framework? How can I modify the code to realize the other approaches?

Thanks a lot!

**Comment by dhadka** [comment]
Hi,

Currently, it's setup with the Tchebycheff approach.  The relevant code can be found in `MOEAD.java` (found in the `src/org/moeaframework/algorithm` folder).  The following two changes would be required:

1. Supply a WeightGenerator to the [MOEAD Constructor](http://moeaframework.org/javadoc/org/moeaframework/algorithm/MOEAD.html#MOEAD(org.moeaframework.core.Problem,%20int,%20org.moeaframework.util.weights.WeightGenerator,%20org.moeaframework.core.Initialization,%20org.moeaframework.core.Variation,%20double,%20double,%20int)) to generate the weights.  By default, it uses the approach described in:

    > Zhang, Q., et al.  "The Performance of a New Version of MOEA/D on CEC09 Unconstrained MOP Test Instances."  IEEE Congress on Evolutionary Computation, 2009.

    There are a couple of default implementations available, such as uniform weights, normal boundary intersection, etc. provided in the `org.moeaframework.util.weights` package.  You can re-use these or write your own.

2. Edit the [fitness function](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/MOEAD.java#L555).  This function is used to compute the fitness of each individual in MOEA/D.  By default, it follows the Tchebycheff approach.  Unfortunately, it's currently a private method so you'll need to modify the `MOEAD.java` code and recompile.
