### ISSUE TITLE
hypervolume

### ISSUE THREAD

**Issue by WendiWang** [MOEAFramework/MOEAFramework#76]
Hello, 

I have a quick question. Is it possible to compute hypervolume of many-objective optimization problem? I found it is difficult to compute hypervolume of solutions from 8 objective problem on the MOEA Framework.

Thank you very much.

Best regards,

**Comment by dhadka** [comment]
See https://github.com/MOEAFramework/Hypervolume for instructions on compiling and integrating faster hypervolume codes.

**Comment by WendiWang** [comment]
I see, thank you very much!
