### ISSUE TITLE
Can I run single objective GA using MOEAFramework?

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#78]
Hi, David, I want to compare results of multi-objective optimization with single objective GA on a simple discrete problem, so I was wondering whether MOEAFramework supports single objective GA with HUX + BF as variation operators. Thanks in advance.

**Comment by dhadka** [comment]
It does, but you'll need to use the single_obj branch.  To download this branch using Git, you would do the following:

```
git clone https://github.com/MOEAFramework/MOEAFramework.git
git checkout single_obj
```

Then, you'd create a GA similar to before:

```
NondominatedPopulation result = new Executor()
				.withProblem("problemName")
				.withAlgorithm("GA")
				.withProperty("method", "linear")
				.withProperty("weights", new double[] { 0.5, 0.5 })
				.withProperty("operator", "hux+bf")
				.withMaxEvaluations(10000)
				.run();
```

In this case, it's solving a multiobjective problem using a linear-weighted sum of the objectives.  You could also pass in a problem with a single objective and skip the weights.

**Comment by longmeili** [comment]
Thank you, it works well.
