### ISSUE TITLE
Hi, I run DTLZ and WFG examples and get errors

### ISSUE THREAD

**Issue by yuxb111** [MOEAFramework/MOEAFramework#79]
Hi, the MOEA framework is a very good framework. Wonderful. I want to ask one quesiton:
when I use the framework to deal with CF1,CF2....,CF10,it is ok. However, when I run DTLZ and WFG examples, I get errors. I know I have to tell the framework how many objectives that I will use, I don't know how to implement in the framework. My code is as following:
package mytest.problem;

import org.moeaframework.Analyzer;
import org.moeaframework.Executor;
import org.moeaframework.core.NondominatedPopulation;
import org.moeaframework.core.Solution;

public class Example1 {public static void main(String[] args) {
	String  problem = "DTLZ1";
	String[] algorithms = { "NSGAII", "GDE3", "MOEAD" };
	         
	//setup the experiment
	Executor executor = new Executor()
	    .withProblem(problem)
	    .withMaxEvaluations(10000);
	         
	Analyzer analyzer = new Analyzer()
	    .withProblem(problem)
	    .includeHypervolume()
	    .showStatisticalSignificance();
	 
	//run each algorithm for 50 seeds
	for (String algorithm : algorithms) {
	    analyzer.addAll(algorithm, 
	        executor.withAlgorithm(algorithm).runSeeds(100));
	}
	 
	//print the results
	analyzer.printAnalysis();
}

}
ERROR message:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at org.moeaframework.problem.StandardProblems.getProblem(StandardProblems.java:645)
	at org.moeaframework.core.spi.ProblemFactory.instantiateProblem(ProblemFactory.java:172)
	at org.moeaframework.core.spi.ProblemFactory.getProblem(ProblemFactory.java:132)
	at org.moeaframework.ProblemBuilder.getProblemInstance(ProblemBuilder.java:328)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:771)
	at org.moeaframework.Executor.runSeeds(Executor.java:722)
	at mytest.problem.Example1.main(Example1.java:25)
Thank you very much.

**Comment by dhadka** [comment]
For scalable problems (DTLZ, WFG), add an underscore followed by the number of objectives.  For example, for 2D DTLZ1, use DTLZ1_2.  For 3D DTLZ1, use DTLZ1_3.

I will fix the error message so it's more clear.

**Comment by yuxb111** [comment]
Thank you very much for your reply. Now, I find  I can deal with the problem by the following code, can you tell me is it right?   
           DTLZ2 problem = new DTLZ2(3);//define DTLZ2 with 3 objectives
	String[] algorithms = { "NSGAII", "GDE3", "MOEAD" };
	         
	//setup the experiment
	Executor executor = new Executor()
	    .withProblem(problem)
	    .withMaxEvaluations(10000);
	         
	Analyzer analyzer = new Analyzer()
	    .withProblem(problem)
	    .includeInvertedGenerationalDistance()
	    .showStatisticalSignificance();
By the code, It run well, But I am not sure it is correct logically.

**Comment by dhadka** [comment]
Yes, that is correct.

**Comment by yuxb111** [comment]
OK.Thank you for your reply. Thank you for your wonderful framework.Best wishes
