### ISSUE TITLE
Can you tell me the reference paper about   Additive ε-Indicator  and Contribution

### ISSUE THREAD

**Issue by yuxb111** [MOEAFramework/MOEAFramework#80]
Hi, Thank you very much for your framework, For some Representations, I know ,such as IGD, GD, I am puzzled about Additive ε-Indicator  and Contribution. I see the java code, however, there is not reference paper information, which can tell me the real meaning for the   Additive ε-Indicator  and Contribution.
So, could you please tell me the the reference paper about   Additive ε-Indicator  and Contribution. Thank you very much. 
Best wishes.

**Comment by dhadka** [comment]
The binary epsilon-indicator is described in [Zitzler & Kunzli (2004)](http://www.tik.ee.ethz.ch/sop/publicationListFiles/zk2004a.pdf).

Contribution is similar to the coverage measure by [Zitzler & Thiele (1998)](http://link.springer.com/chapter/10.1007/BFb0056872), except it is defined with respect to a reference set.  You can think of contribution as calculating the percentage of the reference set (all Pareto optimal solutions) that is "covered" or "contributed" by an approximation set (the result of any MOEA run).  Contribution can be defined using either Pareto dominance or epsilon-dominance.  I personally prefer using epsilon-dominance as you set the distance epsilon by which solutions are considered equal.  To use epsilon-dominance, call the `Analyzer#withEpsilon(...)` method.

**Comment by yuxb111** [comment]
Thank you for your reply
