### ISSUE TITLE
May be there are some wrong for ZDT4 for moead

### ISSUE THREAD

**Issue by yuxb111** [MOEAFramework/MOEAFramework#82]
I test all ZDT1-ZDT6 except ZDT5. IGD values is compatible with original paper(http://dces.essex.ac.uk/staff/zhang/papers/moead.pdf). However, the metric IGD of ZDT4 is very different from the paper (pp.724, Table VII). So, I think maybe there are some wrong for ZDT4 function code or error Pareto front ? Please check. Thank you.

**Comment by dhadka** [comment]
I'll take a closer look.  Note though that the MOEA/D implementation in the MOEA Framework is based on the following two papers:

> [1] Li, H. and Zhang, Q. "Multiobjective Optimization problems with Complicated Pareto Sets, MOEA/D and NSGA-II." IEEE Transactions on Evolutionary Computation, 13(2):284-302, 2009.

> [2] Zhang, Q., et al. "The Performance of a New Version of MOEA/D on CEC09 Unconstrained MOP Test Instances." IEEE Congress on Evolutionary Computation, 2009. 

So there are some implementation differences (including, for example, the use of the differential evolution operator).  This may account for some of the observed differences.

**Comment by yuxb111** [comment]
Thank you for your reply.

**Comment by yuxb111** [comment]
Besides, Can you tell me where is HypE. I test HypE, it always tells me there is no such class. I don't submit a new topic. Just use this topic to ask you for help. Thank you

**Comment by dhadka** [comment]
HypE is an external algorithm (part of the PISA Framework) and needs to be installed separately.  Details can be found in Appendix B.2 in the [Beginner's Guide to the MOEA Framework](https://github.com/MOEAFramework/MOEAFramework/releases/download/v2.11/MOEAFramework-2.11-BeginnersGuidePreview.pdf).

**Comment by yuxb111** [comment]
Thank you very much for your reply. Best wishes.

**Comment by yuxb111** [comment]
Could you please tell me which java package NSGAIII is located? Thank you very much. I can not find it .

**Comment by ninanxiaoguai** [comment]
> I test all ZDT1-ZDT6 except ZDT5. IGD values is compatible with original paper(http://dces.essex.ac.uk/staff/zhang/papers/moead.pdf). However, the metric IGD of ZDT4 is very different from the paper (pp.724, Table VII). So, I think maybe there are some wrong for ZDT4 function code or error Pareto front ? Please check. Thank you.

hello! Recently, I meet the same problem. May I ask you how you solve?
