### ISSUE TITLE
  Could you please tell me which java package NSGAIII is located? 

### ISSUE THREAD

**Issue by yuxb111** [MOEAFramework/MOEAFramework#83]
Could you please tell me which java package NSGAIII is located?  Thank you very much. I can not find it . However, I can run it well, so I feel very strange. Thank  you. Best wishses.

**Comment by dhadka** [comment]
Hi, you can find the code that creates the standard algorithms, including NSGAIII, in [StandardAlgorithm.java](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/StandardAlgorithms.java#L361).

**Comment by yuxb111** [comment]
Thank you very much . Good Luck,
