### ISSUE TITLE
Define  the number of position-related variables and the number of distance-related variables in WFG?

### ISSUE THREAD

**Issue by yuxb111** [MOEAFramework/MOEAFramework#84]
Excuse me, how can I define the number of position-related variables and the number of distance-related variables in WFG? I try different values, indicators are quite different. So, can you tell me the default value for all WFG ?I  try to read the paper, but I can not find the related setting. Thank you very much.

**Comment by dhadka** [comment]
Hi, the defaults are located here: https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/problem/StandardProblems.java#L654

**Comment by yuxb111** [comment]
Thank you  very much.
