### ISSUE TITLE
How to generate Pareto front of WFG 

### ISSUE THREAD

**Issue by yuxb111** [MOEAFramework/MOEAFramework#86]
Hi, Best wishes for coming Thanksgiving day.
I learn about how to generate Pareto front of ZDTL according to previous requests, However, I still do't konw how to generate Pareto front of WFG,Could you tell me ?Thank you very much.

**Comment by Sweetxxy** [comment]
Hi,I also have the same question as yours , I am not sure if you have solved the problem , hope your answer .Thank you very much in advance.

**Comment by dhadka** [comment]
The details are discussed here: https://github.com/MOEAFramework/MOEAFramework/issues/49

For WFG, you would either use:

```java

// 3-objective WFG1
WFG1 problem = new WFG1(2, 10, 3);

// Store generated points in a epsilon-box archive to maintain an even spacing between solutions
EpsilonBoxDominanceArchive trueParetoFront = new EpsilonBoxDominanceArchive(
    new double[] { 0.01, 0.01, 0.01 });

// Generate the points
for (int i = 0;  < 100000; i++) {
    trueParetoFront.add(problem.generate());
}
```

or from the command line:

```
java -cp "lib/*" org.moeaframework.analysis.sensitivity.SetGenerator -b WFG1_3 -n 100000 -e 0.01,0.01,0.01 -o WFG1.3D.pf
```
