### ISSUE TITLE
NormalizationOfObjectiveFunctionValues

### ISSUE THREAD

**Issue by Diksha13Arora** [MOEAFramework/MOEAFramework#89]
I am working on an external problem in MOEA framework and want to calculate metrics such as hypervolume for my problem and have 3 fitness function . Two are for minimization and one is for maximization and the range of all 3 fitness function is different. First and second varies from 0 to 30000 and third can take negative values.
How to normalize all the objective function values ?

**Comment by dhadka** [comment]
Hi, I assume you're using the Analyzer to compute the hypervolume (if not, similar advice applies if you're using the Hypervolume class directly).  The Analyzer will always normalize the population prior to computing the hypervolume.  How it normalizes depends on what options you specify.

1. If no options are given, it will automatically compute a reference set by combining the results from each run (all algorithms and seeds).  The range of each objective in the reference set will determine the normalization.

2. If you have a reference set for the problem, you can set it using `analyzer.withReferenceSet(new File("refSet.txt"));`.  The range of each objective in the reference set will determine the normalization.

3. If you know the ideal and reference points (min and max values), call `analyzer.withIdealPoint(...)` and `analyzer.withReferencePoint(...)`.

There are some additional configuration options in the `global.properties` file if you want more control over the calculation.

**Comment by dhadka** [comment]
Closing issue.  Please reopen or create a new issue if you have any further questions.
