### ISSUE TITLE
Question about the Hypervolume

### ISSUE THREAD

**Issue by Nozo** [MOEAFramework/MOEAFramework#9]
I use your GUI with the following Controls:
Algorithm: NSGAII
Problem:  DLTZ1_2
Seeds: 10
MAX NFE: 50.000 

I figured out (with the help of the comments in the global.properties file) the the reference point for the hypervolume should be at (1,1) for a 2 dimensional problem. 

I am a little bit confused about the result because it is about 0,49 but I expect something like 0,875 for an infinity number of points ?! The Pareto Front of the DTLZ is a line form 0,5 to 0,5 so its just 1 - 0,125 for the Hypervolume with an infinity number of points?! Where I am wrong?

Is there a way in the source code if I use the Hypervolume class in my own design to change the reference point ?!

Another Issue is that the GUI crashes if I am trying to save the results with multiple results ( about 20). Its not so important for just for your information.

**Comment by dhadka** [comment]
Hi,

Hypervolume, like most other performance indicators, are normalized so the values of the objectives lie between 0 and 1.  The *normalized* DTLZ1 Pareto front is a line from (0,1) to (1,0), which given a reference point of (1, 1) will result in a hypervolume of 0.5.

Thanks for reporting the GUI crash.  My gut instinct is that Java's running out of memory during the save operation, and probably needs more heap space (using the `-Xmx` option when running java).  

Dave

**Comment by Nozo** [comment]
Thanks for the information. 
So I am right in the assumption that there is no way of changing the reference point?
If I reduce the number of evaluations there are often some aberrations (in one of the objectives the best value in the one a relative "bad" value), so the behaviour of the algorithm is right but the normalization of the Hypervolume is distorted (Hypervolume values over 0.5 for DTLZ 1). 
Do you have an advice for this circumstance without raising the NFE?!

**Comment by dhadka** [comment]
The hypervolume calculation, which is copied from PISA, assumes the reference point is at (1, 1).  There is no way to directly change it.  (You can give it a different reference set to change how it normalizes the objectives).

You might have better luck with the [WFG hypervolume code](https://github.com/MOEAFramework/Hypervolume/tree/master/WFG), which lets you specify the reference points.  However, it is designed for maximization problems, so you'd need to "flip" or negate the objectives.

The hypervolume exceeding 0.5 could also be a bug.  If you attach an example set producing the incorrect result, I'd be happy to investigate further.

**Comment by Nozo** [comment]
If there only a few NFE lets say 10.000 or less there might be a wrong result because of the normalization. This occurs also if I use the Executor and Analyser. The table below shows 11 individuals with their objective fitness. The Problem is Solution 2! All other solutions are on the Pareto Front except Solution 2. The solution is Nondominated because of the best value of Objective 2. The normalization of the Hypervolume is done with the maximum occurred value of each objective (which is Solution 2 for Objective 1). Therefore the complete normalisation is distorted. I think this circumstance should be avoided by using a reference set but how to create this over a few runs by not increasing the NFE ?!.

	Nr. of Solution |      Objective 1	           |           Objective 2
----------------| --------------------- | --------------------------
1	| 0,0000229246	             |          19,01973061
2	| 31,7491673524	     |           3,03E-06
3	| 19,0197474151	     |           6,12E-06
4	| 8,4242443871	             |          10,59550915
5	| 6,7781650398	             |          12,24158849
6	| 3,5506272857	             |          15,46912625
7	| 15,1581159484	     |          3,861637585
8	| 11,7301553248	     |           7,289598209
9	| 2,3957323296	             |           16,6240212
10	| 12,3885894274	     |           6,631164106
11	| 14,7504872521	     |           4,269266282

**Comment by dhadka** [comment]
Ah, I see.  You could also try the following.  It essentially creates a "fake" reference set to store your reference point.  This should then stabilize the normalization when you encounter those extreme points.

    NondominatedPopulation referenceSet = new NondominatedPopulation()
    referenceSet.add(new Solution(new double[] { 0.0, 0.0 })); // ideal point for DTLZ1
    referenceSet.add(new Solution(new double[] { 35, 35 })); // your reference point

    Hypervolume hyp = new Hypervolume(problem, referenceSet);

Since you're using the Analyzer, you can accomplish the same by creating a file storing the reference points:

    0.0 0.0
    35 35

and reference this file using the Analyzer:

    analyzer.withReferenceSet(new File("myRefSet.txt")

(Unfortunately, the Analyzer currently only loads the reference set from a file.  I'll fix this in the future so it can accept a NondominatedPopulation as well.)

**Comment by dhadka** [comment]
Closing this ticket.  Please re-open or create a new issue if you have further questions.
