### ISSUE TITLE
Statistical analysis with Knapsack

### ISSUE THREAD

**Issue by emelmdn** [MOEAFramework/MOEAFramework#90]
Hello,
I am trying to make statistical comparison of some algorithms by using Analyzer and Executor on the same Knapsack example file. But I get following error:

_Exception in thread "main" org.moeaframework.core.FrameworkException: 
My source code is as follows:

public class KnapsackExample {

	/**
	 * Starts the example running the knapsack problem.
	 * 
	 * @param args the command line arguments
	 * @throws IOException if an I/O error occurred
	 */
	public static void main(String[] args) throws IOException {
			
		String[] algorithms = { "NSGAII", "SPEA2", "OMOPSO" };
		
		//setup the experiment
		Executor executor = new Executor()
			.withProblemClass(Knapsack.class, Knapsack.class.getResourceAsStream("knapsack.750.4"))
		    .withMaxEvaluations(10000);
	
		Analyzer analyzer = new Analyzer().withSameProblemAs(executor)
			.withProblemClass(Knapsack.class, Knapsack.class.getResourceAsStream("knapsack.750.4"))
			.includeHypervolume()
		    .showStatisticalSignificance();
		 
		//run each algorithm for 50 seeds
		for (String algorithm : algorithms) {
		    analyzer.addAll(algorithm, executor.withAlgorithm(algorithm).runSeeds(50));    
		}

		//print the results
		analyzer.printAnalysis();
	}
}

Thanks in advance...

**Comment by dhadka** [comment]
Hi,

Please try passing the input as a `File` rather than an input stream.  The problem is the input stream keeps getting closed; whereas the `File` input ensures it has to re-open the file every run.

```java

	public static void main(String[] args) throws IOException {
		String[] algorithms = { "NSGAII", "SPEA2", "OMOPSO" };
		
		//setup the experiment
		Executor executor = new Executor()
			.withProblemClass(Knapsack.class, new File("examples/org/moeaframework/examples/ga/knapsack/knapsack.100.2"))
		    .withMaxEvaluations(10000);

		Analyzer analyzer = new Analyzer()
			.withSameProblemAs(executor)
			.includeHypervolume()
		    .showStatisticalSignificance();
		 
		//run each algorithm for 50 seeds
		for (String algorithm : algorithms) {
		    analyzer.addAll(algorithm, executor.withAlgorithm(algorithm).runSeeds(50));    
		}

		//print the results
		analyzer.printAnalysis();
	}
```

**Comment by emelmdn** [comment]
Hello,

It worked, thanks a lot.

**Comment by emelmdn** [comment]
Hello dhadka,

It worked for NSGA2 and SPEAs but I receive the following error message for OMOPSO. Is there any specific constructor or library so that I can use OMOPSO? (The code is the same as above)

_Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for OMOPSO_

Many thanks in advance.

**Comment by dhadka** [comment]
OMOPSO only supports real-values and won't work on binary problems such as the Knapsack problem.  More details on what types each algorithm support can be found here: http://moeaframework.org/javadoc/overview-summary.html#listOfAlgorithms.

**Comment by emelmdn** [comment]
Thanks a lot!
