### ISSUE TITLE
How to use the Instrumenter whith customized algorithm parameters 

### ISSUE THREAD

**Issue by applibres** [MOEAFramework/MOEAFramework#91]
Hi David, 
I am new using moeaframework and I have a question related with Instrumenter object. According the documentation, the Instrumenter works with Executor object.
But if we use the parametrization option when we need to customize the algorithm, I wonder if is possible to use an Instrumenter?
For example if we have the next code:

` 
Variation variation = new GAVariation( new OnePointCrossover(0.0),new pm);
		
		NSGAII algorithm = new NSGAII( 
				problem,
				new NondominatedSortingPopulation(), 
				null,
				new TournamentSelection(2, new ChainedComparator(new ParetoDominanceComparator(), new CrowdingComparator())),
				variation,
				new RandomInitialization(problem, 200));
		
		while (algorithm.getNumberOfEvaluations() < 10000) { 
			algorithm.step();
		}
		
		NondominatedPopulation result = algorithm.getResult();
 `
 It is possible to apply an Instrumenter?
 
 Thanks.

**Comment by dhadka** [comment]
Hi,

I'll provide solutions for two scenarios.  If you simply want to change the parameterization of an algorithm, you can use the `Executor` and `Instrumenter` classes:

```java

		// setup the instrumenter to record the generational distance metric
		Instrumenter instrumenter = new Instrumenter()
				.withProblem("DTLZ2_2")
				.withFrequency(100)
				.attachElapsedTimeCollector()
				.attachGenerationalDistanceCollector();
		
		// use the executor to run the algorithm with the instrumenter
		new Executor()
				.withSameProblemAs(instrumenter)
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(10000)
				.withProperty("operator", "1x+pm") // single point crossover with polynomial mutation
				.withProperty("1x.rate", 0.0)
				.withProperty("pm.rate", 1.0)
				.withProperty("pm.distributionIndex", 15.0)
				.withProperty("populationSize", 200)
				.withInstrumenter(instrumenter)
				.run();
		
		Accumulator accumulator = instrumenter.getLastAccumulator();
		
		// print the runtime dynamics
		System.out.format("  NFE    Time      Generational Distance%n");
		
		for (int i=0; i<accumulator.size("NFE"); i++) {
			System.out.format("%5d    %-8.4f  %-8.4f%n",
					accumulator.get("NFE", i),
					accumulator.get("Elapsed Time", i),
					accumulator.get("GenerationalDistance", i));
		}
```

The available parameters can be found in Appendix C in the [Beginner's Guide to the MOEA Framework](https://github.com/MOEAFramework/MOEAFramework/releases/download/v2.11/MOEAFramework-2.11-BeginnersGuidePreview.pdf).  

If you find yourself modifying the algorithms beyond just changing the parameters, then it gets a little bit more advanced.  There are actually two ways to handle this scenario.  The first involves creating a new `AlgorithmProvider` for the custom algorithm following the steps discussed in Chapter 5 within the Beginner's Guide.  Once you have the `AlgorithmProvider`, you can use the code from above and simply replace `withAlgorithm("NSGAII")` with your new algorithm.

The second way to handle this case is to use the underlying `InstrumentedAlgorithm` and `Collector` classes.  This is a bit more tricky to get right, but it's the most flexible option.  Here's an example that will produce similar results to the code above:

```java

		Variation variation = new GAVariation( new OnePointCrossover(0.0), new PM(1.0, 15.0));

		Problem problem = new DTLZ2(2);
		NondominatedPopulation referenceSet = new NondominatedPopulation(PopulationIO.readObjectives(new File("./pf/DTLZ2.2D.pf")));

		NSGAII nsgaii = new NSGAII( 
				problem,
				new NondominatedSortingPopulation(), 
				null,
				new TournamentSelection(2, new ChainedComparator(new ParetoDominanceComparator(), new CrowdingComparator())),
				variation,
				new RandomInitialization(problem, 200));

		InstrumentedAlgorithm algorithm = new InstrumentedAlgorithm(nsgaii, 100);
		algorithm.addCollector(new ElapsedTimeCollector());
		algorithm.addCollector(new IndicatorCollector(new GenerationalDistance(problem, referenceSet), null, nsgaii));
		
		while (algorithm.getNumberOfEvaluations() < 10000) { 
			algorithm.step();
		}

		// display the runtime dynamics
		Accumulator accumulator = algorithm.getAccumulator();
		System.out.format("  NFE    Time      Generational Distance%n");
		
		for (int i=0; i<accumulator.size("NFE"); i++) {
			System.out.format("%5d    %-8.4f  %-8.4f%n",
					accumulator.get("NFE", i),
					accumulator.get("Elapsed Time", i),
					accumulator.get("GenerationalDistance", i));
		}
```

**Comment by applibres** [comment]
David, Thanks, so much.
I am trying to get the population for each generation for that reason I have followed the code from:
https://gist.github.com/dhadka/50c13c0cce249a6753bce72565e58e2f

But, I have used the custom algorithm parametrization following the steps  from Chapter 5. 
Also, I have a computational expensive problem (PtProblem), for that reason I am trying Master-Slave model.
So, in summary I have tried the following:

`ExecutorService executor = Executors.newFixedThreadPool(5);
		
		Problem problem = new DistributedProblem (new PtProblem(5), executor);
		
		Variation variation = new GAVariation( new OnePointCrossover(1.0),new PtMutation());
		
		NSGAII algorithm = new NSGAII( 
				problem,
				new NondominatedSortingPopulation(), 
				null,
				new TournamentSelection(2, new ChainedComparator(new ParetoDominanceComparator(), new CrowdingComparator())),
				variation,
				new RandomInitialization(problem, 5));
		
	InstrumentedAlgorithm InstAlgorithm = new InstrumentedAlgorithm(algorithm, 5);
		InstAlgorithm.addCollector(new ElapsedTimeCollector());
		InstAlgorithm.addCollector(new PopulationCollector());

while (algorithm.getNumberOfEvaluations() < 20) { 
			algorithm.step();
		}

Accumulator accumulator = InstAlgorithm.getAccumulator();

executor.shutdown();


 for (int i = 0; i < accumulator.size("NFE"); i++) {
			
			
			nfeline=accumulator.get("NFE", i).toString();
			

				for (Solution solution : (List<Solution>)accumulator.get("Population", i)) {
				

					for (int j = 0; j < solution.getNumberOfVariables(); j++) {
						variableline+=solution.getVariable(j).toString()+" ";
					
					}
					

					for (int j = 0; j < solution.getNumberOfObjectives(); j++) {
						objectiveline+=solution.getObjective(j)+" ";
						
					}
}
`

But, I get the following error:

Exception in thread "main" java.lang.IllegalArgumentException: key not defined in accumulator: NFE

**Comment by dhadka** [comment]
Please try calling `InstAlgorithm.step()` within the while loop:

```java

	while (InstAlgorithm.getNumberOfEvaluations() < 20) {
		InstAlgorithm.step();
	}
```

**Comment by dhadka** [comment]
Closing issue.  Please reopen or create a new issue if you have any further questions.
