### ISSUE TITLE
FrequencyType option

### ISSUE THREAD

**Issue by TM00** [MOEAFramework/MOEAFramework#92]
Hi 

With regard to the `InstrumentedAlgorithm` class.  I noticed there are two types defined for measuring the frequency namely: evaluations and steps. I also saw that evaluations are by default used.

I thought the type could be chosen in certain cases for example when initiating an `Instrumenter`, but I did not manage to find a place where one can set the type without changing the default.

Could you add such an option in a future release? 

Thanks,
Theo

**Comment by dhadka** [comment]
Hi, thanks for reporting this issue.  It is fixed in 66729da7d34d869a1148fb73b46ad166d667ee3f and will appear in the next release.
