### ISSUE TITLE
How to define the reference set?

### ISSUE THREAD

**Issue by emelmdn** [MOEAFramework/MOEAFramework#95]
Hello,
I will test the performance of NSGA2, NSGA3 and SPEA2 algorithms on multi-objective multi-dimensional knapsack problem. As per defined in the manual, I am trying to collect best know algorithms' approximation sets and merge these populations on .pf file.  I run 4 algorithms (NSGA2, NSGA3 and SPEA2 and SMS-EMOA) and merged their results into .pf file.  Then I will compare the 3 algorithms mentioned above. Is this way correct? The only issue that I have here is it takes really long time especially big data with many objective MOMKP.
Thanks and regards.

**Comment by dhadka** [comment]
Yes, that is correct.

**Comment by emelmdn** [comment]
Thanks a lot!
