### ISSUE TITLE
NSGA-III is not included

### ISSUE THREAD

**Issue by almufdhali** [MOEAFramework/MOEAFramework#97]
NSGA-III is not included in the current version MOEAFramework-2.12 while it publicized on the website that is included.

**Comment by dhadka** [comment]
Hi @almufdhali , the details for NSGA-III can be found here: https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/StandardAlgorithms.java#L430

Here's an example using NSGA-III to solve the 3-objective DTLZ2 problem:

```java

NondominatedPopulation result = new Executor()
    .withProblem("DTLZ2_3")
    .withAlgorithm("NSGA-III")
    .withMaxEvaluations(10000)
    .run();
```

Please let me know if you have any issues getting this to work.  Thanks!

**Comment by dhadka** [comment]
Closing issue.  Please reopen or create a new issue if you have any further questions.
