### ISSUE TITLE
how to add "STEP" in algorithm

### ISSUE THREAD

**Issue by whhxp** [MOEAFramework/MOEAFramework#99]
Now I use NSGAII to optimize a design problem in reality. The variables should be generated by step, for example, a variable name called "diameter" ranges from 10 to 20, the step is 0.1, so the random and genetic operation results should be like 10.5, 12.1, 15.6.

**Comment by dhadka** [comment]
There are two possible ways re-using existing capabilities.  First, use the Real representation and round to one decimal point.

```java

public void evaluate(Solution solution) {
    diameter = EncodingUtils.getReal(solution.getVariable(0));
    diameter = Math.round(diameter * 10) / 10.0;
    ...
}

public Solution newSolution() {
    Solution solution = ...
    solution.setVariable(0, EncodingUtils.newReal(10, 20);
    return solution;
}
```

The potential downside to this approach is that small variations introduced by crossover/mutation may have no effect if the difference is less than 0.1.  A more complex but better approach would be to use the Binary Integer representation:

```java
private double min_diameter = 10.0;
private double max_diameter = 20.0;
private double steps = 10; // space values by 0.1 (1/steps)

public void evaluate(Solution solution) {
    int value= EncodingUtils.getInt(solution.getVariable(0));
    double diameter = min_diameter + (max_diameter-min_diameter)*(value / steps);
    ...
}

public Solution newSolution() {
    Solution solution = ...
    solution.setVariable(0, EncodingUtils.newBinaryInt((max_diameter-min_diameter)*steps));
    return solution;
}
```

**Comment by dhadka** [comment]
Closing issue.  Please reopen or create a new issue if you have any further questions.
